// KCGM plant flashcards.
// Each card: t = topic key, q = question, a = short answer, e = the why / detail.
// Sources: Plant Numbering Spec 2000-F00-STS-GE-10003, Growth Project WBS, Stage 2 Process Design Criteria
// 2000-F00-DCR-PR-10002, Stage 1 as built PFDs, Plant General Process Control Philosophy Stage 1 (2000-F00-REP-PR-10001)
// and Stage 2 (2000-F00-REP-PR-10002).

const TOPICS = {
  big: {name: "Big Picture", icon: "🧭", blurb: "Why the flowsheet looks the way it does"},
  codes: {name: "Area Codes", icon: "🔢", blurb: "F12, F16, F21... what people mean"},
  tags: {name: "Reading Tags", icon: "🏷️", blurb: "Equipment, motor, cable and instrument tags"},
  acro: {name: "Acronyms & Slang", icon: "💬", blurb: "The words you hear on the radio"},
  crush: {name: "Crushing", icon: "🪨", blurb: "ROM pad to coarse ore stockpile"},
  mill: {name: "Milling & Classification", icon: "⚙️", blurb: "SAG, ball mill, pebbles, cyclones"},
  grav: {name: "Gravity & ILR", icon: "✨", blurb: "Knelsons, intensive leach, gravity EW"},
  flot: {name: "Flotation", icon: "🫧", blurb: "Roughers, scavengers, Jamesons"},
  conc: {name: "Concentrate & UFG", icon: "🔬", blurb: "Thickening, IsaMills, CIL2/3"},
  cil4: {name: "Tails Leach (CIL4)", icon: "🛢️", blurb: "Flotation tails thickener and CIL4"},
  elu: {name: "Elution, Regen & Goldroom", icon: "🔥", blurb: "Stripping carbon and pouring doré"},
  util: {name: "Water, Air & Reagents", icon: "💧", blurb: "Services that keep it all running"},
  nums: {name: "Key Numbers", icon: "📊", blurb: "Throughput, grades, recoveries"},
  ctrl: {name: "Controls & DCS", icon: "🎛️", blurb: "Modes, interlocks, loops and trips"},
  hand: {name: "Shift Handover Scenarios", icon: "📻", blurb: "What does that report actually mean?"},
};

const CARDS = [

// BIG PICTURE
{t:"big", q:"Why can't KCGM simply grind the ore and put it all straight into cyanide leach?",
 a:"Much of the gold is locked inside sulphide minerals (mainly pyrite), so cyanide can't reach it",
 e:"KCGM ore is refractory. A large share of the gold is locked inside pyrite and tellurides. Think of it like a bolt seized inside a housing: the solvent (cyanide) can't get to it until you break the housing. That is why the flowsheet splits ore into a sulphide concentrate for extra treatment."},
{t:"big", q:"In one sentence, what are the two gold 'paths' through the plant?",
 a:"Free gold is leached from the bulk tails (CIL4), while sulphide concentrate is floated off, ultra fine ground and leached hard (CIL2/3)",
 e:"Almost every conversation maps to one of these two streams. The big, low grade stream (about 96% of the mass) is flotation tails leached in CIL4. The small, rich stream (about 4% of the mass) is the sulphide concentrate that gets UFG treatment then an aggressive leach in CIL2/3. Gravity skims off coarse free gold early."},
{t:"big", q:"What does flotation actually separate at KCGM?",
 a:"Sulphide minerals (pyrite carrying locked gold) from the non sulphide gangue",
 e:"Flotation makes sulphide particles water repellent so they stick to air bubbles and rise into the froth. The design sulphur recovery to concentrate is about 85%. Gold follows the sulphur because it is locked inside it."},
{t:"big", q:"Why grind the concentrate down to about 9 µm in the UFG mills?",
 a:"To physically break open the pyrite and expose locked gold to cyanide",
 e:"UFG (IsaMills) replaces the old roasting route. Instead of burning the sulphide off, you grind so fine that the gold bearing pyrite grains are cracked open. It costs a lot of energy per tonne (around 116 kWh/t) but only on the small concentrate mass."},
{t:"big", q:"Historically, where was the KCGM concentrate treated before the Growth Project consolidated it at Fimiston?",
 a:"Gidji, first through a roaster and later through ultra fine grinding",
 e:"Concentrate used to be hauled to Gidji. Stage 2 consolidates processing into a single hub at Fimiston, removing the concentrate haulage and targeting a 1 to 2% recovery uplift."},
{t:"big", q:"What does gravity recovery (Knelsons + ILR) catch that flotation and CIL would struggle with?",
 a:"Coarse free gold that is heavy, recirculates in the mill circuit and leaches slowly",
 e:"Coarse gold is so dense it tends to sit in the cyclone underflow and cycle through the ball mill again and again. Gravity pulls it out early. Design gravity recovery is about 14% of feed gold nominal, up to 20%."},
{t:"big", q:"Name the main steps of the bulk ore stream, in order, from truck to tails leach.",
 a:"Primary crusher → coarse ore stockpile → SAG mill → cyclones (with ball mill) → trash screens → rougher/scavenger flotation → tails thickener → CIL4",
 e:"Crush, SAG mill, classify in cyclones (ball mill closes the loop), cyclone overflow through trash screens to rougher/scavenger flotation, then flotation tails are thickened and leached in CIL4."},
{t:"big", q:"Why does the plant use activated carbon in the leach tanks (CIL = Carbon in Leach)?",
 a:"Carbon adsorbs the dissolved gold cyanide from solution so it can be screened out and stripped later",
 e:"Leaching dissolves gold into solution. Carbon granules act like a sponge for gold cyanide. Because the carbon is much coarser than the slurry, it can be held back by intertank screens and moved counter current, then pulled out loaded and sent to elution."},
{t:"big", q:"What is 'Stage 1' vs 'Stage 2' of the Growth Project in simple terms?",
 a:"Stage 1: new crusher, SAG, ball mill, gravity, flotation, UFG 2 and flotation tails thickener. Stage 2: new CIL4, UFG 3, CIL2/3 repurposed, extra elution/EW, and Gidji shut down",
 e:"In Stage 1 part of the thickened flotation tails went to the old CIL2/CIL3 and the rest straight to the TSF, and some concentrate was still filtered and trucked to Gidji. In Stage 2 all thickened tails go to CIL4 and all concentrate is treated at Fimiston. The drawings carry legends like 'SP1 AS BUILT' and 'SP2 NEW / SP2 DECOMMISSIONED'. SP means Separable Portion, the contract packages for Stage 1 and Stage 2."},
{t:"big", q:"On a PFD legend you see 'SP2 DECOMMISSIONED'. What does that line mean?",
 a:"That equipment or line is removed from service as part of Stage 2 (Separable Portion 2)",
 e:"SP = Separable Portion. Old plant items retired in the Stage 2 changeover are shown in that colour. Handy when people say 'that's gone in SP2'."},

{t:"big", q:"In Stage 1, where did the thickened flotation tails go?",
 a:"Part to the old CIL2 and CIL3 circuits (flow controlled to their capacity), the rest straight to the final tails tank and TSF",
 e:"In Stage 2 those branches are decommissioned and all flotation tails thickener underflow goes to the new CIL4."},
{t:"big", q:"In Stage 1, where was the concentrate leached?",
 a:"Part went through UFG 1 and UFG 2 into the existing concentrate CIL1 at Fimiston; the balance was deslimed, filtered and treated at Gidji",
 e:"Stage 2 adds UFG 3 and repurposes CIL2 (leach) and CIL3 (adsorption) so everything is treated at Fimiston and Gidji can be decommissioned."},
{t:"big", q:"What old plant became redundant in Stage 1?",
 a:"The entire Mt Charlotte processing plant, the Fimiston ball mills and the old Fimiston flotation circuit",
 e:"The Fimiston SAG and its pebble crushers stayed, now feeding the new ball mill and cyclones. An old Fimiston flotation tails thickener (No. 3) became the concentrate thickener."},

// AREA CODES
{t:"codes", q:"What is Area F12?",
 a:"Primary Crushing (new)",
 e:"F10 is the existing Fimiston primary crusher (Primary Crushing 1). F12 is the new primary crushing area (Primary Crushing 2), including the crushed ore stockpile and conveyors."},
{t:"codes", q:"What is Area F10?",
 a:"Primary Crushing, Fimiston Existing",
 e:"F10 = the existing Fimiston primary crusher. On the PFDs it is 'Primary Crushing 1' feeding the coarse ore stockpile."},
{t:"codes", q:"What is Area F13?",
 a:"Milling & Classification (new SAG, ball mill, pebble crushing, cyclones, trash screens)",
 e:"F13 is where the new SAG mill (F13-MS-401) and ball mill (F13-MB-401) live, plus stockpile reclaim, pebble crushing, cyclones and trash screens."},
{t:"codes", q:"What is Area F14?",
 a:"Gravity Circuit & Intensive Leaching",
 e:"F14 covers the gravity cyclones, scalping screens, Knelson concentrators and the Acacia intensive leach reactor (ILR)."},
{t:"codes", q:"What is Area F15?",
 a:"Mt Charlotte Stockpile / Reclaim",
 e:"F15 = Mt Charlotte stockpile and reclaim. You'll see F15 tags on the coarse ore conveyor feeding the Fimiston SAG mill."},
{t:"codes", q:"What is Area F16?",
 a:"Rougher & Scavenger Flotation",
 e:"F16 = the big forced air tank cells: 3 rougher cells (F16-CF-411 to 413) then 4 scavenger cells (F16-CF-414 to 417)."},
{t:"codes", q:"What is Area F17?",
 a:"Flotation Tailings Pre-Leach Thickening",
 e:"F17 thickens the scavenger tails and cleaner-scavenger tails before they go to CIL4. Thickening raises the slurry density so the leach tanks give more residence time for the same volume."},
{t:"codes", q:"What is Area F18?",
 a:"Cleaner & Cleaner-Scavenger Flotation (the Jameson cells)",
 e:"F18 holds the two Glencore Jameson B6500/24 cells, one on cleaner duty and one on cleaner-scavenger duty, plus the final concentrate hopper (F18-HP-414)."},
{t:"codes", q:"What is Area F19?",
 a:"Milling & Classification, Fimiston Existing (Area A)",
 e:"F19 is the old Fimiston SAG mill area (F19-MS-61). Its discharge is now pumped across to the new primary cyclone feed hopper so both SAGs share the new ball mill and cyclone cluster."},
{t:"codes", q:"What is Area F21?",
 a:"Flotation Tailings CIL4",
 e:"F21 = CIL4, the new leach and adsorption tanks for the flotation tails (F21-TK-411 to 418)."},
{t:"codes", q:"What is Area F22?",
 a:"CIL4 Carbon Treatment & Elution (incl. CIL4 carbon regeneration)",
 e:"F22 is the carbon side of CIL4: loaded carbon screen, acid wash/elution column, carbon regeneration kiln and the kiln off gas treatment."},
{t:"codes", q:"What is Area F23?",
 a:"Final Tailings Handling & Storage",
 e:"F23 covers the final tails tank, final tails pumps and booster pumps sending tailings to the storage facility (Fim III TSF is WBS T03)."},
{t:"codes", q:"What is Area F24?",
 a:"Air & Water Services (process, gland, raw, saline water, plant and instrument air)",
 e:"F24 is the new services area. Existing services have their own codes: F75 Water Services Existing and F81 Air Services Existing."},
{t:"codes", q:"What is Area F28?",
 a:"Ultra Fine Grinding 2/3 (the new IsaMills)",
 e:"F28 = the two new M15,000 IsaMills. The existing UFG (UFG 1, an M3000) is F34."},
{t:"codes", q:"What is Area F30?",
 a:"Concentrate Pre-Leach Thickening, CIL2/3 & Post-Leach Thickening",
 e:"F30 is the concentrate leach side. CIL2 is repurposed for leach duty, CIL3 for adsorption. You'll see tags like 30-TK-32A and F30-TK-62A."},
{t:"codes", q:"What is Area F34?",
 a:"Ultra Fine Grinding, Existing (UFG 1)",
 e:"F34 = the existing UFG 1 IsaMill (M3000). New UFG 2 and 3 are F28."},
{t:"codes", q:"What is Area F35?",
 a:"Concentrate Handling & Filtration",
 e:"F35 covers the concentrate thickener, filter feed tanks, vacuum belt filters and concentrate stockpile. Filters stay in service to handle concentrate in excess of UFG capacity."},
{t:"codes", q:"What is Area F65?",
 a:"Concentrate Carbon Treatment & Elution (the CIL2/3 carbon side)",
 e:"F65 handles loaded carbon from CIL3: carbon transfer vessels, acid wash, elution and quench tanks. CIL4's equivalent is F22."},
{t:"codes", q:"What is Area F66?",
 a:"Electrowinning & Goldroom",
 e:"F66 covers CIL4A/4B electrowinning, gravity electrowinning and the goldroom where cathode product is smelted to doré."},
{t:"codes", q:"What is Area F72?",
 a:"Reagents Mixing & Storage",
 e:"F72 WBS lines: PAX, frother, copper sulphate, oxygen, caustic, acid, cyanide, lead nitrate, LNG, lime and flocculant. F70 is the existing lime plant and flocculant, F71 existing reagents."},
{t:"codes", q:"What is Area F78?",
 a:"Carbon Regeneration, Existing",
 e:"F78 = the existing carbon regeneration kiln area. F75 = existing water services, F81 = existing air services."},
{t:"codes", q:"Someone says 'it's in 25/26'. Which areas are those?",
 a:"Existing Cleaner Flotation (F25) and existing Cleaner Scavenger Flotation (F26)",
 e:"F25 and F26 are the old cleaner circuits. The new cleaning circuit is F18 (Jameson cells)."},
{t:"codes", q:"What does the leading 'F' in every Growth Project tag stand for?",
 a:"Fimiston Site",
 e:"All Growth Project equipment carries the F prefix for Fimiston. In the WBS, level 1 letters are M Mining, F Fimiston Processing, T Tailings, N Non-Process Infrastructure, P Indirects."},
{t:"codes", q:"In the WBS, what is T03?",
 a:"Fim III Tailings Storage Facility (TSF)",
 e:"T = Tailings Facility. T03 covers the Fim III TSF, tailings pipeline, distribution, and return water."},
{t:"codes", q:"In the WBS, what is N02?",
 a:"Kaltails Borefields (saline water supply)",
 e:"N = Non-Process Infrastructure. N02 Kaltails Borefields includes pump stations, pipelines and the RO / acid water treatment. It is one of the saline water sources."},
{t:"codes", q:"A conveyor runs from F12 into F13. Which area code does it take?",
 a:"The area it feeds (head pulley location), so F13",
 e:"Per the Plant Numbering Spec, a conveyor takes the area code of the area it is feeding / where its head pulley sits."},
{t:"codes", q:"What is Area F00?",
 a:"General Fimiston Site (HV power, buried services, pipe racks, LV distribution)",
 e:"F00 is site wide general scope. Documents like 2000-F00-PFD... are general project documents too."},

// READING TAGS
{t:"tags", q:"Decode F13-MS-401.",
 a:"Fimiston, Milling & Classification area, SAG Mill, number 401",
 e:"Format is Prefix-Area-EquipmentCode-Number. MS = SAG mill. New equipment numbers start at 401 so they never clash with existing plant numbers."},
{t:"tags", q:"Why do new Growth Project equipment numbers start at 401?",
 a:"To avoid duplicating existing plant equipment numbers",
 e:"The spec says new equipment and new instruments in existing areas start at 401. So '4xx' is a quick hint you're looking at Growth Project kit, while low numbers like F19-MS-61 are legacy plant."},
{t:"tags", q:"Equipment code 'CF'?",
 a:"Flotation cell (column or cell)",
 e:"F16-CF-411 is Rougher Cell 1. F18-CF-501 is the cleaner Jameson cell."},
{t:"tags", q:"Equipment code 'MB'?",
 a:"Ball Mill",
 e:"F13-MB-401 = the new ball mill. MS = SAG mill, MU = existing UFG mill, MUF = new UFG mill."},
{t:"tags", q:"Equipment code 'CG'?",
 a:"Gyratory Crusher",
 e:"CG = gyratory crusher, CC = cone crusher (e.g. pebble crushers), CJ = jaw crusher."},
{t:"tags", q:"Equipment code 'CY'?",
 a:"Cyclone",
 e:"F13-CY-401 = the primary cyclone cluster. CR = cranes and hoists."},
{t:"tags", q:"What's the difference between 'PP' and 'PS' pump codes?",
 a:"PP = process pump, PS = sump pump",
 e:"PP for process duty pumps (e.g. cyclone feed pump F13-PP-401), PS for area sump pumps. PW = water pump, PT = transfer pump, PV = vacuum pump."},
{t:"tags", q:"Code 'SU' vs 'PS'. Which is the sump itself?",
 a:"SU is the sump only; PS is the sump pump",
 e:"The spec explicitly says SU = 'Sump (Sump Only! Not Sump Pump)'."},
{t:"tags", q:"Code 'FA'?",
 a:"Apron Feeder",
 e:"Feeders: FA apron, FB belt, FV vibrating, FS screw. Apron feeders sit under the crusher discharge and the stockpile."},
{t:"tags", q:"Code 'TH'?",
 a:"Thickener",
 e:"TH = thickener, TK = tank, AG = agitator, RK = rake mechanism."},
{t:"tags", q:"Code 'IL'?",
 a:"Intensive Leach Reactor",
 e:"The ILR (Acacia CS10000) leaches the Knelson gravity concentrate in batches."},
{t:"tags", q:"Code 'CN'?",
 a:"Elution Column",
 e:"CN = elution column. KN = kiln (carbon regeneration). CL/EC = electrowinning cells (new/existing). ER = electrowinning rectifier."},
{t:"tags", q:"Code 'WD'?",
 a:"Weightometer (belt scale)",
 e:"Weightometers measure tonnes per hour on conveyors, e.g. the SAG mill feed conveyor weightometer. They're your main throughput signal."},
{t:"tags", q:"Code 'MG'?",
 a:"Electro Magnet (tramp metal magnet)",
 e:"Tramp magnets on conveyors pull out steel (rock bolts, mesh, ground engaging tools) that would damage crushers and belts."},
{t:"tags", q:"The motor on pump F21-PU-001 is tagged how?",
 a:"F21PU001 (same number, dashes removed)",
 e:"Motors take the parent equipment number with dashes removed. Its VSD would be F21PU001-VS, its local control station F21PU001-LCS."},
{t:"tags", q:"Cable F21PU001-P1 vs F21PU001-C2. What's the difference?",
 a:"P1 is power cable number 1; C2 is control cable number 2 to the same equipment",
 e:"Circuit types: P power, N neutral, I instrumentation, C control, E earth, D digital/Ethernet, DC direct current, F fire, FO fibre optic."},
{t:"tags", q:"Decode instrument tag FIT13001.",
 a:"Flow Indicating Transmitter, Area 13, loop 001",
 e:"Instrument tags = letters + area + loop number. First letter is the measured variable (F flow), following letters the function (I indicate, T transmit). All parts of one loop share the number, e.g. PT13001, PIC13001, PCV13001."},
{t:"tags", q:"What does the first letter 'D' in an instrument tag like DT or DIT usually measure?",
 a:"Density",
 e:"First letter D = density (slurry density gauges, often nuclear). As a second letter D means differential. Density is critical on cyclone feed, thickener underflow and leach feed."},
{t:"tags", q:"First letter 'L' in an instrument tag?",
 a:"Level",
 e:"LT = level transmitter, LIC = level indicating controller. Sump, hopper and tank levels drive most pump speed loops."},
{t:"tags", q:"First letter 'A' (e.g. AE, AIT)?",
 a:"Analysis (pH, DO, cyanide, particle size etc.)",
 e:"A = analysis. As a second letter A means alarm, e.g. LAH = level alarm high."},
{t:"tags", q:"What does 'LAH' mean on a P&ID?",
 a:"Level Alarm High",
 e:"First letter L level, second letter A alarm, third letter H high. LAL would be level alarm low. Same pattern for PAH, TAH etc."},
{t:"tags", q:"Electrical code 'SW' on the Growth Project?",
 a:"Switchboard (HV and LV switchboards and MCCs)",
 e:"The spec says MCCs are referred to as switchboards, code SW. SR is the switchroom building, TR transformer, VS variable speed drive, SS soft starter."},
{t:"tags", q:"Electrical code 'LCS'?",
 a:"Local Control Station (field start/stop panel)",
 e:"The LCS is the push button station next to a drive, used for local operation and isolations. Tagged like F21PU001-LCS."},
{t:"tags", q:"Code 'VL'?",
 a:"Launder / Sump / Kibble",
 e:"On the flotation PFD, F16-VL-440 is the scavenger concentrate collection launder and F16-VL-438 the rougher 2 & 3 concentrate launder."},
{t:"tags", q:"Code 'SA' (as in F18-SA-403)?",
 a:"Isa Sampler (process sampler)",
 e:"SA samplers cut samples for the onstream analyser and metallurgical accounting, e.g. the final concentrate sampler."},
{t:"tags", q:"Code 'RB' at the crusher?",
 a:"Rock Breaker",
 e:"F10-RB-01 is the rock breaker on the crusher. It breaks oversize rocks that bridge in the crusher throat."},
{t:"tags", q:"Code 'CV'?",
 a:"Conveyor",
 e:"Conveyors are CV (e.g. F19-CV-21 recycle conveyor). Control valves are instrument tags like FCV or LCV."},

// ACRONYMS & SLANG
{t:"acro", q:"'ROM'?",
 a:"Run of Mine (ore as delivered from the pit)",
 e:"ROM ore arrives in CAT 793F haul trucks (about 250 t payload) and is tipped into the primary crusher dump pocket."},
{t:"acro", q:"'COS'?",
 a:"Coarse (Crushed) Ore Stockpile",
 e:"The COS is the buffer between the crusher (65% availability) and the mills (93.4% availability). The new one holds roughly 20,000 t live, about 11 h of mill feed."},
{t:"acro", q:"'SABC'?",
 a:"SAG mill, Ball mill, pebble Crusher circuit",
 e:"SABC: SAG mill does the coarse breakage, ball mill finishes the grind, pebble crushers break the critical size rocks the SAG can't handle."},
{t:"acro", q:"'SAG' mill?",
 a:"Semi Autogenous Grinding: the ore grinds itself with help from a small steel ball charge",
 e:"The new SAG is 10.97 m diameter (36 ft) × 8.38 m EGL with a 20 MW motor, running about 10.5% balls and 27% total load by volume."},
{t:"acro", q:"'P80' of 180 µm means...",
 a:"80% of the product mass passes 180 µm",
 e:"P80 = product size at 80% passing, F80 = feed size at 80% passing. The grind target to flotation is P80 180 µm (220 µm in the 28.35 Mtpa high throughput case)."},
{t:"acro", q:"'OSS' and 'CSS' on a crusher?",
 a:"Open Side Setting and Closed Side Setting (the max and min gap between mantle and concave)",
 e:"The new gyratory runs about 165 mm OSS. The pebble cone crushers run about 7 mm CSS. Tighter setting = finer product but more power and wear."},
{t:"acro", q:"'CIL'?",
 a:"Carbon in Leach: leaching and carbon adsorption happen in the same tank train",
 e:"KCGM talks about CIL2/3 (concentrate) and CIL4 (flotation tails). In the Stage 2 concentrate circuit, CIL2 is used for leach duty and CIL3 for adsorption."},
{t:"acro", q:"'ILR'?",
 a:"Intensive Leach Reactor",
 e:"The ILR is an Acacia CS10000 batch reactor that leaches Knelson gravity concentrate with strong cyanide. About 98% leach recovery."},
{t:"acro", q:"'UFG'?",
 a:"Ultra Fine Grinding (IsaMills grinding concentrate to about 9 µm)",
 e:"UFG 1 is the existing IsaMill M3000 (F34). UFG 2 and 3 are new M15,000 IsaMills (F28), about 3.5 MW draw each."},
{t:"acro", q:"'EW'?",
 a:"Electrowinning: plating gold out of pregnant solution onto cathodes",
 e:"Electrowinning passes current through cells so gold deposits on stainless steel cathodes. Cathode sludge then goes to the goldroom for smelting."},
{t:"acro", q:"'AARL' (as in split AARL elution)?",
 a:"Anglo American Research Laboratories elution method: hot caustic cyanide pre-soak then water elution",
 e:"AARL: acid wash, pre-soak with caustic cyanide, then elute with hot water. 'Split' means part of the eluate is recycled as lean eluate for the next strip."},
{t:"acro", q:"'PAX'?",
 a:"Potassium Amyl Xanthate, the flotation collector",
 e:"PAX coats sulphide surfaces making them water repellent so they attach to bubbles. It's dosed to rougher, scavenger and cleaner circuits."},
{t:"acro", q:"'CuSO₄' in flotation is used as...",
 a:"An activator, making pyrite surfaces more receptive to the collector",
 e:"Copper sulphate 'activates' pyrite. The PDC shows a dosing point at SAG mill discharge so it has conditioning time before flotation, plus cleaner dosing."},
{t:"acro", q:"'OSA'?",
 a:"Onstream Analyser (measures stream assays in near real time)",
 e:"Flotation feed, rougher concentrates, scavenger concentrate and tails, and final concentrate are all sampled to the OSA. It's how operators see grade and recovery trends shift by shift."},
{t:"acro", q:"'DO' in leach?",
 a:"Dissolved Oxygen",
 e:"Cyanide leaching needs oxygen. Sulphide rich slurries consume oxygen, so CIL2 and CIL4 have oxygen side lances and oxygen injection pumps."},
{t:"acro", q:"'WAD cyanide'?",
 a:"Weak Acid Dissociable cyanide, the environmentally relevant cyanide measure",
 e:"WAD CN is what regulators and wildlife care about at the TSF. Decant water is dosed with hydrogen peroxide to a residual WAD target, controlled by an online CNWAD analyser."},
{t:"acro", q:"'TSF'?",
 a:"Tailings Storage Facility",
 e:"Final tails are pumped to the Fim III TSF (WBS T03). Decant water returns to the plant as cyanide water."},
{t:"acro", q:"'BV' in elution?",
 a:"Bed Volume (one volume of the carbon bed)",
 e:"Elution steps are specified in BVs, e.g. 5 BVs of eluate. It scales the solution to the column size, like specifying flushing in 'system volumes'."},
{t:"acro", q:"'PSA' plant?",
 a:"Pressure Swing Adsorption oxygen plant",
 e:"The PSA plant makes oxygen for leaching (and the ILR) by adsorbing nitrogen from compressed air in cycling vessels. Liquid oxygen storage backs it up."},
{t:"acro", q:"'MoL'?",
 a:"Milk of Lime (slaked lime slurry for pH control)",
 e:"Quicklime is slaked to milk of lime and distributed on a lime ringmain to the leach feed boxes. High pH stops toxic HCN gas forming."},
{t:"acro", q:"'TML' for concentrate?",
 a:"Transportable Moisture Limit (max moisture for safe bulk shipment)",
 e:"Concentrate filtered for the stockpile must be under its TML (about 6 to 8% w/w) or it can liquefy in transport. The filter target is below 10% moisture."},
{t:"acro", q:"'%Cs' when talking mill speed?",
 a:"Percent of critical speed (the speed at which the charge centrifuges)",
 e:"The SAG runs 60 to 83% Cs on its VSD. Higher speed throws the charge harder (more impact) but risks liner damage if the load is low."},
{t:"acro", q:"'EGL' on a mill datasheet?",
 a:"Effective Grinding Length (inside liners)",
 e:"The new SAG EGL is 8.38 m vs 4.27 m on the old Fimiston SAG, same 10.97 m diameter. So nearly double the grinding volume."},
{t:"acro", q:"'Circ load' in the grinding circuit?",
 a:"Circulating load: cyclone underflow tonnes returned to the ball mill as a % of new feed",
 e:"Design is around 358% cyclone underflow to overflow. A mechanical analogy is a recirculating pump loop: high circ load keeps the mill full of near sized material to grind efficiently."},
{t:"acro", q:"'Mass pull' in flotation?",
 a:"The % of feed mass that reports to concentrate",
 e:"Rougher 1 pulls about 4.4%, roughers 2&3 about 2.4%, scavengers about 1.1% of feed mass. Too high a pull dilutes grade and overloads the concentrate side."},
{t:"acro", q:"'Froth factor' in the PDC?",
 a:"A design multiplier on concentrate pump/pipe sizing because froth carries air and occupies more volume",
 e:"Froth is a foam. The PDC applies factors of 1.6 to 2.5 to concentrate lines so pumps and launders don't airlock or overflow."},
{t:"acro", q:"'Scats'?",
 a:"Oversize rocks/steel rejected from the ball mill trommel",
 e:"The PFD shows a scats bunker by the ball mill trommel. Scats are worn balls and tough rocks that won't grind."},
{t:"acro", q:"'NSR' on drawings?",
 a:"Northern Star Resources (the owner)",
 e:"NSR is the owner. Primero was the EPC contractor. PDC = Process Design Criteria, TQ = Technical Query, SysCAD = the mass balance modelling software."},
{t:"acro", q:"'TQ' in project documents?",
 a:"Technical Query, a formal question and answer between contractor and owner",
 e:"Many design numbers trace back to TQs (e.g. CIL4 carbon advance, lime system design)."},
{t:"acro", q:"'Doré'?",
 a:"The gold/silver bar poured in the goldroom, sent to the refinery",
 e:"Electrowon sludge is dried and smelted with fluxes into doré bars. The refinery separates gold from silver and other metals."},
{t:"acro", q:"'Pregnant' vs 'barren' solution?",
 a:"Pregnant carries dissolved gold; barren has had the gold removed",
 e:"Same idea for carbon: loaded carbon holds gold, barren carbon is stripped. Lean eluate is partly used eluate recycled for the next strip."},

// CRUSHING
{t:"crush", q:"What type of primary crusher is in the new crushing area?",
 a:"Gyratory crusher (1300 × 1900 TSUV)",
 e:"A gyratory has a gyrating mantle inside a fixed concave bowl. It handles the huge throughput (design 3,135 t/h) and ROM top size near 1 m. Existing Primary Crushing 1 has a 54-75 Mk II gyratory."},
{t:"crush", q:"Which truck is the dump pocket designed around?",
 a:"CAT 793F (about 250 t payload)",
 e:"The dump pocket is direct tip from two sides, sized around the 793F heaped tray volume (about 179 m³ live from one side)."},
{t:"crush", q:"Why is the crusher design rate (≈3,135 t/h) much higher than the mill rate (≈1,833 t/h for the new circuit)?",
 a:"Crushing availability is only ~65% vs ~93% for milling, so it must crush faster while it runs",
 e:"Classic surge design. The crusher stops for truck gaps, blockages and maintenance, so it runs faster when running, and the stockpile evens it out. Same logic as sizing a compressor with a receiver."},
{t:"crush", q:"What's the typical crushed product size to the mills?",
 a:"P80 around 130 mm",
 e:"The new crusher gives P80 about 130 mm (145 mm in the high throughput case). The SAG mill is designed around that feed."},
{t:"crush", q:"What sits between the primary crusher and the conveyor to the stockpile?",
 a:"An apron feeder under the crusher discharge",
 e:"Apron feeders are heavy steel pan conveyors that take impact and control the draw rate. There's also a tramp magnet on the stockpile feed conveyor."},
{t:"crush", q:"How is ore reclaimed from the new coarse ore stockpile to the SAG mill?",
 a:"Apron reclaim feeders under the stockpile onto the SAG feed conveyor, plus one emergency feeder fed by loader",
 e:"Two reclaim apron feeders draw ore through tunnels under the pile. The emergency feeder lets a 992K/994K loader keep the mill fed if the live stockpile runs low."},
{t:"crush", q:"'Live capacity' of a stockpile is...",
 a:"The tonnage that can be drawn by the feeders without dozing (about 20,000 t for the new COS)",
 e:"Only the cone of material above the draw points flows freely (drawdown angle about 60°). Dead stock outside that needs a dozer or loader. Live capacity at design is about 11 hours of new circuit feed."},
{t:"crush", q:"What's the job of the wet scrubber / dust collector at the crusher?",
 a:"Capture dust generated by tipping and crushing",
 e:"Tipping 250 t loads makes a lot of dust. The scrubber and ventilation fans keep dust exposure and emissions in check."},
{t:"crush", q:"What does 'Primary Crushing 1' vs 'Primary Crushing 2' refer to on the PFDs?",
 a:"PC1 is the existing Fimiston crusher (F10); PC2 is the new crusher (F12)",
 e:"Both feed coarse ore stockpiles. PC1 feeds the Fimiston stockpile and SAG feed conveyor, PC2 feeds the new stockpile for the new SAG."},

// MILLING & CLASSIFICATION
{t:"mill", q:"The plant now has two SAG mills. How do they relate to the ball mill?",
 a:"Both the existing Fimiston SAG and the new SAG discharge to the new primary cyclone feed hopper, sharing the new ball mill and cyclones",
 e:"The Fimiston SAG (F19) discharge is pumped by the Fimiston mill transfer pumps to the primary cyclone feed hopper. Total mill feed is about 3,146 t/h nominal (≈1,313 t/h old SAG + ≈1,833 t/h new SAG)."},
{t:"mill", q:"What happens to SAG discharge screen oversize (pebbles)?",
 a:"It goes to the pebble (recycle) crushers and is returned to SAG feed",
 e:"Pebbles are the 'critical size' rocks (roughly 12 to 75 mm) too small to break other rocks but too big to be ground quickly. Crushing them to about 12 mm P80 frees up SAG capacity."},
{t:"mill", q:"What type of pebble crushers are used on the new circuit?",
 a:"Two cone crushers (XL7), duty/duty",
 e:"Two XL7 cone crushers, 375 kW each, CSS about 7 mm. Pebble load is about 17 to 28% of new feed depending on case."},
{t:"mill", q:"Why are tramp magnets and a metal detector important ahead of the pebble crushers?",
 a:"Worn grinding balls and steel in the pebbles can wreck a cone crusher running a 7 mm gap",
 e:"SAG pebbles include broken and worn balls. Steel in a cone crusher closed side causes huge force spikes. So pebbles pass magnets before the crushers, and there's a bypass route for pebbles when crushers are down."},
{t:"mill", q:"What drives the SAG pebble ports size and why does it matter?",
 a:"75 mm pebble ports in the discharge grate. As they wear bigger, pebble load increases",
 e:"The discharge grate acts like a screen. Worn, enlarged pebble ports let more pebbles out, which is why the pebble crusher design allows up to 610 t/h."},
{t:"mill", q:"Where do the cyclone underflow and overflow go?",
 a:"Underflow (coarse) → ball mill; overflow (fine) → trash screens → flotation",
 e:"Hydrocyclones separate by size and density. Coarse, heavy particles spin to the wall and exit the bottom (spigot) back to the ball mill. Fines exit the top (vortex finder) to flotation."},
{t:"mill", q:"What's the primary cyclone arrangement?",
 a:"One 800CVX cluster with 17 cyclones installed: 15 on primary duty and 2 on gravity duty",
 e:"About 12 primary cyclones run nominally (up to 14), with a standby. The 2 gravity cyclones are set up with larger spigots to push about 1,000 t/h each toward gravity."},
{t:"mill", q:"If cyclone feed density goes up too high, what's the likely effect on overflow grind?",
 a:"Coarser overflow (P80 goes up), because classification gets less sharp",
 e:"Denser feed means more hindered settling, so coarse particles get dragged to overflow. Design feed density is about 62% solids w/w. Operators control it with water addition at the cyclone feed hopper."},
{t:"mill", q:"What does 'roping' in a cyclone indicate?",
 a:"The underflow is overloaded and discharging as a solid rope instead of a spray, sending coarse material to overflow",
 e:"A healthy underflow discharges as an umbrella spray. Roping means the spigot is too small for the solids load. Coarse material then short circuits to flotation, which hurts recovery."},
{t:"mill", q:"Why are there trash screens between the cyclone overflow and flotation?",
 a:"To remove wood, plastic, rubber and grit that would block cells, UFG mills and carbon screens",
 e:"There are 4 linear trash screens (3 operating, 1 standby) with 1.0 mm apertures. Trash removed is about 27 t/day. Trash is a big nuisance downstream: it blinds intertank screens and floats with carbon."},
{t:"mill", q:"The ball mill is an 'overflow' type. What does that mean?",
 a:"Slurry discharges by overflowing through the trunnion at the discharge end (no grate)",
 e:"Overflow ball mills let slurry exit through the discharge trunnion like a weir. A trommel on the discharge catches scats. The ball mill is 8.53 m × 13.26 m EGL with a 20 MW motor."},
{t:"mill", q:"What's the SAG mill discharge density target?",
 a:"About 75% solids w/w",
 e:"Mills run thick (≈75% w/w) so the slurry coats the charge and transfers impact energy. Too dilute and balls hit liners; too thick and the mill can overload."},
{t:"mill", q:"SAG mill power rising and bearing pressure climbing, with throughput unchanged. Most likely?",
 a:"The mill load is building (overloading), often from harder or coarser feed",
 e:"Load and power track together up to a point. An overloading SAG needs feed reduced, speed or water adjusted. Past the peak, power can actually drop as the charge stops tumbling efficiently, which is why operators watch bearing pressure too."},
{t:"mill", q:"Why use Poly-Met liners in the ball mill and steel liners in the SAG?",
 a:"Steel handles SAG impact; rubber/steel composite Poly-Met gives lighter, longer life liners for the ball mill's lower impact duty",
 e:"SAG mills see big rock and ball impact so they need hard steel. Ball mills see finer grinding and more abrasion, where composite liners work well and weigh less."},
{t:"mill", q:"What happens to the gravity scalping screen oversize?",
 a:"It goes to ball mill feed",
 e:"The scalping screens (3.2 then 2.0 mm slots) protect the Knelsons from oversize. Oversize (about 10%) goes back to the ball mill, undersize goes to the Knelson concentrators."},

// GRAVITY & ILR
{t:"grav", q:"What type of gravity concentrator is used and how many?",
 a:"Two Knelson KC-QS70 centrifugal concentrators",
 e:"Each Knelson takes up to ~1,000 t/h of slurry. A fluidised bowl spins at high G. Heavy gold is trapped in the riffles while lighter material washes through."},
{t:"grav", q:"What is 'fluidising water' on a Knelson and why is it critical?",
 a:"Water injected through the bowl rings to keep the concentrate bed loose so heavy particles can penetrate and light ones wash out",
 e:"About 120 m³/h per unit. Too little and the bed compacts and loses gold. Too much and gold is washed out. Blocked fluidising holes are a common maintenance item."},
{t:"grav", q:"How does a Knelson produce concentrate?",
 a:"In batches: it runs a cycle (about 30 min), then stops feeding and flushes the concentrate out (about 150 kg per cycle)",
 e:"48 cycles a day produce about 14 t/day of concentrate. That concentrate is dewatered and sent to the ILR."},
{t:"grav", q:"Where do Knelson tails go?",
 a:"Back to the primary cyclone feed hopper",
 e:"Gravity is run on a circulating stream, so tails simply rejoin the grinding circuit. That's why it can catch gold repeatedly as it circulates."},
{t:"grav", q:"What does the ILR do with the Knelson concentrate?",
 a:"Leaches it in a batch with strong cyanide and oxygen, recovering about 98% of the gold into a pregnant solution",
 e:"The Acacia CS10000 runs 1 to 2 batches a day, about 12 h per cycle, making about 14.5 m³ of very rich pregnant solution (over 1,000 ppm Au)."},
{t:"grav", q:"Where does the ILR pregnant solution go?",
 a:"Gravity electrowinning cells in the goldroom (F66)",
 e:"Gravity EW uses clean in place cells, runs about 10 h per batch, and drives barren solution under 5 ppm Au."},
{t:"grav", q:"Why keep gravity gold separate rather than letting CIL collect it?",
 a:"Coarse gold leaches slowly and can escape to tails; gravity plus ILR gets it out fast and securely",
 e:"It also reduces gold inventory in the circuit and gives fast gold for production. Gravity recovery is about 14% of feed gold nominal."},

// FLOTATION
{t:"flot", q:"How are the rougher and scavenger cells arranged?",
 a:"3 rougher tank cells in series followed by 4 scavenger tank cells, all forced air",
 e:"F16-CF-411 to 413 are Rougher 1, 2 and 3. F16-CF-414 to 417 are Scavenger 1 to 4. Slurry flows by gravity cell to cell. Blowers supply low pressure air."},
{t:"flot", q:"What is the significance of the scavenger cells?",
 a:"They are the last chance to catch slower floating sulphides before they go to tails, where locked gold is largely lost",
 e:"Whatever the scavengers miss goes to CIL4, where only about a third of the remaining gold is recovered. So scavenger air, froth depth and reagent dosing directly decide how much refractory gold escapes."},
{t:"flot", q:"Where does Rougher 1 concentrate go?",
 a:"It can report straight to the final concentrate hopper because it's already high grade (about 15% S)",
 e:"The PFD shows a Rougher 1 collection box with a final concentrate sampler routed to the final concentrate hopper. Fast floating, high grade material doesn't need cleaning."},
{t:"flot", q:"Where do Rougher 2 & 3 concentrate and Scavenger concentrate go?",
 a:"To the cleaner circuit (Jameson cleaner cell)",
 e:"These concentrates are lower grade (about 7% S and 5% S) with more gangue, so they're upgraded in the cleaner."},
{t:"flot", q:"Where do cleaner tails go?",
 a:"To the cleaner-scavenger Jameson cell",
 e:"The cleaner rejects gangue, but its tails still carry some sulphide. The cleaner-scavenger gives it another pass. Cleaner-scavenger concentrate returns to the cleaner feed."},
{t:"flot", q:"Where do cleaner-scavenger tails go?",
 a:"To the flotation tailings thickener, joining the scavenger tails for CIL4",
 e:"Flotation tails thickener feed = scavenger tails + cleaner-scavenger tails."},
{t:"flot", q:"What type of cells are the cleaner and cleaner-scavenger?",
 a:"Glencore Jameson cells (B6500/24), naturally aspirated via downcomers",
 e:"In a Jameson cell, slurry is pumped as a plunging jet down downcomers, which sucks in air and makes very fine bubbles. High intensity, small footprint, great for cleaning."},
{t:"flot", q:"The Jameson cells have an 'external recycle'. Why?",
 a:"Part of the tails is recirculated to the feed hopper to keep downcomer flow (and jet pressure) constant regardless of new feed rate",
 e:"A Jameson needs a steady volumetric flow through its downcomers. About half of the tails are recycled so new feed variations don't upset the jet. It's like a pump minimum flow bypass."},
{t:"flot", q:"Name the flotation collector, activator and frother.",
 a:"Collector: PAX. Activator: copper sulphate. Frother: Luprofroth 168",
 e:"Collector makes sulphides hydrophobic, activator conditions the pyrite surface, frother stabilises bubbles and froth."},
{t:"flot", q:"Froth in the rougher looks flat, watery and collapsing. Likely cause?",
 a:"Too little frother or collector, or too much water; weak froth drops recovery",
 e:"A healthy froth is loaded with mineral and stable. Watery froth means poor mineral loading. Operators trim frother, collector, air rate and froth depth (level) in response."},
{t:"flot", q:"Raising the air rate on the scavengers generally...",
 a:"Increases mass pull and recovery but lowers concentrate grade",
 e:"More air lifts more material, including gangue. That's why scavenger concentrate goes to the cleaner rather than straight to final concentrate."},
{t:"flot", q:"What are the nominal rougher and scavenger residence times?",
 a:"About 15 min rougher and 21 min scavenger (≈37 min combined)",
 e:"Residence time = cell volume / slurry flow (adjusted for air hold up). Rougher total volume is 1,890 m³ (3 cells), scavenger 2,520 m³ (4 cells), so 630 m³ each."},
{t:"flot", q:"Nominal flotation gold recovery (of feed gold)?",
 a:"About 72% of gold (and about 85% of sulphur) to concentrate",
 e:"Flotation Au recovery is about 71.8% nominal (max 75%). The remaining gold goes to CIL4 with the tails."},
{t:"flot", q:"Where does final flotation concentrate go?",
 a:"Final concentrate hopper, then pumped to the concentrate thickener (existing 30-TH-61)",
 e:"30-TH-61 is the old Fimiston Flotation Tailings Thickener No. 3, repurposed as the concentrate thickener in Stage 1. From it, concentrate goes to filter feed tanks and on to the UFG mills."},
{t:"flot", q:"Why does flotation feed pass an onstream analyser and samplers?",
 a:"To measure head grade (Au/S proxies) so recovery and reagent dosing can be tracked in near real time",
 e:"Feed, concentrate and tail assays let metallurgists calculate recovery around the circuit every shift."},

// CONCENTRATE & UFG
{t:"conc", q:"How many UFG mills treat concentrate in Stage 2?",
 a:"Three IsaMills: UFG 1 (M3000, existing) plus UFG 2 and 3 (M15,000, new)",
 e:"UFG 2 came in Stage 1, UFG 3 in Stage 2. Normal Stage 2 running is UFG 2 and 3 only. When concentrate is high, UFG 2/3 run flat out and the excess goes to UFG 1. Each new mill takes about 30 t/h nominal (46 t/h max)."},
{t:"conc", q:"What is the UFG product size target?",
 a:"P80 ≈ 9 µm (range 9 to 12 µm)",
 e:"For scale, a human hair is about 70 µm. The whole ore is ground to 180 µm, but concentrate is ground 20 times finer to crack the pyrite."},
{t:"conc", q:"Roughly how much energy per tonne does UFG use vs the ball mill?",
 a:"About 116 kWh/t for UFG vs roughly 8 to 10 kWh/t for the ball mill",
 e:"Grinding energy rises steeply as size drops. It's only economic because concentrate is about 4% of the ore mass. Each new IsaMill draws about 3.5 MW."},
{t:"conc", q:"How does an IsaMill differ from a ball mill?",
 a:"It's a horizontal stirred mill: discs on a shaft spin small ceramic/sand media at high speed; the tumbling shell doesn't rotate",
 e:"Stirred mills transfer energy through attrition and shear, which is far more efficient at micron sizes than tumbling. Media is a few mm in size."},
{t:"conc", q:"Why are there static trash screens ahead of UFG 2 and 3?",
 a:"Any trash (wood fibre, plastic) would block the IsaMill's product separator and screens",
 e:"Inclined static wedge wire screens with 1.0 mm apertures. There was even a variation to add a trash screen on UFG Mill 2."},
{t:"conc", q:"What happens to concentrate in excess of UFG capacity?",
 a:"It goes through the existing vacuum belt filters to a concentrate stockpile",
 e:"Filter cake target is under 10% moisture, and stockpiled concentrate needs to be under its Transportable Moisture Limit if it's to be moved in bulk."},
{t:"conc", q:"After UFG, where does the ground concentrate go before leaching?",
 a:"The concentrate pre-leach thickener (existing 30-TH-31, repurposed)",
 e:"Thickening to about 52 to 58% solids gives more residence time in the leach and recovers water. Underflow feeds CIL2."},
{t:"conc", q:"In Stage 2, what are CIL2 and CIL3 used for?",
 a:"CIL2 is repurposed for leach duty; CIL3 is repurposed for adsorption duty",
 e:"It works like a leach-then-CIL train: gold dissolves in CIL2 (7 tanks), then carbon in CIL3 (6 tanks) adsorbs it."},
{t:"conc", q:"Why is the concentrate leach run at high pH (about 11.75 to 12.5) and with lead nitrate?",
 a:"High pH keeps cyanide as CN⁻ (not HCN gas); lead nitrate helps overcome sulphide passivation and speeds gold dissolution",
 e:"Fine sulphide concentrate is very reactive and consumes cyanide and oxygen. Lead nitrate is dosed at the leach feed box to counter that."},
{t:"conc", q:"The concentrate leach uses very high cyanide concentrations (thousands of ppm) compared to CIL4. Why?",
 a:"Concentrate is rich in gold and cyanide consuming sulphides, so it needs aggressive leaching to hit ~90% extraction",
 e:"Design leach extraction for concentrate was lifted to 90%. CIL3 tails, still carrying cyanide, flow on to CIL4 so that cyanide keeps working."},
{t:"conc", q:"Where do CIL3 tails go?",
 a:"To the CIL4 feed distribution box",
 e:"Sending CIL3 tails to CIL4 gives a second chance to recover any dissolved gold and reuses residual cyanide."},
{t:"conc", q:"Typical loaded carbon grade in CIL3 vs CIL4?",
 a:"About 4,500 g/t in CIL3 vs roughly 330 to 580 g/t in CIL4",
 e:"Concentrate solution is much richer, so carbon loads far higher. CIL3 carbon is stripped in the existing elution circuits (F65)."},
{t:"conc", q:"How is oxygen added in the CIL2 leach?",
 a:"Side lances on the tanks plus oxygen circulating/injection pumps on the first tanks",
 e:"Sulphide concentrate consumes oxygen fast. Oxygen injection pumps shear oxygen into the slurry for high DO."},

// TAILS LEACH (CIL4)
{t:"cil4", q:"What feeds the flotation tailings thickener?",
 a:"Scavenger tails and cleaner-scavenger tails",
 e:"About 3,000 t/h of solids at about 33% solids. The thickener lifts it to about 56% solids underflow."},
{t:"cil4", q:"Why thicken flotation tails before CIL4?",
 a:"Removing water shrinks the slurry volume so the same tanks give more leach residence time, and recovers water",
 e:"Going from ~33% to ~56% solids roughly halves the slurry volume. Thickener overflow is recycled as process water."},
{t:"cil4", q:"What is the CIL4 tank layout on the PFD?",
 a:"8 tanks in series: 2 leach tanks (TK-411/412) then 6 adsorption tanks (TK-413 to 418), with space for a future tank",
 e:"Each tank is about 5,600 m³ live. Total leach plus adsorption residence is about 12.8 h nominal, a bit under the 14 h ideal, which is why a future extra tank was allowed for."},
{t:"cil4", q:"How does carbon move in CIL4?",
 a:"Counter current: carbon is pumped upstream (toward the feed) while slurry flows downstream",
 e:"Barren (regenerated) carbon enters at the last tank where solution gold is lowest. It's advanced tank to tank upstream, loading more each step, and pulled out loaded from the first adsorption tank. Like a counterflow heat exchanger."},
{t:"cil4", q:"What do intertank screens do in CIL4?",
 a:"Hold carbon in each tank while letting slurry pass to the next tank",
 e:"Kemix mechanically swept pumped screens with 1.0 mm wedge wire. Carbon (≈1 to 3 mm) stays, slurry (P80 ~180 µm) passes. If they blind or overflow, carbon can migrate the wrong way."},
{t:"cil4", q:"What's the 'Carbon Scout'?",
 a:"An automatic sampler that measures carbon concentration in each CIL4 tank",
 e:"Gekko Carbon Scout samples all CIL4 tanks. Carbon concentration target is about 12.5 g/L. It tells operators when to advance carbon and whether carbon is distributed evenly."},
{t:"cil4", q:"CIL4 leach pH is about 8.8 to 9.3, much lower than CIL2. Why is that typical at KCGM?",
 a:"The hypersaline process water buffers pH; pushing it higher costs a lot of lime due to magnesium precipitation",
 e:"Process water SG is about 1.07 because it's saline bore water. Magnesium in the water consumes lime, so the bulk tails leach runs lower pH to control reagent cost, with safety controls for HCN."},
{t:"cil4", q:"CIL4 leach gold extraction is quite low (about 34 to 38%). Why is it still worth running?",
 a:"It treats ~96% of the mass; even a modest % of the gold in that huge tonnage is a lot of ounces",
 e:"Most of the tails gold is locked in unfloated sulphides, so leach extraction is limited. But at ~3,000 t/h, a few tenths of a g/t recovered is significant gold."},
{t:"cil4", q:"Where does loaded carbon from CIL4 go?",
 a:"Pumped from the first adsorption tank to the CIL4 loaded carbon screen, then the transfer vessel, then the CIL4 elution column (F22)",
 e:"The loaded carbon screen separates carbon from slurry. Slurry returns to the CIL4 tanks."},
{t:"cil4", q:"Where do CIL4 tails go?",
 a:"Final tails tank, then tailings disposal pumps to the TSF",
 e:"Acid wash waste and fine carbon waste also go to the final tails tank. Tails are sampled first (primary sampler) for metallurgical accounting."},
{t:"cil4", q:"What is the CIL4 static screen for?",
 a:"Screening event pond / silt trap slurry (spillage) before it's returned so trash doesn't enter CIL4",
 e:"A sieve bend with a 1 mm wedge wire. Spillage return is a common trash source."},
{t:"cil4", q:"What is a 'carbon safety screen'?",
 a:"A screen on leach tails to catch any carbon escaping the last tank before it's lost to the TSF",
 e:"Carbon lost to tails takes its loaded gold with it. CIL4's carbon safety screens are shown as future equipment in the PDC."},

// ELUTION, REGEN & GOLDROOM
{t:"elu", q:"What's the sequence of a typical AARL strip?",
 a:"Acid wash → water rinse → caustic cyanide pre-soak → hot water elution → cool down → carbon out to regeneration",
 e:"Acid removes carbonate scale that blocks carbon pores. The pre-soak loosens the gold. Hot water elution strips it into pregnant eluate."},
{t:"elu", q:"Why is the elution column kept under pressure?",
 a:"To stop the hot solution flashing (boiling) inside the column",
 e:"Elution runs well above 100 °C, so pressure keeps it liquid. Same principle as a pressurised cooling system."},
{t:"elu", q:"What acid is used for acid washing carbon?",
 a:"Hydrochloric acid (HCl, about 3% w/v)",
 e:"Dilute HCl dissolves calcium and magnesium carbonate scale. Acid waste goes to the final tails tank."},
{t:"elu", q:"The CIL4 elution uses a single column for two duties. Which?",
 a:"Acid wash and elution in the same column (duplex stainless SAF2205)",
 e:"The existing concentrate circuits have separate acid wash columns. CIL4 uses one combined column made of acid and chloride resistant duplex stainless steel."},
{t:"elu", q:"How is the CIL4 elution solution heated?",
 a:"LPG fired elution heater with heat exchangers",
 e:"The TPE LPG heater package heats the eluate. Hence LPG shows up in the reagent/utilities list."},
{t:"elu", q:"What happens to barren (stripped) carbon?",
 a:"It's regenerated in a kiln (thermal reactivation), quenched, sized on a screen and returned to CIL",
 e:"Heating in a low oxygen atmosphere burns off organics that foul carbon pores. The sizing screen removes fines, which would otherwise pass through intertank screens and carry gold to tails."},
{t:"elu", q:"Why does the carbon regeneration kiln off gas need treatment?",
 a:"Mercury and organics driven off the carbon must be captured before release",
 e:"Goldfields ores carry mercury, which loads on carbon and comes off in the kiln. A mercury abatement system and a regenerative thermal oxidiser treat the off gas."},
{t:"elu", q:"What happens in the goldroom?",
 a:"Gold is electrowon onto cathodes, the sludge is dried, fluxed and smelted into doré bars",
 e:"F66 covers CIL4A/4B electrowinning and gravity electrowinning. High security area."},
{t:"elu", q:"What is 'lean eluate'?",
 a:"Partly depleted eluate saved from a strip and reused for the pre-soak/first stage of the next strip",
 e:"In split AARL, reusing lean eluate saves reagents and water. The first bed volumes of fresh water become the next strip's lean eluate."},

// WATER, AIR & REAGENTS
{t:"util", q:"Process water at KCGM has an SG of about 1.07. Why?",
 a:"It's hypersaline bore water (very high dissolved salts)",
 e:"Fresh water is scarce in the Goldfields, so the plant runs on saline bore water from borefields like Kaltails. That's why corrosion resistant materials and specific reagent behaviour matter."},
{t:"util", q:"What is 'scheme water' used for?",
 a:"Fresh (potable quality) water for gland seals, elution, reagent make up, safety showers and other duties that can't tolerate salt",
 e:"Scheme water comes from the Goldfields pipeline and is expensive, so it's reserved for jobs that need clean water. Its SG is 1.00."},
{t:"util", q:"What is 'cyanide water'?",
 a:"Decant water returned from the TSF, still carrying some cyanide, reused in the plant",
 e:"Reusing it saves water and cyanide. It's treated with hydrogen peroxide (inline mixers on the decant lines) to a residual WAD cyanide target."},
{t:"util", q:"What is 'gland water'?",
 a:"Clean water injected into slurry pump shaft seals to keep grit out and cool the packing",
 e:"A mechanical engineer's favourite. Loss of gland water means packing runs dry, overheats and slurry gets into the seal. The new UFG mills also use scheme water for gland seals."},
{t:"util", q:"What's the difference between 'HP process water' and 'mill water'?",
 a:"HP process water is pumped at high pressure for sprays and hose points; mill (circuit) water is lower pressure dilution water for mills and cyclone hoppers",
 e:"The PFDs show both distributions. Screen sprays, launder sprays and trash screens use HP process water."},
{t:"util", q:"What supplies air to the rougher and scavenger cells?",
 a:"Low pressure flotation blowers",
 e:"FLS forced air tank cells take blower air. Jameson cells don't need blowers because the plunging jet entrains air."},
{t:"util", q:"Why is instrument air kept separate from plant air?",
 a:"Instruments and valve actuators need clean, dry, oil free air at stable pressure",
 e:"Wet or dirty air fouls positioners and solenoids. Instrument air is dried and filtered with a receiver for backup."},
{t:"util", q:"What's lime used for, and how is it delivered?",
 a:"pH control in leach (to prevent HCN gas); quicklime is slaked to milk of lime and pumped round a ringmain",
 e:"The Stage 2 lime system includes a slaking package. Dosing points are leach feed boxes."},
{t:"util", q:"Why is flocculant added to thickeners?",
 a:"It binds fine particles into larger flocs that settle faster, giving a clear overflow and dense underflow",
 e:"Flocculant is a long chain polymer, mixed dilute and dosed at the thickener feed well. Overdose makes underflow sticky and hard to pump."},
{t:"util", q:"What is hydrogen peroxide used for?",
 a:"Destroying (oxidising) cyanide in decant/cyanide water",
 e:"Dosing is controlled from an online WAD cyanide analyser."},
{t:"util", q:"What is caustic (NaOH) mainly used for?",
 a:"Elution pre-soak solution and pH control in elution/EW",
 e:"The pre-soak is a caustic cyanide solution. Caustic also keeps electrowinning solution alkaline."},
{t:"util", q:"Why is oxygen a key 'reagent' at KCGM?",
 a:"Gold cyanidation needs dissolved oxygen, and sulphide rich slurries consume it quickly",
 e:"Oxygen is supplied from a PSA plant with liquid oxygen backup, fed to leach tanks, ILR and CIL4."},

// KEY NUMBERS
{t:"nums", q:"Nominal Stage 2 plant throughput?",
 a:"About 25.5 Mtpa (with a 28.35 Mtpa high throughput case at P80 220 µm)",
 e:"That's about 3,146 t/h through the mills at 93.4% availability. For comparison the old Fimiston circuit alone was about 10.5 Mtpa."},
{t:"nums", q:"Nominal head grade the design is based on?",
 a:"About 1.6 g/t Au and about 1% S",
 e:"Nominal 1.58 g/t Au and 1.02% S. The design grade case is 1.81 g/t Au and 1.49% S."},
{t:"nums", q:"Nominal overall gold recovery?",
 a:"About 84%",
 e:"Built from gravity (~14%), flotation concentrate leach (high) and tails leach (low). Stage 2 aims for a 1 to 2% uplift."},
{t:"nums", q:"Approximate annual gold production in the nominal Stage 2 design case?",
 a:"About 1.2 million ounces",
 e:"The PDC calculates roughly 1.19 Moz/a for the 25.5 Mtpa nominal case."},
{t:"nums", q:"How much flotation concentrate is produced per year (nominal)?",
 a:"About 876,000 t/a (roughly 100 t/h)",
 e:"That's the feed that UFG 1, 2 and 3 plus the filters must handle."},
{t:"nums", q:"Concentrator availability vs crushing availability used in design?",
 a:"93.4% concentrator vs 65% crushing",
 e:"That difference is why the stockpile exists and why the crusher is sized for a much higher instantaneous rate."},
{t:"nums", q:"The new SAG mill motor is rated...",
 a:"20 MW",
 e:"Same as the ball mill (20 MW). The old Fimiston SAG was 12 MW. Each new UFG mill is 3.8 MW installed."},
{t:"nums", q:"Gravity cyclone underflow aims to send how much to each Knelson?",
 a:"About 900 to 1,000 t/h",
 e:"Vendor recommended about 90% of the 1,000 t/h max, so about 900 t/h per unit, 1,800 t/h total to gravity."},
{t:"nums", q:"CIL4 carbon concentration target per tank?",
 a:"About 12.5 g/L",
 e:"The carbon scout measures it. CIL3 runs higher (about 20 g/L) because its solution is richer."},
{t:"nums", q:"Tailings disposal pumps arrangement?",
 a:"Duty / duty / duty / standby",
 e:"Three running with one standby gives redundancy on a critical line. If tails can't be pumped, the whole plant stops."},

// SHIFT HANDOVER SCENARIOS
{t:"hand", q:"Handover: 'Pebble crushers both down, pebbles on bypass.' What should you expect on the SAG?",
 a:"Pebbles recirculate uncrushed so SAG load builds and throughput usually has to be cut",
 e:"Critical size material builds up in the SAG. Operators typically back off feed, watch power and bearing pressure, and may adjust speed."},
{t:"hand", q:"Handover: 'Cyclone overflow P80 running coarse, around 230 µm.' Downstream concern?",
 a:"Poorer liberation, so flotation recovery drops and coarse sulphides can sand up in the cells",
 e:"Grind is a trade off with throughput. Coarser grind = more tonnes but more gold locked in unliberated particles going to tails."},
{t:"hand", q:"Handover: 'Scavenger tails sulphur is creeping up on the OSA.' What does it mean?",
 a:"More sulphide (and locked gold) is escaping flotation to CIL4, so recovery is dropping",
 e:"Check air rates, froth levels, reagent dosing (PAX, CuSO₄, frother), feed grind and feed rate. This is the scavenger significance in action."},
{t:"hand", q:"Handover: 'Trash screen 2 is blinding, running 3 wide with no standby.' Why does it matter?",
 a:"With no standby, any further loss sends trash or overflow to flotation and downstream screens/UFG",
 e:"4 screens installed, 3 needed. Blinding means reduced open area, overflow and possible bypass of trash. Wash down or change panels quickly."},
{t:"hand", q:"Handover: 'Flotation tails thickener underflow density dropped to 48%.' Effect on CIL4?",
 a:"More water goes to CIL4, cutting leach residence time and diluting reagents",
 e:"Target is about 56%. Causes: flocculant issues, overloading or rake problems. Watch rake torque and bed level too."},
{t:"hand", q:"Handover: 'Thickener rake torque high and climbing.' Main risk?",
 a:"The rake can bog and trip; a bogged thickener is a major outage",
 e:"Operators respond by increasing underflow pumping, raising rakes, reducing feed or flocculant. A classic mechanical risk area."},
{t:"hand", q:"Handover: 'Carbon Scout shows Tank 6 low on carbon and Tank 7 high.' Likely issue?",
 a:"Carbon distribution problem: intertank screen or carbon advance pump not moving carbon as intended",
 e:"Carbon moves counter current by recessed impeller pumps. Uneven inventory reduces adsorption efficiency and can lead to soluble gold loss."},
{t:"hand", q:"Handover: 'DO low in CIL2 leach tanks.' What might be the cause and consequence?",
 a:"Oxygen supply or injection pump issue; slower gold dissolution and more cyanide consumption",
 e:"Check the PSA plant, liquid oxygen, lances and injection pumps. Sulphide concentrate is a big oxygen consumer."},
{t:"hand", q:"Handover: 'High WAD on decant return.' What system should respond?",
 a:"Hydrogen peroxide cyanide destruct dosing on the decant water lines",
 e:"An environmental and safety item. The online CNWAD analyser controls peroxide dosing."},
{t:"hand", q:"Handover: 'Knelson 1 fluidising water flow low alarm.' Action and consequence?",
 a:"Investigate blocked rings/supply; low fluidisation compacts the bed and loses gold recovery",
 e:"Fluidising water is about 120 m³/h per unit. Low flow usually means blockages or supply issues."},
{t:"hand", q:"Handover: 'UFG 2 offline for media top up, excess con going to filters.' What does that tell you?",
 a:"UFG capacity is short, so concentrate is being pushed to UFG 1 and then filtered and stockpiled rather than leached right now",
 e:"The filters and stockpile act as the relief path for concentrate above UFG capacity."},
{t:"hand", q:"Handover: 'Elution on strip 2 of 3 for CIL4, kiln running.' What does 'strip' mean?",
 a:"One complete elution batch of loaded carbon",
 e:"The CIL4 column does acid wash and elution in one vessel. Each strip then sends carbon to the regeneration kiln."},
{t:"hand", q:"Handover: 'SAG discharge screen panels worn, pebbles reporting to cyclone hopper.' Risk?",
 a:"Oversize can overload the cyclone feed pump and send coarse material to the ball mill and cyclones",
 e:"The discharge screen (12 × 55 mm slots) keeps pebbles out of the slurry side. Worn panels let oversize through."},
{t:"hand", q:"Handover: 'Jameson cleaner recycle valve stuck open.' Why care?",
 a:"It changes the downcomer flow/pressure balance, affecting bubble generation and cleaner performance",
 e:"The Jameson depends on a steady jet flow through the downcomers. The external recycle keeps that constant."},
{t:"hand", q:"Handover: 'Concentrate thickener overflow is dirty.' Main loss?",
 a:"Fine sulphide concentrate (with gold) is reporting to the overflow water",
 e:"Check flocculant dosing and thickener loading. Dirty overflow also contaminates process water."},
{t:"hand", q:"Handover: 'Final tails sampler down.' Why do metallurgists care?",
 a:"Final tails assays are needed for metallurgical accounting and recovery calculation",
 e:"Without tails samples, recovery for the shift can't be confirmed."},
{t:"hand", q:"Handover: 'Fimiston SAG transfer pump tripped.' Which circuit is affected immediately?",
 a:"The old Fimiston SAG (F19) can't send discharge to the new cyclone feed hopper, so it must stop or reduce feed",
 e:"Since both SAGs share the new cyclone cluster and ball mill, the transfer line is critical to running the old SAG."},

// CONTROLS & DCS  (from the Stage 1 and Stage 2 Plant General Process Control Philosophies)
{t:"ctrl", q:"What control system runs the Fimiston plant?",
 a:"A Yokogawa Centum VP DCS, with Field Control Stations spread around the plant",
 e:"New and old plant are configured to the same KCGM templates so it looks and operates as one plant. Data is logged to a PI historian, which is where trends come from."},
{t:"ctrl", q:"What are the two main control rooms?",
 a:"The Fimiston Crusher control room and the Main Mill control building",
 e:"The new primary crusher (PC2) is run remotely from the existing crusher control room using CCTV. Acronyms: CRO = Control Room Operator, OIS = Operator Interface System (the screens), CCR = Central Control Room, CrCR = Crusher Control Room."},
{t:"ctrl", q:"A drive has three modes. Name them.",
 a:"Automatic, Manual and Local",
 e:"Mode is selected from the OIS only. The field LCS has start and latch off stop buttons but no mode selector switch."},
{t:"ctrl", q:"In Automatic mode, can you start the drive from its field LCS?",
 a:"No. Field start is blocked, but field stop always works",
 e:"In Auto the DCS starts and stops it from a sequence or process condition, e.g. a sump pump starting on its high level switch."},
{t:"ctrl", q:"What does Manual mode mean for a drive?",
 a:"The CRO starts and stops it from the OIS (or LCS start/stop), but it won't auto start or stop with sequences or process conditions",
 e:"All process interlocks, critical interlocks and permissives still apply. Some pumps with manual isolation valves are field start only, so you open the valve before starting and don't run against a closed valve."},
{t:"ctrl", q:"What does Local mode bypass, and what does it never bypass?",
 a:"It bypasses process interlocks and start permissives. Critical (safety) interlocks, hardwired devices and protection relays always stay active",
 e:"Local is for fault finding and maintenance only, started from the LCS, and must be supervised. A configurable timer drops the drive out of Local back to its target mode."},
{t:"ctrl", q:"Does switching a running drive between Auto, Manual and Local stop it?",
 a:"No. Mode changes are bumpless; only a new command or an interlock changes the drive state",
 e:"Useful to know before you ask the CRO to put something in Local for testing."},
{t:"ctrl", q:"Name the three interlock types in the DCS.",
 a:"Critical (safety) interlocks, process interlocks and start permissives",
 e:"Critical: E-stops, pull wires, protection relays, trip in every mode and can't be bypassed. Process: stop the drive to prevent spills or poor performance, trip in Auto and Manual, bypassable by named users one at a time. Start permissive: stops it starting, but won't stop it once running."},
{t:"ctrl", q:"Difference between a start permissive and a process interlock?",
 a:"A permissive only prevents a start; a process interlock will trip a running drive",
 e:"Example permissive: gland water low flow stops a slurry pump starting. Once running, low gland flow must persist for a set time before it trips."},
{t:"ctrl", q:"Why do DCS interlocks have an adjustable time delay?",
 a:"So a momentary instrument spike doesn't trip the plant; the condition must be true continuously for XX seconds",
 e:"Delays are set during commissioning. Hardwired critical trips like E-stops act immediately."},
{t:"ctrl", q:"What is 'first out' on a trip?",
 a:"The DCS records which condition tripped the drive first, so you can find the root cause",
 e:"When one trip cascades into many alarms, first out tells you where it started."},
{t:"ctrl", q:"What are the three loop controller modes?",
 a:"Manual (operator sets the output), Automatic (PID drives PV to an operator setpoint) and Cascade (setpoint comes from a master controller)",
 e:"PV = process variable (what you measure), SV = setpoint value, CV = controlled variable (the output to the valve or VSD)."},
{t:"ctrl", q:"What's a cascade loop, in mechanical terms?",
 a:"A master loop sets the setpoint of a faster slave loop, e.g. thickener bed pressure sets the underflow flow setpoint, and the flow loop drives the pump VSD",
 e:"The inner loop handles fast disturbances such as pump wear or head change. The outer loop handles the slow process target."},
{t:"ctrl", q:"How is level normally controlled in a slurry pump hopper?",
 a:"The level controller trims the pump VSD speed. With a flowmeter it can cascade level to a flow controller that sets pump speed",
 e:"Hopper level alarms warn the CRO when it drifts outside range."},
{t:"ctrl", q:"Some hoppers have 'dual level controllers'. How do they work?",
 a:"Loop A controls pump speed at a higher level setpoint. Loop B adds water at a lower setpoint when inflow drops below the pump's minimum flow",
 e:"It keeps line velocity above the settling velocity so slurry lines don't sand up. Setpoint A must be above setpoint B or the loops fight each other."},
{t:"ctrl", q:"Why do slurry pump dump valves fail open on power loss?",
 a:"To drain the line so slurry doesn't settle and bog the pump and pipe",
 e:"Duty/standby pump sets have actuated suction, discharge and dump valves with proximity switches, interlocked so a pump can't run against a closed valve (except briefly on start or changeover)."},
{t:"ctrl", q:"What makes up a pump's gland water arrangement?",
 a:"Manual isolation valves, an actuated on/off valve, a Maric constant flow valve and a flow switch or flowmeter",
 e:"The actuated valve opens as part of the pump start sequence. The Maric valve gives a set flow regardless of supply pressure. The big pumps (cyclone feed, tails thickener underflow, final tails) get mag flowmeters instead of switches."},
{t:"ctrl", q:"How does a sump pump run in Auto?",
 a:"It starts on high level and runs until the high level clears plus a run on time, or until low level, then stops",
 e:"If the high level doesn't clear within a set time, the DCS alarms. Reagent area sumps follow different rules because of what's in them."},
{t:"ctrl", q:"Why must the CRO call before starting the mills?",
 a:"There's no DCS link to the Parkeston Power Station, so large loads need the power supplier's approval first",
 e:"Sequences pause and ask for operator confirmation before starting big loads like the 20 MW mill motors."},
{t:"ctrl", q:"What happens in the field before crushers, feeders, conveyors and mills start?",
 a:"A start siren and flashing red light warn people nearby",
 e:"Cyanide areas also have HCN gas monitors with beacons and sirens."},
{t:"ctrl", q:"How does a DCS start sequence handle a drive in Local or faulted?",
 a:"It won't start. All drives, valves and PIDs in the sequence must be in Auto or Manual (Manual ones get switched to Auto)",
 e:"Each step must confirm (e.g. run feedback) within a set transition time, or the sequence pauses and alerts the operator."},
{t:"ctrl", q:"What does an actuated valve 'watchdog' do?",
 a:"If the limit switch doesn't confirm open or closed within a set time, it faults 'fail to open/close' and holds the sequence",
 e:"It also flags both limit switches on (or both off) together, which means a switch or valve fault."},
{t:"ctrl", q:"Name the protection devices on a plant conveyor.",
 a:"Start siren, LCS E-stop, pull wires, belt drift switches, belt speed (under-speed) sensor, belt rip detector and blocked chute switch",
 e:"Pull wires and rip detectors must be reset in the field. A conveyor trip also stops any upstream interlocked equipment so material doesn't pile up."},
{t:"ctrl", q:"Belt drift switches come in inner and outer pairs. What does each do?",
 a:"Inner switch: alarm only (after a delay). Outer switch: trips the conveyor",
 e:"It gives the operator a chance to fix tracking before the belt runs off and damages the structure."},
{t:"ctrl", q:"What does the under-speed sensor catch?",
 a:"The belt slowing below set speed, stopping unexpectedly, or not reaching full speed in time after a start",
 e:"Typical causes: slipping drive pulley, overloaded belt, or a failed coupling or gearbox."},
{t:"ctrl", q:"What type of blocked chute sensor is preferred?",
 a:"Microwave blocked chute sensors, with a time delay to avoid false trips",
 e:"A blocked chute trips the feeding conveyor and stops upstream equipment."},
{t:"ctrl", q:"How do the primary cyclones get opened and closed in Auto?",
 a:"Air actuated knife gates open one extra cyclone if feed pressure stays high, and close one if pressure stays low",
 e:"In cascade, the cyclone feed hopper level controller adjusts the pressure setpoint. Gravity cyclones run on their own sequences, interlocked to their gravity screens."},
{t:"ctrl", q:"Why must a minimum number of cyclones be open before the cyclone feed pump starts?",
 a:"To prevent overpressuring the cyclone cluster (deadheading the pump)",
 e:"Same principle as a minimum flow path on any centrifugal pump."},
{t:"ctrl", q:"What sets the SAG feed rate?",
 a:"Reclaim feeder speeds, controlled to a tonnage setpoint (or mill weight) through the SAG feed weightometer, normally set by the mill expert system",
 e:"A deadband allows for the lag between feeder speed change and the weightometer seeing it. Feeders can be run as a ratio or one fixed and one trimming."},
{t:"ctrl", q:"What does the milling expert system use as inputs?",
 a:"SAG feed camera size analyser, SAG noise monitor, mill load, speed and power, and other measured variables",
 e:"It controls feed rate, water addition, mill weight, cyclone feed flow and pressure, solids concentration, SAG speed and grind size."},
{t:"ctrl", q:"How are grinding balls added?",
 a:"Automatically, to a kg/t setpoint or to hold a preset mill weight",
 e:"The ball mill normally runs at a fixed speed of about 75% of critical. The SAG speed range is 60 to 83%."},
{t:"ctrl", q:"Why does the cyclone feed hopper have 'Fast' and 'Slow' tuning?",
 a:"Slow (detuned) keeps flotation feed flow smooth in normal running. Fast protects equipment in upsets by quickly restoring minimum hopper level",
 e:"A classic trade-off between stability downstream and protection upstream."},
{t:"ctrl", q:"What makes the pebble bin bypass gate open?",
 a:"Metal detected in the pebble crusher feed, bin level High with both feeders stopped, or bin level High-High",
 e:"Crusher feeders start on high bin level and stop on low level. Pebbles on bypass go straight back to the SAG."},
{t:"ctrl", q:"How does the grinding circuit run during mill relines?",
 a:"New SAG alone (single stage) while the ball mill is relined, new SABC while the Fimiston SAG is relined, and Fimiston SAG plus ball mill while the new SAG is relined",
 e:"All at reduced throughput. Good context when someone says 'we're single stage this week'."},
{t:"ctrl", q:"Why do flotation cell agitators normally keep running even when the plant is down?",
 a:"If the cell holds slurry or water, stopping would let solids settle and sand in the rotor",
 e:"Agitators are started from the OIS after the field operator has checked them visually."},
{t:"ctrl", q:"Why are flotation cell drives reversible?",
 a:"To even out rotor wear by running in both directions",
 e:"The direction is picked on the OIS based on how long it has run each way."},
{t:"ctrl", q:"What happens to a flotation cell's air valve when its agitator trips?",
 a:"It interlocks closed, to avoid sanding the rotor/stator gap and damaging the motor bearings",
 e:"The vendor recommends having the air controller in Auto at a low setpoint before starting the agitator."},
{t:"ctrl", q:"How is rougher and scavenger cell level held?",
 a:"Two discharge dart valves per cell on a split range level controller, in series or in parallel",
 e:"Level sets froth depth. The flotation expert system uses froth cameras, launder velocity cameras and OSA data to adjust level, air and reagents."},
{t:"ctrl", q:"How is air controlled in the Jameson cells?",
 a:"By the total slurry flow (new feed plus recycle) through the downcomers, with the feed pump VSD held at a set flow",
 e:"No agitators and no blowers. The jet does the work."},
{t:"ctrl", q:"The OSA measures gold and iron. How does it get sulphur?",
 a:"Sulphur is inferred from iron, because the sulphide is mainly pyrite (FeS₂)",
 e:"Nine flotation streams are sampled, from feed to final tails. Samples return in separate high grade and low grade hoppers."},
{t:"ctrl", q:"How are reagent doses set?",
 a:"As g/t in a calculation block (turned into a flow setpoint) or as a direct flow setpoint; a flow controller trims the dosing pump VSD",
 e:"Unloading from tankers is always a manual, field started job. Antiscalant is the exception: IBCs with manually set metering pumps."},
{t:"ctrl", q:"How are cyanide and caustic distributed?",
 a:"By pressurised ringmains with DOL pumps and a mechanical back pressure valve on the return line",
 e:"Pressure on the pump discharge and the return line alerts the operator to loss of flow. Flowmeters sit at each dosing point."},
{t:"ctrl", q:"Why does the caustic tank have an immersion heater?",
 a:"Concentrated caustic can freeze (crystallise) in cold weather. The heater starts below about 20 °C and stops above about 25 °C",
 e:"Setpoints are confirmed at commissioning."},
{t:"ctrl", q:"What does the flotation tails thickener vendor panel show?",
 a:"Rake torque, bed level, rake height and bed mass (bed pressure), plus overflow clarity",
 e:"Rakes and rake lift are run from the field panel in local mode. Bed level is measured by a SmartDiver or Manta sub."},
{t:"ctrl", q:"How is thickener underflow pumping controlled?",
 a:"Cascade: a bed pressure or underflow density controller sets a flow controller, which drives the underflow pump VSD",
 e:"During start up, shutdown or low flow the underflow can recycle back to the feed to keep bed mass without bogging the rakes."},
{t:"ctrl", q:"How is flocculant dosing controlled on the flotation tails thickener?",
 a:"Stage 1: cascaded from bed level. Stage 2: to a floc to feed solids ratio setpoint",
 e:"Flocculant is diluted again in an inline mixer just before the thickener."},
{t:"ctrl", q:"UFG feed hopper water addition does two jobs. What are they?",
 a:"Holds feed solids concentration for good grinding, and adds water to cool the mill if discharge temperature exceeds 60 °C",
 e:"IsaMills put a lot of energy into a small volume, so slurry heats up. The feed pump runs on flow control."},
{t:"ctrl", q:"How is IsaMill media added?",
 a:"A positioning knife gate valve meters media in to hold a mill power draw setpoint",
 e:"Less media means lower power. The mill also has shell vibration monitoring and hardwired motor interlocks, and liquid resistance starters on a vendor PLC."},
{t:"ctrl", q:"How is CIL4 pH controlled?",
 a:"A pH controller on leach tank 1 opens the milk of lime valve at the CIL4 feed distribution box (tank 2's controller takes over if tank 1 is down)",
 e:"Both pH loops alarm on abnormal high or low."},
{t:"ctrl", q:"How is CIL4 cyanide added?",
 a:"Flow control at the front end, set by the operator or by a g/t ratio on thickener underflow tonnes, with the cyanide analyser able to trim it. Leach tanks and adsorption tank 3 have extra addition lines",
 e:"An HCN gas monitor in the area triggers a beacon and siren at high-high."},
{t:"ctrl", q:"How is oxygen added in CIL4?",
 a:"VSD oxygen injection pumps with flow control valves on the leach tanks, plus side lances on the leach tanks and the first two adsorption tanks",
 e:"DO analysers alarm high or low. Lance pressures are checked on local gauges against vendor pressure-flow curves."},
{t:"ctrl", q:"What's a 'carbon detection meter' on the CIL4 tails?",
 a:"It detects carbon escaping to tails and alarms; a second meter at the carbon-free front end is the reference probe",
 e:"Lost carbon carries loaded gold to the TSF. CIL3 tails have the same setup."},
{t:"ctrl", q:"How are CIL4 tails sampled for accounting?",
 a:"A three stage sampling station takes a shift composite before the final tails tank",
 e:"The lab assays it, which gives the tails grade for the recovery calculation."},
{t:"ctrl", q:"How are slurry bypass gates between CIL4 tanks operated?",
 a:"Pneumatic isolation gates operated locally by the plant operator; DCS control is inhibited",
 e:"Loaded carbon routing between tanks is changed with removable spool pieces in the central pipe rack."},
{t:"ctrl", q:"What runs the CIL4 elution?",
 a:"A timed sequence using level, temperature and pressure to step through carbon in, acid wash, rinse, pre-soak, lean eluate elution, scheme water elution and cooling",
 e:"A temperature controller on the eluate line talks to the vendor LPG burner management system. Pregnant eluate fills the circulation tank, then overflow goes to the lean eluate tank."},
{t:"ctrl", q:"Who controls the CIL4 carbon regeneration kiln?",
 a:"A vendor PLC (screw feeder, kiln and local panel), tied to the DCS through an overall regeneration sequence",
 e:"The mercury abatement system must run whenever the kiln runs, so its drives are in the same sequence."},
{t:"ctrl", q:"How do weightometers totalise tonnes?",
 a:"Wet tonnes per 12 hour shift from 5:00 am, per day from 5:00 am, and a running total. A moisture input converts wet to dry",
 e:"Permanent calibration chains are fitted on the new conveyors."},
{t:"ctrl", q:"How is slurry mass flow measured?",
 a:"Magnetic flowmeter plus nucleonic density gauge, with an operator entered dry solids SG in a DCS calculation",
 e:"A wrong SG entry gives wrong tonnes. Worth knowing when tonnages look odd."},
{t:"ctrl", q:"What's the difference between emergency and essential backup power?",
 a:"Emergency power: a generator that starts automatically on outage. Essential power: an operator manually starts a generator",
 e:"The DCS and field RIO panels ride through on UPS, and emergency lighting lasts at least 90 minutes."},
{t:"ctrl", q:"What do switchroom sprinklers interlock with?",
 a:"Lube and hydraulic pumps (timed on mills to allow a safe stop) and conveyor drives with external lube/hydraulic systems",
 e:"Each switchroom has a hardwired fire alarm on the DCS with siren, beacon and suppression."},
{t:"ctrl", q:"How do LV motors talk to the DCS?",
 a:"DOL starters have electronic overloads (EOL) on Modbus TCP; VSDs have a field network link",
 e:"Field start, latched stop healthy, pull wire and float switch status are hardwired to the EOL or VSD I/O. VSD E-stops are wired to Safe Torque Off."},
{t:"ctrl", q:"What are the four DCS alarm priorities?",
 a:"Logging, Low, High and Urgent",
 e:"Analogue alarms have LL, L, H and HH levels. Alarm management follows ISA-18.2, and alarms are masked when their equipment isn't running."},
{t:"ctrl", q:"How do the primary crusher 'traffic lights' work?",
 a:"Red/green lights tell truck drivers when they can tip. They're set by the crusher control room and automatically from truck radar, ROM bin and discharge chamber levels, crusher running and rock breaker position",
 e:"The rock breaker is run remotely by camera and parks itself when not in use."},
{t:"ctrl", q:"How is the new primary crusher gap adjusted?",
 a:"Automatically, from a camera based particle size analyser on the stockpile feed conveyor",
 e:"The discharge apron feeder is controlled to a tonnage setpoint on the stockpile feed weightometer."},
{t:"ctrl", q:"What stops the stockpile feed conveyor overfilling the COS?",
 a:"It's interlocked to the stockpile high-high level switch and the high-high alarm on the stockpile level indicator",
 e:"CCTV also watches the stockpile drawdown."},
{t:"ctrl", q:"Where does raw water for gland seals come from?",
 a:"The lower part of the new Raw Water Tank feeds the LP and HP gland water pumps; the tank is fed from Bore Water/Saline Dam 3",
 e:"The Process Water Tank is mainly fed by flotation tails thickener overflow, with top up from Bore Water Dam 2 (South Dam)."},
{t:"ctrl", q:"How do the flotation air blowers hold pressure?",
 a:"VSDs on the blowers hold a constant air header pressure",
 e:"Each cell then has its own air flow controller (mass flow meter plus control valve)."},
{t:"ctrl", q:"What's a 'vendor package' and how does it link to the DCS?",
 a:"Equipment supplied with its own controls (e.g. OSA, IsaMill starters, rock breaker, regen kiln). If it has a PLC, it reports to the DCS for Monitor or Control",
 e:"Standalone PLCs need NSR approval. Most big items (SAG, ball mill, flotation cells, thickener, Knelsons, ILR, Jamesons) are controlled directly by the DCS."},
];
