// Plant reference sheet sent to the AI with every follow up question, so answers are grounded in KCGM documents.
// Condensed from: Stage 2 Process Design Criteria 2000-F00-DCR-PR-10002 Rev 4 (design values, not live operating data),
// Plant General Process Control Philosophy Stage 1 (2000-F00-REP-PR-10001 Rev 4) and Stage 2 (2000-F00-REP-PR-10002 Rev 0),
// Stage 1 as built PFDs, Plant Numbering Spec 2000-F00-STS-GE-10003 and the Growth Project WBS.
const PLANT_FACTS = `
SITE AND PROJECT
KCGM = Kalgoorlie Consolidated Gold Mines, owned by Northern Star Resources (NSR). Fimiston processing plant, Kalgoorlie WA. Growth Project EPC contractor Primero (project 23517). Ore is refractory: much gold is locked in sulphides (mainly pyrite) and tellurides.
Flowsheet: crushing, SABC grinding, gravity recovery on cyclone underflow with intensive cyanidation and gravity electrowinning, rougher/scavenger then Jameson cleaner/cleaner-scavenger flotation, ultra fine grinding (UFG) of concentrate, separate cyanide leaching of concentrate (CIL2 leach, CIL3 adsorption) and flotation tails (CIL4), split AARL elution and electrowinning, carbon regeneration kilns, goldroom.
Plant sections for DCS ownership: Greenfields Stage 1, Greenfields Stage 2, Brownfield (modifications to existing Fimiston plant), Existing plant.
Stage 1 scope: new primary crusher (PC2) and stockpile feed conveyor in parallel with existing gyratory; new coarse ore stockpile, reclaim, SAG mill and pebble crushing in parallel with existing Fimiston SAG and its pebble crushers; Mt Charlotte processing plant, Fimiston ball mills and old Fimiston flotation made redundant; new ball mill fed by both SAG mills; new gravity and intensive leach circuit; new gravity EW; new rougher/scavenger flotation; new cleaner and cleaner-scavenger flotation; new UFG circuit with one IsaMill (UFG 2); new flotation tailings thickener; new final tails tank and four tailings disposal pumps. In Stage 1 a portion of flotation tails thickener underflow went to existing CIL2 and CIL3 (flow controlled to their capacity) with the balance to final tails. Existing Fimiston Flotation Tailings Thickener No.3 was reused as the concentrate thickener. Part of the concentrate went through existing and new UFG mills to existing concentrate CIL1 at Fimiston; the balance was deslimed, filtered and processed at the Gidji UFG and CIL circuit. Existing acid wash, elution and regeneration kilns were used.
Stage 2 scope: new CIL4 treating combined thickened flotation tails plus concentrate CIL tails; additional UFG mill (UFG 3) so Gidji can be decommissioned; CIL2 repurposed for concentrate leaching and CIL3 for adsorption; second existing Fimiston flotation tails thickener (30-TH-31) repurposed as the UFG product / concentrate pre-leach thickener; additional elution and EW capacity and reagent facilities (lead nitrate, HCl, caustic, cyanide, lime, antiscalant, oxygen). In Stage 2 all flotation tails thickener underflow goes to CIL4. Stage 2 expected to add 1 to 2 percent recovery and remove concentrate haulage to Gidji.
PFD legends: SP1 / SP2 = Separable Portion 1 / 2 (Stage 1 / Stage 2 contract scope).

DESIGN BASIS (PDC Stage 2, nominal case unless stated)
Throughput nominal 25.5 Mtpa (reduced 24.0 Mtpa design grade case; 28.35 Mtpa high throughput case at P80 220 um). Old Fimiston circuit alone was 10.5 Mtpa.
Crushing availability 65 percent (5,694 h/a). Concentrator availability 93.4 percent (8,182 h/a). UFG availability 93.4 percent.
Crushing rate new circuit 2,634 t/h nominal, design 3,135 t/h, crusher max 3,436 t/h. Existing crusher 1,844 t/h.
Mill feed: existing Fimiston SAG 1,313 t/h plus new SAG 1,833 t/h = 3,146 t/h nominal to cyclones/flotation (3,494 t/h high case).
Nominal head grade 1.58 g/t Au, 1.02 percent S. Design grade 1.81 g/t Au, 1.49 percent S. Achievable grade case 1.70 g/t Au, 1.40 percent S.
Recovery nominal: total Au 84 percent; gravity 14 percent of feed (max 20); flotation Au 71.8 percent (max 75); flotation S 85.1 percent (max 90); concentrate leach 84 percent (range 80 to 88, later agreed 90 percent for CIL2/3 design); flotation tails leach 34 percent (CIL4 design extraction 38 percent, adsorption efficiency 88 percent).
Gold production 1.11 Moz/a nominal grade case, 1.19 Moz/a design grade, 1.20 Moz/a achievable grade, 1.23 Moz/a high throughput. Flotation concentrate 637 kt/a nominal (about 75 to 78 t/h), 876 kt/a design grade and achievable grade (about 104 to 107 t/h), 707 kt/a high throughput.
Process water SG 1.07 (saline). Scheme water SG 1.00.

CRUSHING (F10 existing PC1, F12 new PC2)
ROM feed F80 450 mm, F99 1,000 mm. Trucks CAT 793F, 250 t payload, dump pocket direct tip two sides, 179 m3 live one side.
New crusher: gyratory FLS 1300 x 1900 TSUV, OSS 165 mm, throw 38 mm, 600 kW. Existing: 54-75 Mk II, OSS 141 mm, 450 kW. Product P80 130 mm (145 mm high case); simulated P80 122 mm, P100 229 mm.
Crushed ore stockpile new: live 12,035 m3 (60 deg drawdown), about 20,460 t at 1.70 t/m3, residence about 11 h. Existing COS live about 21,000 t (16 h).
Discharge apron feeder 1 off, design 3,135 t/h, speed controlled to stockpile feed weightometer tonnage setpoint. Reclaim apron feeders 2 off, design 2,017 t/h each (110 percent of nominal). One emergency apron feeder fed by CAT 992K/994K loader.
Controls: PC2 run from existing crusher control room with CCTV. Truck traffic lights automatic from truck radar, ROM bin level, discharge chamber level and HH switch, crusher running and rock breaker position. Crusher gap auto adjusted from camera particle size analyser on stockpile feed. Rock breaker remote by camera, auto park. Apron feeder interlocked to discharge conveyor run, discharge chamber LL and head chute HH. Stockpile feed conveyor interlocked to stockpile HH switch and level HH alarm. Wet scrubber and dust extraction must run.

MILLING AND CLASSIFICATION (F13 new, F19 existing Fimiston Area A)
SABC circuit. Grind target P80 180 um (max 250); 220 um in high throughput case.
New SAG: 10.97 m dia x 8.38 m EGL, 20 MW installed, pinion duty about 16.8 MW, speed 60 to 83 percent Cs, ball charge 10.5 percent v/v, total load 27 percent (structural 18 percent balls, 35 percent total), discharge 75 percent solids, steel liners, pebble ports 75 mm, grate open area 11 to 12 percent, curved pulp lifters 2,100 m3/h max, trommel 3.829 m x 3.8 m, 12 x 40 mm apertures. SAG specific energy modelled 9.14 kWh/t (7.68 high case).
Existing Fimiston SAG: 10.97 m x 4.27 m EGL, 12 MW. Discharge pumped by duty/duty Fimiston mill transfer pumps from Fimiston SAG discharge hopper to new primary cyclone feed hopper (transfer density 60 percent). Transfer pumps interlocked if primary cyclone feed pump not running.
SAG discharge screen: horizontal vibrating 4.27 x 8.54 m, 12 x 55 mm slots, oversize about 375 t/h to pebble crushing.
Ball mill: overflow type 8.53 m x 13.26 m EGL, 20 MW, pinion about 17.7 MW, 60 to 78 percent Cs range, normally fixed speed about 75 percent, ball charge 28.5 percent (max 31, structural 38), Poly-Met liners, discharge 75 percent solids, trommel 19 x 40 mm slotted, scats bunker. Ball mill specific energy modelled 9.68 kWh/t at 180 um.
Pebble crushers: 2 x XL7 SH-HD cone, duty/duty, 375 kW each, CSS 7 mm, product P80 12 mm, feed F80 49 mm, 305 t/h each at CSS (610 t/h total allows for worn pebble ports), pebbles 16.6 to 28 percent of new feed. Feed bins 2 x 65 t. Automatic bypass on metal detection; bypass gate opens if bin High and both feeders stopped, or bin High-High. Feeders start on bin high level and stop on low level.
Cyclones: one Weir 800CVX13 cluster, 18 outlets, 17 installed (15 primary duty, 2 gravity duty). Nominal 12 primary operating (max 14), 1 standby. Feed about 14,400 t/h solids, 13,233 m3/h at 62 percent solids (65 high case). Underflow 77 percent solids. Overflow 36.4 percent solids, 3,146 t/h. Circulating load 358 percent (UF/OF). Pressure about 82 kPa. Knife gate valves open one cyclone when feed pressure high for a set time, close one when low; minimum number open before cyclone feed pump start; cascade from hopper level to pressure setpoint. Hopper water addition controls cyclone feed or overflow density; Fast and Slow level tuning.
Reclaim feeders controlled to SAG feed weightometer tonnage or mill weight setpoint, normally from expert system; deadband for lag. Expert system inputs: SAG feed camera size analyser, SAG noise monitor, load, speed, power. Ball addition automatic to kg/t or mill weight.
Reline scenarios: new SAG single stage during ball mill reline; new SABC during Fimiston SAG reline; Fimiston SAG plus new ball mill during new SAG reline.
Trash screens: 4 linear screens (3 operating, 1 standby), 9.53 x 4.2 m, 1.0 x 1.0 mm aperture, max flux 75 m3/m2/h, spray 60 m3/h per screen. Trash dewatering screen 1.83 x 3.66 m, 1 x 15 mm. About 27 t/day wood, grit and trash removed.

GRAVITY AND INTENSIVE LEACH (F14), GRAVITY EW (F66)
2 gravity cyclones, each underflow to its own gravity scalping screen (horizontal vibrating 3.66 x 6.10 m, 3.2 x 18 mm slots first half, 2.0 x 18 mm second half, oversize 8 to 15 percent, design 10 percent, oversize to ball mill feed). Cyclone feed valves interlocked to their gravity screens.
2 Knelson KC-QS70 concentrators, max 1,000 t/h each, nominal 900 t/h each (1,800 t/h total), feed 54 percent solids, fluidising water 120 m3/h each, 30 min cycle including flush, 48 cycles/day, 150 kg concentrate per cycle, 14.4 t/day. Tails to primary cyclone feed hopper.
Intensive leach reactor: Acacia CS10000, 1 off, 1 batch/day nominal, 2 max, 12 h cycle, about 14.4 t per batch at 90 percent solids, leach recovery 92 to 98 percent (98 design), pregnant solution 14.5 m3 per batch at about 1,100 to 1,800 ppm Au, about 29 ppm Ag, 303 ppm Cu. Residue 40 percent solids.
Gravity EW: clean in place split cell 1000x1000-22D, 2 compartments of 11 cathodes, 24 m3/h per compartment, 10 h EW, barren below 5 ppm Au, 2 x 2,500 A rectifiers, current density 15 to 25 A/m2.

FLOTATION (F16 rougher/scavenger, F18 cleaner/cleaner-scavenger)
Feed 3,146 t/h at 34.4 percent solids, 6,719 m3/h, from trash screen underflow.
Roughers: 3 FLS forced air tank cells (F16-CF-411 to 413), total 1,890 m3 (630 m3 each), residence 15.1 min (existing plant was 10 to 12 min). Rougher 1 mass pull 4.4 percent at about 15.3 percent S, reports to the Jameson cleaner per the PDC mass balance (older PFDs showed it going to final concentrate). Only cleaner concentrate feeds the final concentrate hopper. Rougher 2 and 3 mass pull 2.4 percent at about 7.1 percent S, to cleaner. Rougher tail 2,946 t/h.
Scavengers: 4 cells (F16-CF-414 to 417), total 2,520 m3, residence 21.4 min (existing plant 29 to 32 min). Mass pull 1.1 percent at about 5.1 percent S, to cleaner. Scavenger tail 2,914 t/h to flotation tails thickener. Combined rougher plus scavenger residence 36.5 min.
Design lip loading and froth carry rate 1.5 t/m/h and 1.5 t/m2/h. Froth factors: rougher con 2.0, scavenger con 1.6, cleaner con 2.5, cleaner-scavenger con 2.0.
Cleaner: Glencore Jameson B6500/24, natural aspiration via downcomers, froth area 22.2 m2, feed 1,998 m3/h total incl. recycle at 17.5 to 19.5 percent solids, mass pull 31 to 44 percent, stage S recovery about 93 percent, concentrate SG 3.93. Cleaner tails about 50 percent recycled to cleaner feed hopper (external recycle keeps downcomer flow constant), rest to cleaner-scavenger. Feed = rougher 2/3 con, scavenger con, cleaner-scavenger con.
Cleaner-scavenger: Jameson B6500/24, feed 2,048 m3/h, concentrate about 13.1 percent S back to cleaner feed, tails about half recycled, rest to flotation tails thickener.
Final concentrate hopper F18-HP-414 to concentrate thickener feed box (existing 30-TH-61).
Controls: cell agitators started from OIS after field check, keep running whenever cell has slurry or water, reversible drives for even rotor wear. Two dart valves per cell on split range level control (series or parallel). Air per cell by flow controller with mass flow meter; air valve interlocks closed if agitator stops (prevents sanding rotor/stator, protects bearings). Blowers have VSDs holding header pressure. Jameson air depends on total pumped flow through downcomers, feed pump VSD on flow. OSA measures Au and Fe, S inferred from Fe, streams: flotation feed, rougher 1 con, rougher 2/3 con, scavenger con, scavenger tails, cleaner feed, cleaner-scavenger tails, final con, final tails. Flotation expert system uses OSA, froth cameras, launder velocity cameras to set level (froth depth), air and reagents.
Reagents: copper sulphate activator (dosed at SAG discharge and cleaner), PAX collector (potassium amyl xanthate), frother Luprofroth 168 (rougher, scavenger, cleaner and cleaner-scavenger feeds).

CONCENTRATE HANDLING AND UFG (F35, F34 UFG 1, F28 UFG 2/3)
Concentrate thickener (existing 30-TH-61) feed about 25 percent solids, testwork flux 0.25 t/m2/h. Filter feed tanks A and B (balance line), about 60 percent solids.
UFG 1 existing: IsaMill M3000, 1,120 kW, about 10 t/h (13 design) when used. UFG 2 and 3 new: IsaMill M15000, 3.8 MW installed, 3.5 MW draw, 30 t/h fresh feed nominal each, 46 t/h max at P80 12 um. Product P80 9 um (9 to 12). Specific energy 116.5 kWh/t. Closed circuit with Weir 100CVX cyclones (underflow 48 percent, overflow 17 to 18 percent solids). Inclined static wedge wire trash screens 1.0 mm ahead of UFG 2/3; UFG 1 vibrating 1.0 mm mesh screen. Scheme water for gland seal.
Stage 2 UFG operating: UFG 2 and 3 normally; at high concentrate, UFG 2/3 at max with excess to UFG 1. Excess beyond UFG goes to existing vacuum belt filters (55 m2, cake below 10 percent moisture) and concentrate stockpile (TML 6.1 to 8.3 percent w/w).
UFG controls: feed pump on flow control with density and mass flow; feed hopper water addition holds feed solids or cools mill if discharge above 60 C; media addition by positioning knife gate to hold mill power draw setpoint; shell vibration monitoring; hardwired motor interlocks; liquid resistance starters on vendor PLC; online particle size analyser. UFG 3 discharge hopper density by water addition, swaps to level control if level low; cyclone valves on pressure or level deadband.
Concentrate pre-leach thickener: existing 30-TH-31 repurposed, underflow 52 to 58 percent solids, duty/standby VSD underflow pumps cascade from bed pressure or density; can recycle to feed box.

CONCENTRATE LEACH CIL2 / CIL3 (F30, carbon side F65)
CIL2 repurposed for leach only: tanks 30-TK-32A to 32F plus new 32G, 1,685 m3 each, pH 11.75 to 12.5 early tanks, 11 to 12.5 later. High cyanide targets increasing along the train (1,000 to 6,500 ppm in later tanks). Oxygen: side lances on tanks plus new VSD oxygen injection pumps on first two tanks. Milk of lime and lead nitrate at leach feed box. Cyanide ratioed to solids mass flow on CIL2 feed. Portion of spent eluate returns to CIL2. Design leach extraction 90 percent. Feed about 104 t/h solids at about 49 percent solids.
CIL3 repurposed for adsorption only: 6 tanks x 1,685 m3 (10,110 m3), no oxygen. Carbon about 20 g/L, 202 t carbon in circuit, design loading about 4,490 g/t. Kemix MPSP 1200 intertank screens (1.0 mm). New single loaded carbon pump to new Derrick linear motion screen (0.8 x 12.8 mm) then hopper and pump to existing acid wash columns. New CIL3 barren carbon sizing screen. Carbon detection meter on CIL3 tails with reference probe. CIL3 tails hopper and duty/standby VSD pumps to CIL4 feed box; cyanide water added to hopper.
Existing elution: split AARL, 2 existing circuits, acid wash with HCl, existing regeneration kilns with off gas treatment.

FLOTATION TAILS THICKENER (F17)
Feed scavenger tails plus cleaner-scavenger tails, about 3,071 t/h, 6,871 m3/h, 33 percent solids. Underflow nominal 56 percent (range 50 to 62). Area 2,827 m2 (about 60 m dia), testwork flux 1.5 t/m2/h. Duty/standby underflow pumps, total about 3,329 m3/h. Underflow pumps in cascade from bed pressure or density to flow to VSD; recycle to feed on start up or low flow. Flocculant: Stage 1 cascaded from bed level (Manta sub); Stage 2 to feed solids ratio setpoint; inline mixer secondary dilution. Vendor panel signals: rake torque, bed level (SmartDiver), rake height, bed pressure (bed mass), overflow clarity. Overflow mainly feeds the Process Water Tank.

TAILS LEACH CIL4 (F21, carbon F22)
Feed: flotation tails thickener underflow plus CIL3 tails plus portion of spent eluate, about 3,164 t/h solids, 3,511 m3/h. 2 leach tanks plus 6 adsorption tanks (F21-TK-411 to 418), 5,600 m3 live each, space for a future extra tank. Leach residence 3.2 h, total 12.8 h (below 14 h ideal). Leach pH 8.8 to 9.3. Carbon 12.5 g/L, loading range 332 to 579 g/t. Leach extraction 38 percent, adsorption efficiency 88 percent (84 to 92).
Controls: pH controller on tank 1 (tank 2 as backup) opens milk of lime valve at CIL4 feed distribution box. Cyanide flow control at front end, setpoint by operator or g/t on thickener underflow tonnes, trimmed by cyanide analyser (tanks 1 and 2); extra cyanide lines on each leach tank and adsorption tank 3. HCN gas monitor with beacon and siren. Oxygen by VSD injection pumps with flow control valves on both leach tanks, plus side lances on leach tanks and first two adsorption tanks; DO analysers alarm high/low. Kemix MPS2535(P) intertank screens 1.0 mm wedge wire. Gekko Carbon Scout MK6 samples all adsorption tanks (carbon g/L) and leach tanks (DO, pH, solids). Pneumatic slurry bypass gates operated locally only. Loaded carbon routing between tanks by removable spool pieces. Loaded carbon pumped from first adsorption tank to loaded carbon screen (horizontal vibrating 1.83 x 4.88 m, 0.8 x 18.5 mm) then transfer vessel to elution. Barren carbon returns to last tank via CIL4 carbon sizing screen. Carbon detection meter on tails with reference probe at front end. Three stage sampler takes shift composite of CIL4 tails. Future carbon safety screens (4.27 x 7.93 m, 0.85 x 18.5 mm). CIL4 static screen (sieve bend, 1 mm) for event pond and silt trap return.
Final tails tank: CIL4 tails, acid wash waste, fine carbon waste, about 3,164 t/h at 54.5 percent solids. Tailings pumps duty/duty/duty/standby to TSF (Fim III, WBS T03), each line with flowmeter, density and pressure; second flowmeter near deposition end for leak detection; tank level sets pump flow setpoints.

CIL4 ELUTION, REGEN, EW
Single SAF2205 duplex stainless column for acid wash and elution. Split AARL sequence: carbon transfer in, acid wash (dilute HCl), water rinse, pre-soak with caustic and cyanide, elution with lean eluate, elution with scheme water, cooling with scheme water, carbon out. Column pressurised to stop flashing. LPG fired heater (TPE package) with burner management system; temperature controller on eluate line. Pregnant eluate to CIL4 eluate circulation tanks; when full, diverts to lean eluate tank. 5 bed volumes of eluate. Barren carbon educted to regen kiln dewatering screen and kiln feed hopper; kiln package (Lochhead) with screw feeder and vendor PLC in an overall regeneration sequence with quench tank and barren carbon pump; mercury abatement system must run with the kiln. Fresh carbon added via hoist, bag splitter and quench hopper. CIL4 EW: two split feed cells, VSD pumps on flow control, batch by sequence or manual.

WATER, AIR, REAGENTS
Water types: saline bore process water (SG 1.07), scheme water (fresh pipeline), raw water, HP process water, mill circuit water, cyanide water (TSF decant return), gland water, potable and fire water. Raw Water Tank lower portion supplies LP and HP gland water pumps; fed from Bore Water / Saline Dam 3 via booster pumps. Process Water Tank duty/standby pumps, mainly fed by flotation tails thickener overflow, top up from Bore Water Dam 2 (South Dam) by three DOL saline pumps that trip on dam LL level. Saline sources include Kaltails borefield (N02), Eastern Borefield, Gidji saline transfer dam.
Cyanide destruct: hydrogen peroxide via inline mixers on the 3 decant water lines, controlled by online WAD cyanide analyser and flowmeters, residual WAD target about 1.5.
Air: LP flotation blowers with VSDs on header pressure; plant and instrument air compressors; oxygen from new oxygen plant (PSA) with liquid oxygen, to CIL2/3 and CIL4.
Reagents: copper sulphate, PAX, frother (VSD dosing pumps, flow control, g/t or flow setpoint). Cyanide and caustic via pressurised ringmains with DOL pumps and mechanical back pressure valve on return; flowmeters at each dosing point. Caustic tank immersion heater on below about 20 C off above about 25 C to stop freezing. Lead nitrate VSD pumps on flow (g/t). HCl DOL dosing pumps started by elution sequences; separate dilute acid tank for CIL4. Quicklime slaked in vendor lime plant (two parallel circuits, slaking mills, cyclones, scrubber) to milk of lime tank, ringmain with duty/standby DOL pumps. Flocculant plant: screw feeder, heated cone, blower, wetting head; existing thickeners' floc pumps on VSD cascaded from bed level. Antiscalant from IBCs on manual metering pumps. Cyanide NaCN about 29 percent solution, nominal about 21.5 kg/t of concentrate dosed across six tanks. Grinding media: SAG 125 mm balls; UFG ceramic media.

CONTROL SYSTEM GENERAL
Yokogawa Centum VP DCS with Field Control Stations; PI historian. Two main control rooms: Fimiston Crusher control room and Main Mill control building. CRO = control room operator, OIS = operator screens.
Drive modes selected from OIS only: Automatic (DCS control, no LCS start, LCS stop works), Manual (CRO start/stop from OIS, LCS start/stop), Local (LCS start only, bypasses process interlocks and start permissives, critical interlocks stay, timer returns drive to target mode, for fault finding and maintenance only, must be supervised). Mode changes are bumpless.
Interlocks: Critical (E-stops, pull wires, protection relays; trip in all modes; cannot be bypassed), Process (trip in Auto and Manual; bypass by named users individually), Start permissives (prevent start only). Configurable time delays on DCS interlocks. First out detection on trips.
Loop modes: Manual, Automatic, Cascade. PV, SV, CV.
Sequences: group start/stop from OIS; drives must be in Auto or Manual; steps confirm feedback within a transition time or the sequence pauses; restart sequences work backwards from downstream with checks (flocculant, thickener rakes, mill inching, pumps and dump valves).
Large drives: no link to Parkeston Power Station, CRO phones for approval before starting mills; sequence pauses for confirmation. Start sirens and flashing lights on crushers, feeders, conveyors, mills.
Conveyors: start siren, LCS E-stop, pull wires (reset in field), inner (alarm) and outer (trip) belt drift switches, under-speed sensor, belt rip detector, microwave blocked chute switch with delay. Trip stops interlocked upstream equipment.
Valves: Auto or Manual; watchdog timer for fail to open/close; both limit switches on or off flagged; open/close permissives and trips.
Pumps: duty/standby with actuated suction, discharge and dump valves; dump valves fail open on power loss; standby changeover case by case. Gland water: manual isolation, actuated valve opened in start sequence, Maric constant flow valve, flow switch (mag flowmeter on cyclone feed, thickener underflow and final tails pumps); low gland flow blocks start, trips after delay when running. Sump pumps start on high level, run until high clears plus run on time or low level.
Dual hopper level control: loop A pump speed at higher setpoint, loop B water addition at lower setpoint to keep minimum line velocity.
Measurement: weightometers with calibration chains, totals per 12 h shift and day from 5:00 am, wet to dry by moisture input; slurry mass flow by mag flowmeter plus nucleonic density with operator entered solids SG.
Alarms: ISA-18.2, priorities Logging, Low, High, Urgent; analogue LL, L, H, HH; masked when equipment not running.
Power: emergency generator auto start, essential generator manual start, UPS on DCS and RIO, emergency lighting 90 min. Switchroom fire alarm, sprinkler interlocks with lube and hydraulic pumps and conveyors with external lube. LV DOL starters with electronic overloads on Modbus TCP; VSDs on field network, E-stop to Safe Torque Off. Electrical SLD displays from 33 kV incomers to 415 V MCC incomers.
Vendor packages with own PLC report to DCS (e.g. rock breaker, OSA, particle size analysers, compressors, chillers, samplers, IsaMill LRS, regen kiln). SAG, ball mill, flotation cells, thickener, Knelsons, ILR, EW cells, Jameson cells are DCS controlled.

NUMBERING
Tags F + area + equipment code + number, e.g. F13-MS-401 (Fimiston, Milling, SAG mill, 401). New equipment numbers start at 401. Conveyors take the area they feed. Motors = equipment number without dashes (F21PU001), VSD suffix -VS, LCS -LCS. Cables: -P power, -N neutral, -I instrumentation, -C control, -E earth, -D digital, -FO fibre. Instruments: letters plus area plus loop, e.g. FIT13001; first letter measured variable (A analysis, D density, F flow, L level, P pressure, T temperature, W weight, Z position), following letters function (I indicate, T transmit, C control, A alarm, H high, L low, V valve).
Areas: F00 general, F10 PC1 existing, F12 PC2 new, F13 milling, F14 gravity/ILR, F15 Mt Charlotte stockpile, F16 rougher/scavenger, F17 flot tails thickening, F18 cleaner/cleaner-scavenger, F19 Fimiston milling Area A, F20 Area B, F21 CIL4, F22 CIL4 elution, F23 final tails, F24 air and water, F25 cleaner existing, F26 cleaner-scavenger existing, F28 UFG 2/3, F30 conc thickening and CIL2/3, F34 UFG existing, F35 conc handling and filtration, F65 conc carbon and elution, F66 EW and goldroom, F70 existing lime and floc, F71 existing reagents, F72 reagents, F75 water existing, F78 carbon regen existing, F81 air existing. WBS: M mining, F Fimiston processing, T tailings (T03 Fim III TSF), N non process infrastructure (N02 Kaltails borefields), P indirects.
`;
