// Quick reference glossary: [term, meaning, discipline]. Disciplines: General, Process, Mechanical, Piping, Electrical,
// Instrumentation & control, Civil, Structural (the pills above the glossary). The electrical terms come from the
// electrical lists and SLDs.
const GLOSSARY = [
  ["F00", "General FIM Site (HV power, buried services, pipe racks)", "General"],
  ["F10", "Primary Crushing, FIM Existing (Primary Crushing 1)", "General"],
  ["F12", "Primary Crushing, new (Primary Crushing 2), crushed ore stockpile", "General"],
  ["F13", "Milling & Classification (new SAG, ball mill, pebble crushing, cyclones, trash screens)", "General"],
  ["F14", "Gravity Circuit & Intensive Leaching (Knelsons, ILR)", "General"],
  ["F15", "Mt Charlotte Stockpile / Reclaim", "General"],
  ["F16", "Rougher & Scavenger Flotation (FLS tank cells)", "General"],
  ["F17", "Flotation Tailings Pre-Leach Thickening", "General"],
  ["F18", "Cleaner & Cleaner-Scavenger Flotation (Jameson cells)", "General"],
  ["F19", "Milling & Classification, FIM Existing, Area A (old SAG)", "General"],
  ["F20", "Milling & Classification, Area B", "General"],
  ["F21", "Flotation Tailings CIL4", "General"],
  ["F22", "CIL4 Carbon Treatment & Elution, CIL4 regen kiln", "General"],
  ["F23", "Final Tailings Handling & Storage", "General"],
  ["F24", "Air & Water Services (new)", "General"],
  ["F25", "Cleaner Flotation, Existing", "General"],
  ["F26", "Cleaner Scavenger Flotation, Existing", "General"],
  ["F28", "Ultra Fine Grinding 2/3 (new IsaMills M15,000)", "General"],
  ["F30", "Concentrate Pre-Leach Thickening, CIL2/3, Post-Leach Thickening", "General"],
  ["F34", "Ultra Fine Grinding, Existing (UFG 1, IsaMill M3000)", "General"],
  ["F35", "Concentrate Handling & Filtration", "General"],
  ["F65", "Concentrate Carbon Treatment & Elution", "General"],
  ["F66", "Electrowinning & Goldroom", "General"],
  ["F70", "Existing Lime Plant & Flocculant", "General"],
  ["F71", "Existing Reagents", "General"],
  ["F72", "Reagents Mixing & Storage", "General"],
  ["F75", "Water Services, Existing", "General"],
  ["F78", "Carbon Regeneration, Existing", "General"],
  ["F81", "Air Services, Existing", "General"],
  ["T03", "Fim III Tailings Storage Facility", "General"],
  ["N02", "Kaltails Borefields (saline water)", "General"],
  ["SP1 / SP2", "Separable Portion 1 / 2 (Stage 1 / Stage 2 contract scope)", "General"],
  ["401", "Start number for new Growth Project equipment and instruments", "General"],
  ["AG", "Agitator", "Mechanical"],
  ["BN", "Bin", "Mechanical"],
  ["CC", "Cone crusher", "Mechanical"],
  ["CF", "Flotation cell", "Mechanical"],
  ["CG", "Gyratory crusher", "Mechanical"],
  ["CN", "Elution column", "Mechanical"],
  ["CV", "Conveyor", "Mechanical"],
  ["CY", "Cyclone", "Mechanical"],
  ["FA", "Apron feeder", "Mechanical"],
  ["FB", "Belt feeder", "Mechanical"],
  ["HP", "Hopper", "Mechanical"],
  ["IL", "Intensive leach reactor", "Mechanical"],
  ["KN", "Kiln", "Mechanical"],
  ["MB", "Ball mill", "Mechanical"],
  ["MS", "SAG mill", "Mechanical"],
  ["MU / MUF", "UFG mill (MU meant existing and MUF new, but all UFG mills in the data are tagged MUF)", "Mechanical"],
  ["MG", "Tramp magnet", "Mechanical"],
  ["PP", "Process pump", "Mechanical"],
  ["PS", "Sump pump", "Mechanical"],
  ["PW", "Water pump", "Mechanical"],
  ["RB", "Rock breaker", "Mechanical"],
  ["SA", "Isa sampler", "Mechanical"],
  ["SC", "Screen", "Mechanical"],
  ["SL", "Trash screen", "Mechanical"],
  ["SU", "Sump only (not the pump)", "Mechanical"],
  ["TH", "Thickener", "Mechanical"],
  ["TK", "Tank", "Mechanical"],
  ["VL", "Launder / sump / kibble", "Mechanical"],
  ["WD", "Weightometer", "Mechanical"],
  ["SW", "Switchboard / MCC", "Electrical"],
  ["VS", "Variable speed drive", "Electrical"],
  ["LCS", "Local control station", "Electrical"],
  ["SR", "Switchroom", "Electrical"],
  ["TR", "Transformer", "Electrical"],
  ["-P / -C / -I / -E", "Cable suffix: power / control / instrumentation / earth", "Electrical"],
  ["FIT", "Flow indicating transmitter", "Instrumentation & control"],
  ["LT / LIC", "Level transmitter / level indicating controller", "Instrumentation & control"],
  ["DT", "Density transmitter", "Instrumentation & control"],
  ["AE / AIT", "Analysis element / transmitter (pH, DO, CN)", "Instrumentation & control"],
  ["LAH / LAL", "Level alarm high / low", "Instrumentation & control"],
  ["ROM", "Run of mine ore", "Process"],
  ["COS", "Coarse (crushed) ore stockpile", "Process"],
  ["SABC", "SAG, Ball mill, pebble Crusher circuit", "Process"],
  ["SAG", "Semi autogenous grinding mill", "Process"],
  ["P80 / F80", "Size 80% of product / feed passes", "Process"],
  ["OSS / CSS", "Crusher open / closed side setting", "Process"],
  ["%Cs", "Percent of mill critical speed", "Process"],
  ["EGL", "Effective grinding length", "Process"],
  ["Circ load", "Cyclone underflow returned as % of new feed", "Process"],
  ["Scats", "Oversize rejected by ball mill trommel", "Process"],
  ["Pebbles", "SAG critical size rocks to pebble crushers", "Process"],
  ["Roping", "Overloaded cyclone underflow, coarse to overflow", "Process"],
  ["Knelson", "Centrifugal gravity concentrator (KC-QS70)", "Process"],
  ["ILR", "Intensive leach reactor (Acacia CS10000)", "Process"],
  ["PAX", "Potassium amyl xanthate, collector", "Process"],
  ["CuSO₄", "Copper sulphate, activator", "Process"],
  ["Frother", "Luprofroth 168, stabilises froth", "Process"],
  ["Mass pull", "% of feed mass to concentrate", "Process"],
  ["Jameson", "Plunging jet flotation cell, no blower", "Process"],
  ["OSA", "Onstream analyser", "Instrumentation & control"],
  ["UFG", "Ultra fine grinding (IsaMill) to about 9 µm", "Process"],
  ["TML", "Transportable moisture limit", "Process"],
  ["CIL", "Carbon in leach", "Process"],
  ["CIL2 / CIL3", "Concentrate leach / concentrate adsorption (Stage 2)", "Process"],
  ["CIL4", "Flotation tails leach and adsorption", "Process"],
  ["DO", "Dissolved oxygen", "Process"],
  ["Carbon Scout", "Gekko auto sampler for carbon g/L per tank", "Instrumentation & control"],
  ["Loaded / barren carbon", "Carbon holding gold / stripped of gold", "Process"],
  ["AARL", "Elution method: acid wash, caustic cyanide pre-soak, hot water strip", "Process"],
  ["BV", "Bed volume", "Process"],
  ["Pregnant / lean / barren eluate", "Rich / partly used / stripped solution", "Process"],
  ["EW", "Electrowinning", "Process"],
  ["Doré", "Gold/silver bar poured in goldroom", "Process"],
  ["Regen", "Carbon regeneration kiln (thermal reactivation)", "Process"],
  ["WAD CN", "Weak acid dissociable cyanide", "Process"],
  ["TSF", "Tailings storage facility", "General"],
  ["Scheme water", "Fresh pipeline water, SG 1.00", "Process"],
  ["Process water", "Saline bore water, SG about 1.07", "Process"],
  ["Cyanide water", "TSF decant return, peroxide treated", "Process"],
  ["Gland water", "Clean seal water to slurry pump glands", "Piping"],
  ["MoL", "Milk of lime", "Process"],
  ["PSA", "Pressure swing adsorption oxygen plant", "Process"],
  ["LPG", "Fuel for CIL4 elution heater", "Process"],
  ["PDC", "Process design criteria", "General"],
  ["PFD", "Process flow diagram", "General"],
  ["P&ID", "Piping and instrumentation diagram", "General"],
  ["TQ", "Technical query", "General"],
  ["SysCAD", "Mass balance model software", "General"],
  ["WBS", "Work breakdown structure", "General"],
  ["DCS", "Distributed control system (Yokogawa Centum VP)", "Instrumentation & control"],
  ["OIS", "Operator interface system, the control room screens", "Instrumentation & control"],
  ["CRO", "Control room operator", "Instrumentation & control"],
  ["CrCR", "Crusher control room", "Instrumentation & control"],
  ["FCS", "Field control station", "Instrumentation & control"],
  ["PI", "Plant data historian (trends)", "Instrumentation & control"],
  ["Auto / Manual / Local", "Drive modes: DCS controlled / operator from OIS / field LCS only, process interlocks bypassed", "Instrumentation & control"],
  ["Critical interlock", "Safety trip (E-stop, pull wire, protection relay), active in every mode", "Instrumentation & control"],
  ["Process interlock", "Trips a drive in Auto and Manual to prevent spills or poor performance", "Instrumentation & control"],
  ["Start permissive", "Must be healthy to start, does not trip a running drive", "Instrumentation & control"],
  ["First out", "The trip that happened first", "Instrumentation & control"],
  ["PV / SV / CV", "Process variable / setpoint / controller output", "Instrumentation & control"],
  ["Cascade", "Master loop sets the setpoint of a slave loop", "Instrumentation & control"],
  ["DOL", "Direct on line starter", "Electrical"],
  ["EOL", "Electronic overload relay", "Electrical"],
  ["STO", "Safe Torque Off, VSD E-stop input", "Electrical"],
  ["Maric valve", "Constant flow valve on gland water", "Piping"],
  ["Dart valve", "Flotation cell discharge valve for level control", "Mechanical"],
  ["Manta sub / SmartDiver", "Thickener bed level sensors", "Instrumentation & control"],
  ["Single stage", "SAG running without the ball mill (e.g. during ball mill reline)", "Process"],
  ["MCC", "Motor control centre: the switchboard that starts, protects and controls a group of motors", "Electrical"],
  ["HV / LV", "High voltage (above 1 kV, here 33 kV, 11 kV and 3.3 kV) / low voltage (415 V and 240 V)", "Electrical"],
  ["VSD", "Variable speed drive: sets a motor's speed by varying the supply frequency (tag suffix -VS)", "Electrical"],
  ["Soft starter", "Ramps a motor's voltage up to limit starting current (tag suffix -SS)", "Electrical"],
  ["DB", "Distribution board: feeds lighting, small power and auxiliary circuits", "Electrical"],
  ["L&SP", "Lighting and small power", "Electrical"],
  ["UPS", "Uninterruptible power supply: battery backed supply for control and comms", "Electrical"],
  ["Essential / emergency switchboard", "Board kept alive by the emergency generator, for loads that must run in an outage", "Electrical"],
  ["Incomer", "The switchboard's main supply breaker", "Electrical"],
  ["Feeder", "An outgoing circuit from a switchboard to a load or another board", "Electrical"],
  ["Busbar", "Copper bar inside a switchboard that the incomer and feeders connect to", "Electrical"],
  ["CB / ACB / MCCB", "Circuit breaker / air circuit breaker / moulded case circuit breaker", "Electrical"],
  ["ELR", "Earth leakage relay: trips on current leaking to earth", "Electrical"],
  ["FLC", "Full load current: a motor's current at rated output", "Electrical"],
  ["CT / VT", "Current transformer / voltage transformer, for metering and protection", "Electrical"],
  ["NER", "Neutral earthing resistor: limits earth fault current on a transformer neutral (tag -NR)", "Electrical"],
  ["ISL", "Isolator: local switch to lock off a motor for maintenance", "Electrical"],
  ["JB", "Junction box", "Electrical"],
  ["RIO", "Remote IO panel: field inputs and outputs wired back to the DCS over a network", "Electrical"],
  ["RTU", "Remote telemetry unit: sends signals from remote sites (e.g. TSF pumps) by radio", "Electrical"],
  ["FIP", "Fire indicator panel", "Electrical"],
  ["FOBOT", "Fibre optic break out tray: where a fibre cable is terminated", "Electrical"],
  ["HIM", "Human interface module: a VSD's keypad and display", "Electrical"],
  ["HF", "Harmonic filter: cleans up the distortion VSDs put on the supply", "Electrical"],
  ["XE", "Earth electrode (earth stake)", "Electrical"],
  ["Earth bar", "Copper bar in a switchroom that all equipment earths bond to (tag -EB)", "Electrical"],
  ["Arc flash", "Explosive release of energy from a fault in switchgear; boards are rated and labelled for it", "Electrical"],
  ["SLD", "Single line diagram: one line shows each three phase circuit from supply to load", "Electrical"],
  ["Schematic (SCM)", "Control wiring drawing of one circuit: starts, stops, interlocks, terminals", "Electrical"],
  ["TLD", "Three line diagram: all three phases drawn, for protection and metering", "Electrical"],
  ["Termination diagram (TER)", "Which core lands on which terminal at each end of a cable", "Electrical"],
  ["Cable schedule", "List of every cable: number, from, to, size, cores, length, route", "Electrical"],
  ["Load list", "Every electrical load with its rating, used to size boards and transformers", "Electrical"],
  ["XLPE / PVC / EPR", "Cable insulation: cross linked polyethylene / polyvinyl chloride / ethylene propylene rubber", "Electrical"],
  ["CWS / SWA", "Copper wire screen / steel wire armour, a cable's metal layer", "Electrical"],
  ["OSCN / IOSCN", "Overall screened / individually and overall screened instrument cable", "Electrical"],
  ["3C+E, 4C+E", "Number of cores: three or four power cores plus an earth", "Electrical"],
  ["0.6/1 kV, 1.9/3.3 kV", "Cable voltage rating: phase to earth / phase to phase", "Electrical"],
  ["Trefoil", "Three single core cables laid in a triangle and tied together, to balance heating", "Electrical"],
  ["Ladder", "Open cable tray like a ladder; cables are tied to its rungs", "Electrical"],
  ["CAT6A", "Shielded data cable for Ethernet", "Electrical"],
  ["E&I", "Electrical and instrumentation (the contractor scope)", "Electrical"],
  ["kVA / kVAr", "Apparent power / reactive power", "Electrical"],
  ["IP rating", "Ingress protection: dust and water rating of an enclosure (e.g. IP20, IP66)", "Electrical"],
  ["Space heater", "Small heater in a motor or panel that stops condensation when idle (tag -SH)", "Electrical"],
  ["Thermistor", "Temperature sensor in a motor winding that trips the motor if it overheats", "Electrical"],
  ["Fed from", "The switchboard or MCC a load is supplied by", "Electrical"],
  ["Document number", "2000-Fxx-TYP-DD-nnnnn: project, area, document type, discipline, sequence", "General"],
  ["PR / ME / PP / EL / IC", "Discipline codes in document numbers: process / mechanical / piping / electrical / instrumentation and control", "General"],
  ["CV (document)", "Civil, the discipline code in a document number", "Civil"],
  ["ST (document)", "Structural, the discipline code in a document number", "Structural"],
  ["GE (document)", "General, the discipline code in a document number", "General"],
  ["LST / DRG / DSH / STS / STD", "Document types: list / drawing / datasheet / specification / standard drawing", "General"],
  ["REP / DCR / TQY / BLK", "Document types: report / design criteria / technical query / block diagram", "General"],
  ["DN", "Nominal pipe size in mm (DN150 = 150 mm pipe)", "Piping"],
  ["Pipe spec", "Piping class code: material, pressure rating and fittings for a line (e.g. FD, PE16, SS1)", "Piping"],
  ["Line number", "Area-sequence-service-spec-size, e.g. 12-1606-COW-SS1-80", "Piping"],
  ["SPI", "Special piping item: anything in a line that isn't standard pipe, fitting or valve", "Piping"],
  ["Spool", "Prefabricated length of pipe with its fittings, made in the shop", "Piping"],
  ["Victaulic / Straub coupling", "Grooved / clamp-on pipe couplings, quick to take apart", "Piping"],
  ["NDE", "Non destructive examination of welds (X-ray, ultrasonic, dye penetrant)", "Piping"],
  ["HDPE", "High density polyethylene pipe", "Piping"],
];
