// Quick reference glossary: [term, meaning]
const GLOSSARY = [
  ["F00","General FIM Site (HV power, buried services, pipe racks)"],
  ["F10","Primary Crushing, FIM Existing (Primary Crushing 1)"],
  ["F12","Primary Crushing, new (Primary Crushing 2), crushed ore stockpile"],
  ["F13","Milling & Classification (new SAG, ball mill, pebble crushing, cyclones, trash screens)"],
  ["F14","Gravity Circuit & Intensive Leaching (Knelsons, ILR)"],
  ["F15","Mt Charlotte Stockpile / Reclaim"],
  ["F16","Rougher & Scavenger Flotation (FLS tank cells)"],
  ["F17","Flotation Tailings Pre-Leach Thickening"],
  ["F18","Cleaner & Cleaner-Scavenger Flotation (Jameson cells)"],
  ["F19","Milling & Classification, FIM Existing, Area A (old SAG)"],
  ["F20","Milling & Classification, Area B"],
  ["F21","Flotation Tailings CIL4"],
  ["F22","CIL4 Carbon Treatment & Elution, CIL4 regen kiln"],
  ["F23","Final Tailings Handling & Storage"],
  ["F24","Air & Water Services (new)"],
  ["F25","Cleaner Flotation, Existing"],
  ["F26","Cleaner Scavenger Flotation, Existing"],
  ["F28","Ultra Fine Grinding 2/3 (new IsaMills M15,000)"],
  ["F30","Concentrate Pre-Leach Thickening, CIL2/3, Post-Leach Thickening"],
  ["F34","Ultra Fine Grinding, Existing (UFG 1, IsaMill M3000)"],
  ["F35","Concentrate Handling & Filtration"],
  ["F65","Concentrate Carbon Treatment & Elution"],
  ["F66","Electrowinning & Goldroom"],
  ["F70","Existing Lime Plant & Flocculant"],
  ["F71","Existing Reagents"],
  ["F72","Reagents Mixing & Storage"],
  ["F75","Water Services, Existing"],
  ["F78","Carbon Regeneration, Existing"],
  ["F81","Air Services, Existing"],
  ["T03","Fim III Tailings Storage Facility"],
  ["N02","Kaltails Borefields (saline water)"],
  ["SP1 / SP2","Separable Portion 1 / 2 (Stage 1 / Stage 2 contract scope)"],
  ["401","Start number for new Growth Project equipment and instruments"],
  ["AG","Agitator"],["BN","Bin"],["CC","Cone crusher"],["CF","Flotation cell"],["CG","Gyratory crusher"],
  ["CN","Elution column"],["CV","Conveyor"],["CY","Cyclone"],["FA","Apron feeder"],["FB","Belt feeder"],
  ["HP","Hopper"],["IL","Intensive leach reactor"],["KN","Kiln"],["MB","Ball mill"],["MS","SAG mill"],
  ["MU / MUF","UFG mill existing / new"],["MG","Tramp magnet"],["PP","Process pump"],["PS","Sump pump"],
  ["PW","Water pump"],["RB","Rock breaker"],["SA","Isa sampler"],["SC","Screen"],["SL","Trash screen"],
  ["SU","Sump only (not the pump)"],["TH","Thickener"],["TK","Tank"],["VL","Launder / sump / kibble"],
  ["WD","Weightometer"],["SW","Switchboard / MCC"],["VS","Variable speed drive"],["LCS","Local control station"],
  ["SR","Switchroom"],["TR","Transformer"],
  ["-P / -C / -I / -E","Cable suffix: power / control / instrumentation / earth"],
  ["FIT","Flow indicating transmitter"],["LT / LIC","Level transmitter / level indicating controller"],
  ["DT","Density transmitter"],["AE / AIT","Analysis element / transmitter (pH, DO, CN)"],
  ["LAH / LAL","Level alarm high / low"],
  ["ROM","Run of mine ore"],["COS","Coarse (crushed) ore stockpile"],["SABC","SAG, Ball mill, pebble Crusher circuit"],
  ["SAG","Semi autogenous grinding mill"],["P80 / F80","Size 80% of product / feed passes"],
  ["OSS / CSS","Crusher open / closed side setting"],["%Cs","Percent of mill critical speed"],
  ["EGL","Effective grinding length"],["Circ load","Cyclone underflow returned as % of new feed"],
  ["Scats","Oversize rejected by ball mill trommel"],["Pebbles","SAG critical size rocks to pebble crushers"],
  ["Roping","Overloaded cyclone underflow, coarse to overflow"],
  ["Knelson","Centrifugal gravity concentrator (KC-QS70)"],["ILR","Intensive leach reactor (Acacia CS10000)"],
  ["PAX","Potassium amyl xanthate, collector"],["CuSO₄","Copper sulphate, activator"],
  ["Frother","Luprofroth 168, stabilises froth"],["Mass pull","% of feed mass to concentrate"],
  ["Jameson","Plunging jet flotation cell, no blower"],["OSA","Onstream analyser"],
  ["UFG","Ultra fine grinding (IsaMill) to about 9 µm"],["TML","Transportable moisture limit"],
  ["CIL","Carbon in leach"],["CIL2 / CIL3","Concentrate leach / concentrate adsorption (Stage 2)"],
  ["CIL4","Flotation tails leach and adsorption"],["DO","Dissolved oxygen"],
  ["Carbon Scout","Gekko auto sampler for carbon g/L per tank"],
  ["Loaded / barren carbon","Carbon holding gold / stripped of gold"],
  ["AARL","Elution method: acid wash, caustic cyanide pre-soak, hot water strip"],
  ["BV","Bed volume"],["Pregnant / lean / barren eluate","Rich / partly used / stripped solution"],
  ["EW","Electrowinning"],["Doré","Gold/silver bar poured in goldroom"],
  ["Regen","Carbon regeneration kiln (thermal reactivation)"],
  ["WAD CN","Weak acid dissociable cyanide"],["TSF","Tailings storage facility"],
  ["Scheme water","Fresh pipeline water, SG 1.00"],["Process water","Saline bore water, SG about 1.07"],
  ["Cyanide water","TSF decant return, peroxide treated"],["Gland water","Clean seal water to slurry pump glands"],
  ["MoL","Milk of lime"],["PSA","Pressure swing adsorption oxygen plant"],["LPG","Fuel for CIL4 elution heater"],
  ["PDC","Process design criteria"],["PFD","Process flow diagram"],
  ["P&ID","Piping and instrumentation diagram"],["TQ","Technical query"],["SysCAD","Mass balance model software"],
  ["WBS","Work breakdown structure"],
  ["DCS","Distributed control system (Yokogawa Centum VP)"],["OIS","Operator interface system, the control room screens"],
  ["CRO","Control room operator"],["CrCR","Crusher control room"],["FCS","Field control station"],["PI","Plant data historian (trends)"],
  ["Auto / Manual / Local","Drive modes: DCS controlled / operator from OIS / field LCS only, process interlocks bypassed"],
  ["Critical interlock","Safety trip (E-stop, pull wire, protection relay), active in every mode"],
  ["Process interlock","Trips a drive in Auto and Manual to prevent spills or poor performance"],
  ["Start permissive","Must be healthy to start, does not trip a running drive"],
  ["First out","The trip that happened first"],["PV / SV / CV","Process variable / setpoint / controller output"],
  ["Cascade","Master loop sets the setpoint of a slave loop"],["DOL","Direct on line starter"],["EOL","Electronic overload relay"],
  ["STO","Safe Torque Off, VSD E-stop input"],["Maric valve","Constant flow valve on gland water"],
  ["Dart valve","Flotation cell discharge valve for level control"],["Manta sub / SmartDiver","Thickener bed level sensors"],
  ["Single stage","SAG running without the ball mill (e.g. during ball mill reline)"],
];
