// Data for the interactive desktop PFD (pfd.html).
// Values are design figures from the Stage 2 PDC (2000-F00-DCR-PR-10002 Rev 4), control notes from the
// Stage 1 and Stage 2 Plant General Process Control Philosophies, routing from the Stage 1 as built PFDs.
// st: "b" both stages, 1 Stage 1 only, 2 Stage 2 only.

const PFD_W = 4460, PFD_H = 2130;

const STREAM_TYPES = {
  ore:    { name: "Ore / grinding slurry", color: "#c9a06a" },
  flot:   { name: "Flotation slurry",      color: "#b9b08f" },
  conc:   { name: "Concentrate",           color: "#e8a93a" },
  tails:  { name: "Tails",                 color: "#8f8a80" },
  leach:  { name: "Leach slurry",          color: "#c98a5a" },
  carbon: { name: "Carbon",                color: "#9fb0c2" },
  gold:   { name: "Gold solution / product", color: "#ffd84a" },
  water:  { name: "Water",                 color: "#4aa3df" },
  cnw:    { name: "Cyanide water",         color: "#2bb3a3" },
  reag:   { name: "Reagent",               color: "#b07cd8" },
  air:    { name: "Air / oxygen",          color: "#9fe0f0" }
};

const FRAMES = [
  { x: 20,   y: 40,   w: 540,  h: 500, label: "F10 / F12  PRIMARY CRUSHING" },
  { x: 575,  y: 40,   w: 930,  h: 650, label: "F13 / F19  MILLING & CLASSIFICATION" },
  { x: 1530, y: 60,   w: 920,  h: 200, label: "F14 / F66  GRAVITY & INTENSIVE LEACH" },
  { x: 1220, y: 760,  w: 1150, h: 505, label: "F16 / F18  FLOTATION" },
  { x: 2385, y: 1320, w: 260,  h: 200, label: "F17  TAILS THICKENING" },
  { x: 2660, y: 1320, w: 1380, h: 220, label: "F21  CIL4 FLOTATION TAILS LEACH", st: 2 },
  { x: 2950, y: 1560, w: 1100, h: 230, label: "F22 / F66  CIL4 CARBON, ELUTION, REGEN, EW", st: 2 },
  { x: 4050, y: 1320, w: 380,  h: 220, label: "F23  FINAL TAILS" },
  { x: 2430, y: 850,  w: 690,  h: 460, label: "F35 / F28 / F34  CONCENTRATE & UFG" },
  { x: 3120, y: 905,  w: 900,  h: 175, label: "F30  CONCENTRATE LEACH (CIL2 / CIL3)" },
  { x: 3690, y: 655,  w: 740,  h: 225, label: "F65 / F78  CONCENTRATE CARBON" },
  { x: 20,   y: 1330, w: 1150, h: 420, label: "F72  REAGENTS" },
  { x: 20,   y: 1860, w: 4410, h: 250, label: "F24 / F75 / F81  WATER & AIR SERVICES" }
];

// type drives the icon. d = key data rows. c = control notes. w = what you'll hear / watch for.
const NODES = [
// ---------- CRUSHING ----------
{ id:"rom", t:"rom", x:40, y:290, w:110, h:80, sn:"ROM trucks", n:"ROM pad & haul trucks", tag:"CAT 793F",
  s:"Run of mine ore arrives from the pit in CAT 793F haul trucks and is tipped direct into the crusher dump pockets.",
  d:[["Truck payload","250 t"],["Dump pocket","Direct tip, two sides, 179 m³ live one side"],["ROM size","F80 450 mm, F99 1,000 mm"]],
  c:"Red/green traffic lights tell drivers when to tip. They switch automatically from truck radar, ROM bin level, discharge chamber level, crusher running and rock breaker position.",
  hear:"'Crusher's full, trucks on hold' usually means the discharge chamber or ROM bin level interlock has the lights on red." },
{ id:"pc1", t:"crusher", x:200, y:110, w:120, h:110, sn:"Primary Crusher 1", n:"Primary Crusher 1 (existing)", tag:"F10-CG-01", area:"F10",
  s:"The original Fimiston gyratory. Feeds the existing coarse ore stockpile and the Fimiston SAG mill.",
  d:[["Model","54-75 Mk II gyratory"],["OSS","141 mm"],["Motor","450 kW"],["Rate","About 1,844 t/h when running"]],
  c:"Has a rock breaker (F10-RB-01) for oversize, a tramp magnet on the discharge conveyor and a root picker.",
  hear:"'PC1' in conversation." },
{ id:"cos1", t:"stockpile", x:380, y:110, w:150, h:110, sn:"COS (existing)", n:"Coarse Ore Stockpile (existing)", tag:"F10-SP-01", area:"F10",
  s:"Surge pile between PC1 and the Fimiston SAG. Reclaimed by four belt feeders onto the coarse ore conveyor (F15).",
  d:[["Live capacity","About 21,000 t"],["Residence","About 16 h"],["Reclaim","4 belt feeders F10-FB-01A to D"]],
  c:"Feeders controlled to the SAG feed weightometer.", hear:"" },
{ id:"pc2", t:"crusher", x:200, y:370, w:120, h:110, sn:"Primary Crusher 2", n:"Primary Crusher 2 (new)", tag:"F12-CG-401", area:"F12",
  s:"New FLS gyratory for the Growth Project. Run remotely from the existing crusher control room with CCTV.",
  d:[["Model","1300 × 1900 TSUV gyratory"],["OSS","165 mm, throw 38 mm"],["Motor","600 kW"],["Design rate","3,135 t/h (nominal 2,634 t/h)"],["Product","P80 about 130 mm"],["Availability","65%"]],
  c:"Crusher gap is adjusted automatically from a camera particle size analyser on the stockpile feed conveyor. The discharge apron feeder runs to a tonnage setpoint on the stockpile feed weightometer and is interlocked to the discharge conveyor, discharge chamber low-low and head chute high-high. Rock breaker is camera operated and parks itself.",
  hear:"Sized much faster than the mill because crushing only runs about 65% of the time. The stockpile evens it out." },
{ id:"cos2", t:"stockpile", x:380, y:370, w:150, h:110, sn:"COS (new)", n:"Coarse Ore Stockpile (new)", tag:"F12-SKP", area:"F12",
  s:"Buffer between the new crusher and new SAG mill. Two apron reclaim feeders plus one loader fed emergency feeder.",
  d:[["Live capacity","12,035 m³, about 20,460 t at 1.7 t/m³"],["Residence","About 11 h at design"],["Reclaim feeders","2 apron, 2,017 t/h design each"],["Emergency feeder","1 apron, fed by CAT 992K/994K"]],
  c:"Stockpile feed conveyor trips on the stockpile high-high switch or high-high level alarm. CCTV watches drawdown.",
  hear:"'Running on the emergency feeder' means the live pile is low and loaders are feeding the mill." },
// ---------- MILLING ----------
{ id:"fimsag", t:"mill", x:600, y:120, w:200, h:100, sn:"Fimiston SAG (existing)", n:"Fimiston SAG Mill (existing)", tag:"F19-MS-61", area:"F19",
  s:"The original SAG. In the Growth Project its discharge is pumped across to the new primary cyclone feed hopper, so it shares the new ball mill and cyclones.",
  d:[["Size","10.97 m dia × 4.27 m EGL"],["Motor","12 MW"],["Throughput","About 1,313 t/h"],["Transfer density","About 60% solids"]],
  c:"The duty/duty Fimiston mill transfer pumps run on the transfer hopper level with dilution water to hold minimum flow, and are interlocked off if the new primary cyclone feed pump isn't running.",
  hear:"If the transfer pumps trip, the old SAG has to stop or cut feed." },
{ id:"fimpeb", t:"cone", x:860, y:110, w:130, h:90, sn:"Fimiston pebble crushers", n:"Fimiston recycle crushers", tag:"F19 recycle crushers", area:"F19",
  s:"Pebble crushers on the old SAG. Crushed pebbles return to the Fimiston SAG feed conveyor.",
  d:[["Duty","Pebble recycle crushing for the Fimiston SAG"]], c:"Belt magnets remove steel ahead of the crushers.", hear:"" },
{ id:"sag", t:"mill", x:600, y:380, w:220, h:110, sn:"New SAG Mill", n:"New SAG Mill", tag:"F13-MS-401", area:"F13",
  s:"Semi autogenous mill: the ore grinds itself with a small steel ball charge. The coarse breakage stage of the SABC circuit.",
  d:[["Size","10.97 m (36 ft) dia × 8.38 m EGL"],["Motor","20 MW, pinion about 16.8 MW"],["Throughput","About 1,833 t/h"],["Speed","60 to 83% of critical (VSD)"],["Ball charge","10.5% v/v, total load 27%"],["Discharge","75% solids, 75 mm pebble ports"],["Specific energy","About 9.1 kWh/t modelled"]],
  c:"Mill expert system sets feed rate, water, mill weight and speed using the SAG feed camera size analyser, a SAG noise monitor, load, power and speed. Balls added automatically to a kg/t or mill weight setpoint. CRO must phone Parkeston Power Station before starting a mill.",
  hear:"'Mill's loading up' means weight and power rising, usually from harder or coarser feed." },
{ id:"dscr", t:"screen", x:880, y:400, w:130, h:60, sn:"SAG discharge screen", n:"SAG discharge screen", tag:"F13-SC-401", area:"F13",
  s:"Splits SAG discharge: slurry passes to the cyclone feed hopper, pebbles (oversize) go to the pebble crushers.",
  d:[["Type","Horizontal vibrating 4.27 × 8.54 m"],["Aperture","12 × 55 mm"],["Oversize","About 375 t/h pebbles"]], c:"", hear:"Worn panels let pebbles into the slurry side and the cyclone feed pump." },
{ id:"peb", t:"cone", x:880, y:545, w:130, h:90, sn:"Pebble crushers ×2", n:"Pebble crushers ×2", tag:"F13-CC-401/402", area:"F13",
  s:"Cone crushers that break SAG pebbles (critical size rock) to about 12 mm and return them to the SAG feed.",
  d:[["Model","XL7 SH-HD cone, duty/duty"],["Motor","375 kW each"],["CSS","7 mm"],["Capacity","305 t/h each (610 t/h total)"],["Pebble load","17 to 28% of new feed"]],
  c:"Metal detector in the feed triggers automatic bypass of the crusher feed bin. Bypass gate opens if the bin is High with both feeders stopped, or High-High. Feeders start on bin high level and stop on low.",
  hear:"'Pebbles on bypass' means uncrushed pebbles going back to the SAG, so the SAG load builds." },
{ id:"cfh", t:"hopper", x:1070, y:525, w:120, h:85, sn:"Cyclone feed hopper", n:"Primary cyclone feed hopper & pump", tag:"F13-HP-401 / F13-PP-401", area:"F13",
  s:"Collects SAG discharge (both SAGs), ball mill discharge and Knelson tails, and pumps it to the cyclone cluster.",
  d:[["Cyclone feed","About 14,400 t/h solids, 13,233 m³/h"],["Feed density","62% solids"]],
  c:"Water addition controls cyclone feed or overflow density. Pump runs on flow, cascaded from cyclone pressure and hopper level. Two tuning sets: Slow (smooth flotation feed) and Fast (upsets). Gland water on a mag flowmeter.",
  hear:"The heart of the grinding circuit's control." },
{ id:"cyc", t:"cyclone", x:1070, y:300, w:120, h:120, sn:"Primary cyclones", n:"Primary cyclone cluster", tag:"F13-CY-401", area:"F13",
  s:"Hydrocyclones classify by size: fines to overflow (flotation), coarse to underflow (ball mill). Two cyclones on the cluster feed gravity.",
  d:[["Model","Weir 800CVX13"],["Installed","17 (15 primary, 2 gravity)"],["Operating","About 12 primary, max 14"],["Pressure","About 82 kPa"],["Underflow","77% solids"],["Overflow","36% solids, 3,146 t/h"],["Circulating load","About 358%"],["Grind target","P80 180 µm (max 250)"]],
  c:"Air actuated knife gate on each cyclone. In Auto one extra cyclone opens if pressure stays high, one closes if low. A minimum number must be open before the pump starts.",
  hear:"'Roping' = overloaded underflow sending coarse to flotation." },
{ id:"bm", t:"mill", x:1260, y:525, w:220, h:100, sn:"Ball Mill", n:"Ball Mill", tag:"F13-MB-401", area:"F13",
  s:"Overflow ball mill finishing the grind on cyclone underflow. Fed by both SAG circuits.",
  d:[["Size","8.53 m × 13.26 m EGL"],["Motor","20 MW, pinion about 17.7 MW"],["Speed","Normally fixed at about 75% Cs (range 60 to 78)"],["Ball charge","28.5% v/v (max 31)"],["Liners","Poly-Met"],["Trommel","19 × 40 mm slots, scats to bunker"]],
  c:"Automatic ball addition. During a ball mill reline the new SAG runs single stage.", hear:"" },
{ id:"trash", t:"screen", x:1270, y:320, w:150, h:70, sn:"Trash screens ×4", n:"Trash screens ×4", tag:"F13-SL-401 to 404", area:"F13",
  s:"Remove wood, plastic and grit from cyclone overflow before flotation. Trash would blind intertank screens and UFG mills.",
  d:[["Type","Linear, 9.53 × 4.2 m"],["Running","3 duty, 1 standby"],["Aperture","1.0 × 1.0 mm"],["Trash removed","About 27 t/day"]],
  c:"CRO picks duty screens on the DCS; actuated gate valves isolate feed; spray water in the area sequence.",
  hear:"'Running three wide, no standby' means no spare screen if one blinds." },
// ---------- GRAVITY ----------
{ id:"gcyc", t:"cyclone", x:1560, y:110, w:110, h:110, sn:"Gravity cyclones", n:"Gravity cyclones ×2", tag:"on F13-CY-401", area:"F13",
  s:"Two cyclones on the main cluster set up with bigger spigots to push coarse, heavy material to gravity.",
  d:[["Underflow","About 1,000 t/h each to gravity"],["Pressure","About 83 kPa"]],
  c:"Run by their own sequences, each interlocked to its gravity screen.", hear:"" },
{ id:"gscr", t:"screen", x:1730, y:125, w:130, h:60, sn:"Gravity screens", n:"Gravity scalping screens ×2", tag:"F14-SC", area:"F14",
  s:"Protect the Knelsons from oversize. Oversize to ball mill feed, undersize to Knelsons.",
  d:[["Size","3.66 × 6.10 m"],["Aperture","3.2 × 18 mm then 2.0 × 18 mm"],["Oversize","8 to 15% (10% design)"]], c:"", hear:"" },
{ id:"kn", t:"knelson", x:1920, y:110, w:120, h:100, sn:"Knelsons ×2", n:"Knelson concentrators ×2", tag:"F14-CO", area:"F14",
  s:"Centrifugal gravity concentrators. A fluidised bowl spinning at high G traps heavy gold; lighter material washes through.",
  d:[["Model","KC-QS70"],["Feed","About 900 t/h each (max 1,000)"],["Fluidising water","120 m³/h each"],["Cycle","30 min incl. flush, 48 per day"],["Concentrate","About 150 kg per cycle, 14.4 t/day"]],
  c:"Controlled by the DCS using the vendor philosophy.", hear:"Low fluidising water = compacted bed = lost gold." },
{ id:"ilr", t:"drum", x:2100, y:115, w:130, h:90, sn:"ILR (Acacia)", n:"Intensive Leach Reactor", tag:"F14-IL", area:"F14",
  s:"Acacia batch reactor that leaches Knelson concentrate with strong cyanide and oxygen.",
  d:[["Model","Acacia CS10000"],["Batches","1 per day nominal, 2 max"],["Cycle","12 h"],["Recovery","About 98%"],["Pregnant solution","14.5 m³ per batch, over 1,000 ppm Au"]],
  c:"Cyanide and caustic come from the existing ring mains.", hear:"" },
{ id:"gew", t:"ew", x:2290, y:120, w:130, h:80, sn:"Gravity EW", n:"Gravity electrowinning", tag:"F66-CL", area:"F66",
  s:"Plates gold from the ILR pregnant solution onto cathodes.",
  d:[["Cells","Clean in place, 2 compartments × 11 cathodes"],["Flow","24 m³/h per compartment"],["Time","About 10 h per batch"],["Barren","Below 5 ppm Au"]], c:"", hear:"" },
// ---------- FLOTATION ----------
{ id:"ffb", t:"box", x:1250, y:820, w:110, h:70, sn:"Flotation feed box", n:"Flotation feed box & OSA", tag:"F16-BX-411", area:"F16",
  s:"Trash screen underflow enters here. Reagents are added and the flotation feed is sampled for the onstream analyser.",
  d:[["Feed","3,146 t/h at 34% solids, 6,719 m³/h"]],
  c:"OSA measures gold and iron; sulphur is inferred from iron. Particle size analyser on flotation feed.", hear:"" },
{ id:"r1", t:"cell", x:1420, y:800, w:110, h:100, sn:"Rougher 1", n:"Rougher cell 1", tag:"F16-CF-411", area:"F16", s:"First rougher. Floats the fast, high grade sulphides.",
  d:[["Cell","FLS forced air tank cell, 630 m³"],["Mass pull","About 4.4%"],["Concentrate","About 15% S, can go straight to final concentrate"]],
  c:"Level by two dart valves on split range control. Air by flow controller and mass flow meter; air valve closes if the agitator trips. Reversible drive. Agitators keep running whenever the cell holds slurry.", hear:"" },
{ id:"r2", t:"cell", x:1560, y:800, w:110, h:100, sn:"Rougher 2", n:"Rougher cell 2", tag:"F16-CF-412", area:"F16", s:"Second rougher. Concentrate goes to the cleaner.",
  d:[["Cell","630 m³"],["Rougher 2 + 3 mass pull","About 2.4% at about 7% S"]], c:"Same level and air control as all tank cells.", hear:"" },
{ id:"r3", t:"cell", x:1700, y:800, w:110, h:100, sn:"Rougher 3", n:"Rougher cell 3", tag:"F16-CF-413", area:"F16", s:"Third rougher. Concentrate goes to the cleaner.",
  d:[["Cell","630 m³"],["Rougher bank residence","About 15 min"]], c:"", hear:"" },
{ id:"s1", t:"cell", x:1860, y:800, w:110, h:100, sn:"Scavenger 1", n:"Scavenger cell 1", tag:"F16-CF-414", area:"F16", s:"Scavengers catch slower floating sulphides before they go to tails.",
  d:[["Cell","630 m³"],["Scavenger mass pull","About 1.1% at about 5% S"]], c:"", hear:"Scavenger tails grade rising on the OSA = gold escaping to CIL4." },
{ id:"s2", t:"cell", x:2000, y:800, w:110, h:100, sn:"Scavenger 2", n:"Scavenger cell 2", tag:"F16-CF-415", area:"F16", s:"Second scavenger.", d:[["Cell","630 m³"]], c:"", hear:"" },
{ id:"s3", t:"cell", x:2140, y:800, w:110, h:100, sn:"Scavenger 3", n:"Scavenger cell 3", tag:"F16-CF-416", area:"F16", s:"Third scavenger.", d:[["Cell","630 m³"]], c:"", hear:"" },
{ id:"s4", t:"cell", x:2280, y:800, w:110, h:100, sn:"Scavenger 4", n:"Scavenger cell 4", tag:"F16-CF-417", area:"F16", s:"Last chance for sulphides. Tails leave through the flotation discharge box to the tails thickener.",
  d:[["Scavenger bank residence","About 21 min"],["Scavenger tail","About 2,914 t/h"]], c:"", hear:"" },
{ id:"blow", t:"util", x:1250, y:1000, w:120, h:70, sn:"Flotation blowers", n:"Flotation air blowers", tag:"F24-BW", area:"F24", s:"Low pressure air for the forced air rougher and scavenger cells.",
  d:[["Control","VSDs hold constant air header pressure"]], c:"Each cell then has its own air flow controller.", hear:"" },
{ id:"jc", t:"jameson", x:1680, y:1040, w:120, h:150, sn:"Jameson cleaner", n:"Jameson cleaner", tag:"F18-CF-501", area:"F18",
  s:"Upgrades rougher 2/3, scavenger and cleaner-scavenger concentrates. Slurry is pumped as a plunging jet down downcomers that suck in air and make fine bubbles.",
  d:[["Model","Glencore Jameson B6500/24"],["Aspiration","Natural, no blower"],["Feed","About 2,000 m³/h incl. recycle"],["Froth area","22.2 m²"],["Stage S recovery","About 93%"]],
  c:"Air is set by the total pumped flow through the downcomers. Feed pump VSD holds a set flow, and about half the tails recycle to the feed hopper so jet flow stays constant.", hear:"" },
{ id:"jcs", t:"jameson", x:1960, y:1040, w:120, h:150, sn:"Jameson cleaner-scav", n:"Jameson cleaner-scavenger", tag:"F18-CF-511", area:"F18",
  s:"Gives cleaner tails another pass. Its concentrate goes back to cleaner feed; its tails go to the tails thickener.",
  d:[["Model","B6500/24"],["Feed","About 2,050 m³/h incl. recycle"],["Concentrate","About 13% S"]], c:"External recycle keeps downcomer flow constant.", hear:"" },
{ id:"fch", t:"hopper", x:2200, y:1070, w:120, h:85, sn:"Final con hopper", n:"Final concentrate hopper", tag:"F18-HP-414", area:"F18",
  s:"Collects Rougher 1 and cleaner concentrate and pumps it to the concentrate thickener.",
  d:[["Concentrate","About 876 kt/a, roughly 100 t/h"],["Flotation recovery","About 72% Au, 85% S"]], c:"Final concentrate is sampled for the OSA and accounting.", hear:"" },
// ---------- TAILS / CIL4 ----------
{ id:"ftt", t:"thickener", x:2400, y:1380, w:230, h:95, sn:"Flotation tails thickener", n:"Flotation tails thickener", tag:"F17-TH-401", area:"F17",
  s:"Thickens scavenger and cleaner-scavenger tails before leaching, and recovers water for the Process Water Tank.",
  d:[["Feed","About 3,071 t/h at 33% solids"],["Underflow","About 56% solids (50 to 62)"],["Area","2,827 m² (about 60 m dia)"],["Underflow pumps","Duty/standby, about 3,329 m³/h"]],
  c:"Underflow pumps in cascade: bed pressure or density sets a flow controller that drives the VSD. Recycle to feed on start up or low flow. Flocculant: Stage 1 from bed level (Manta sub), Stage 2 to a floc to feed solids ratio. Vendor panel shows rake torque, bed level, rake height, bed pressure, clarity.",
  hear:"'Rake torque climbing' is a classic thickener risk: a bogged thickener is a major outage." },
{ id:"c4fb", t:"box", x:2680, y:1400, w:100, h:60, sn:"CIL4 feed box", n:"CIL4 feed distribution box", tag:"F21-FD-431", area:"F21", st:2,
  s:"Where thickened tails, CIL3 tails and spent eluate meet. Milk of lime and cyanide are added here.",
  d:[["Total feed","About 3,164 t/h solids, 3,511 m³/h"]],
  c:"pH controller on tank 1 opens the milk of lime valve here. Cyanide flow set by operator or a g/t ratio on thickener underflow tonnes, trimmed by the cyanide analyser.", hear:"" },
{ id:"t411", t:"tank", x:2830, y:1370, w:120, h:120, sn:"Tank 1 · leach", n:"CIL4 Tank 1 (leach)", tag:"F21-TK-411", area:"F21", st:2,
  s:"First of two leach tanks. Gold dissolves; no carbon here.",
  d:[["Live volume","5,600 m³"],["pH","8.8 to 9.3"],["Leach residence","About 3.2 h (both tanks)"]],
  c:"VSD oxygen injection pump plus side lances. DO analyser alarms high/low. pH controller for lime.", hear:"" },
{ id:"t412", t:"tank", x:2980, y:1370, w:120, h:120, sn:"Tank 2 · leach", n:"CIL4 Tank 2 (leach)", tag:"F21-TK-412", area:"F21", st:2,
  s:"Second leach tank.", d:[["Live volume","5,600 m³"]], c:"Oxygen injection pump, side lances, dedicated cyanide line. Backup pH controller.", hear:"" },
{ id:"t413", t:"tank", x:3130, y:1370, w:120, h:120, sn:"Tank 3 · ads 1", n:"CIL4 Tank 3 (adsorption 1)", tag:"F21-TK-413", area:"F21", st:2,
  s:"First adsorption tank. Most loaded carbon is here and is pumped out to the loaded carbon screen.",
  d:[["Carbon","12.5 g/L target"],["Loaded carbon","About 330 to 580 g/t Au"]], c:"Side lance oxygen. Kemix intertank screens hold carbon back.", hear:"" },
{ id:"t414", t:"tank", x:3280, y:1370, w:120, h:120, sn:"Tank 4 · ads 2", n:"CIL4 Tank 4 (adsorption 2)", tag:"F21-TK-414", area:"F21", st:2, s:"Adsorption tank.", d:[["Live volume","5,600 m³"]], c:"Side lance oxygen.", hear:"" },
{ id:"t415", t:"tank", x:3430, y:1370, w:120, h:120, sn:"Tank 5 · ads 3", n:"CIL4 Tank 5 (adsorption 3)", tag:"F21-TK-415", area:"F21", st:2, s:"Adsorption tank with dedicated cyanide addition. Carbon Scout samples return here.", d:[["Live volume","5,600 m³"]], c:"HCN gas monitor with beacon and siren in the area.", hear:"" },
{ id:"t416", t:"tank", x:3580, y:1370, w:120, h:120, sn:"Tank 6 · ads 4", n:"CIL4 Tank 6 (adsorption 4)", tag:"F21-TK-416", area:"F21", st:2, s:"Adsorption tank.", d:[["Live volume","5,600 m³"]], c:"", hear:"" },
{ id:"t417", t:"tank", x:3730, y:1370, w:120, h:120, sn:"Tank 7 · ads 5", n:"CIL4 Tank 7 (adsorption 5)", tag:"F21-TK-417", area:"F21", st:2, s:"Adsorption tank.", d:[["Live volume","5,600 m³"]], c:"", hear:"" },
{ id:"t418", t:"tank", x:3880, y:1370, w:120, h:120, sn:"Tank 8 · ads 6", n:"CIL4 Tank 8 (adsorption 6)", tag:"F21-TK-418", area:"F21", st:2,
  s:"Last tank. Regenerated (barren) carbon enters here, where solution gold is lowest. Space in the layout for a future extra tank.",
  d:[["Total residence","About 12.8 h (below 14 h ideal)"],["Leach extraction","About 38%"],["Adsorption efficiency","About 88%"]],
  c:"Carbon detection meter on tails alarms if carbon escapes. Three stage sampler takes a shift composite.", hear:"" },
{ id:"ftk", t:"tank", x:4070, y:1385, w:110, h:100, sn:"Final tails tank", n:"Final tails tank", tag:"F23-TK-404", area:"F23",
  s:"Collects CIL4 tails, acid wash waste and fine carbon for pumping to the tailings dam.",
  d:[["Feed","About 3,164 t/h at 54.5% solids"],["Pumps","4, duty/duty/duty/standby"]],
  c:"Tank level sets each pump's flow setpoint. Each line has a flowmeter, density gauge and pressure transmitter, plus a flowmeter at the deposition end for leak detection.", hear:"" },
{ id:"tsf", t:"dam", x:4240, y:1390, w:170, h:90, sn:"Fim III TSF", n:"Tailings storage (Fim III TSF)", tag:"WBS T03", area:"T03",
  s:"Final tails are deposited here. Decant water returns to the plant as cyanide water.", d:[], c:"", hear:"" },
// ---------- CIL4 CARBON ----------
{ id:"lcs4", t:"screen", x:2980, y:1610, w:120, h:60, sn:"Loaded carbon screen", n:"CIL4 loaded carbon screen", tag:"F22-SC-421", area:"F22", st:2,
  s:"Separates loaded carbon from slurry pumped out of the first adsorption tank. Slurry returns to CIL4.",
  d:[["Type","Horizontal vibrating 1.83 × 4.88 m"],["Aperture","0.8 × 18.5 mm"]],
  c:"Loaded carbon pump started manually or by sequence when permissives are healthy.", hear:"" },
{ id:"tv4", t:"hopper", x:3140, y:1600, w:110, h:80, sn:"Transfer vessel", n:"CIL4 loaded carbon transfer vessel", tag:"F22-HP-445", area:"F22", st:2,
  s:"Holds a batch of loaded carbon for transfer into the elution column.", d:[], c:"", hear:"" },
{ id:"el4", t:"column", x:3300, y:1585, w:90, h:170, sn:"Elution column", n:"CIL4 acid wash / elution column", tag:"F22-CN", area:"F22", st:2,
  s:"Single SAF2205 duplex stainless column does both acid wash and split AARL elution.",
  d:[["Steps","Carbon in, acid wash, rinse, caustic/cyanide pre-soak, lean eluate elution, scheme water elution, cool, carbon out"],["Heating","LPG fired heater with burner management"],["Eluate","About 5 bed volumes"]],
  c:"Timed sequence using level, temperature and pressure. Column kept under pressure so hot solution doesn't flash.", hear:"'Strip 2 of 3' = second elution batch of the day." },
{ id:"eu4", t:"tank", x:3430, y:1610, w:100, h:90, sn:"Eluate tanks", n:"CIL4 eluate circulation & lean eluate tanks", tag:"F22-TK", area:"F22", st:2,
  s:"Pregnant eluate fills the circulation tanks for EW; once full, eluate diverts to the lean eluate tank for the next strip.", d:[], c:"", hear:"" },
{ id:"ew4", t:"ew", x:3570, y:1615, w:120, h:80, sn:"CIL4 EW", n:"CIL4 electrowinning", tag:"F66-CL", area:"F66", st:2,
  s:"Two split feed EW cells plate gold from pregnant eluate.", d:[["Pumps","VSD on flow control"]], c:"Batch, by sequence or manual.", hear:"" },
{ id:"kiln4", t:"kiln", x:3720, y:1615, w:160, h:75, sn:"Regen kiln + Hg abatement", n:"CIL4 regeneration kiln & mercury abatement", tag:"F22-KN", area:"F22", st:2,
  s:"Reheats barren carbon in a low oxygen atmosphere to burn off organics and restore activity. Off gas passes a mercury abatement system.",
  d:[["Vendor","Lochhead kiln package"]], c:"Vendor PLC runs the kiln inside an overall regeneration sequence; the mercury abatement must run whenever the kiln runs.", hear:"" },
{ id:"sz4", t:"screen", x:3910, y:1620, w:110, h:60, sn:"Carbon sizing screen", n:"CIL4 carbon sizing screen", tag:"F21-SC-420", area:"F21", st:2,
  s:"Removes carbon fines after quenching, then returns regenerated carbon to the last CIL4 tank.", d:[], c:"Fresh carbon is added via hoist, bag splitter and quench hopper.", hear:"" },
// ---------- CONCENTRATE ----------
{ id:"ct", t:"thickener", x:2450, y:1085, w:180, h:80, sn:"Concentrate thickener", n:"Concentrate thickener", tag:"30-TH-61 (existing)", area:"F35",
  s:"The old Fimiston Flotation Tailings Thickener No.3, repurposed in Stage 1 to thicken final concentrate.",
  d:[["Feed","About 25% solids"],["Testwork flux","0.25 t/m²/h"]], c:"", hear:"Dirty overflow = fine concentrate (and gold) lost to water." },
{ id:"fft", t:"tank", x:2680, y:1085, w:110, h:85, sn:"Filter feed tanks", n:"Filter feed tanks A & B", tag:"F35-TK", area:"F35",
  s:"Storage ahead of the UFG mills, linked by a balance line.", d:[["Density","About 60% solids"]],
  c:"Levels here and in the final concentrate hopper tell the CRO when to bring more UFG capacity online.", hear:"" },
{ id:"ufg2", t:"isamill", x:2870, y:900, w:170, h:70, sn:"UFG 2 · M15000", n:"UFG 2 IsaMill (new, Stage 1)", tag:"F28-MUF-401", area:"F28",
  s:"Horizontal stirred mill grinding concentrate to about 9 µm to crack open gold bearing pyrite.",
  d:[["Model","IsaMill M15000"],["Motor","3.8 MW, about 3.5 MW draw"],["Feed","30 t/h nominal, 46 t/h max"],["Product","P80 9 µm (9 to 12)"],["Specific energy","116.5 kWh/t"]],
  c:"Feed pump on flow control. Feed hopper water holds density, or cools the mill if discharge exceeds 60 °C. Media added by a positioning knife gate to hold a power setpoint. Shell vibration monitoring, hardwired motor interlocks, liquid resistance starter on vendor PLC.", hear:"" },
{ id:"ufg3", t:"isamill", x:2870, y:1005, w:170, h:70, sn:"UFG 3 · M15000", n:"UFG 3 IsaMill (new, Stage 2)", tag:"F28-MUF-402", area:"F28", st:2,
  s:"Second M15000 added in Stage 2 so all concentrate can be ground at Fimiston.",
  d:[["Model","IsaMill M15000"],["Feed","30 t/h nominal"],["Product","P80 9 µm"]],
  c:"Discharge hopper density by water addition, swapping to level control if low. Cyclone valves on pressure or level deadband.", hear:"" },
{ id:"ufg1", t:"isamill", x:2870, y:1110, w:170, h:70, sn:"UFG 1 · M3000", n:"UFG 1 IsaMill (existing)", tag:"F34-MU", area:"F34",
  s:"The original M3000. In Stage 2 it only takes concentrate above UFG 2/3 capacity.",
  d:[["Model","IsaMill M3000, 1,120 kW"],["Feed","About 10 t/h when running"]], c:"", hear:"" },
{ id:"filt", t:"filter", x:2870, y:1215, w:170, h:60, sn:"Belt filters & stockpile", n:"Belt filters & concentrate stockpile", tag:"F35-FI (existing)", area:"F35",
  s:"Relief path for concentrate beyond UFG capacity: deslimed, filtered and stockpiled.",
  d:[["Filters","Vacuum belt, 55 m²"],["Cake moisture","Below 10%"],["TML","6.1 to 8.3%"]], c:"", hear:"" },
{ id:"gidji", t:"offpage", x:3080, y:1215, w:120, h:60, sn:"To Gidji", n:"To Gidji (Stage 1)", tag:"off site", st:1,
  s:"In Stage 1 the balance of filtered concentrate was treated at the Gidji UFG and CIL plant. Stage 2 removes this haulage.", d:[], c:"", hear:"" },
{ id:"cil1", t:"train", x:3150, y:720, w:230, h:90, sn:"CIL1 (Stage 1)", n:"CIL1 concentrate CIL (Stage 1)", tag:"F30-TK-01/02", area:"F30", st:1, k:8,
  s:"In Stage 1, UFG product was leached in the existing CIL1 (two leach tanks then six adsorption tanks). Its tails went to CIL3.",
  d:[], c:"Stage 2 documents don't describe a role for CIL1.", hear:"" },
{ id:"plt", t:"thickener", x:3140, y:960, w:190, h:80, sn:"Pre-leach thickener", n:"Concentrate pre-leach thickener", tag:"30-TH-31 (existing)", area:"F30", st:2,
  s:"Second old Fimiston flotation tails thickener, repurposed in Stage 2 to thicken UFG product before leaching.",
  d:[["Underflow","52 to 58% solids"]],
  c:"New duty/standby VSD underflow pumps, flow cascaded from bed pressure or density. Can recycle to its own feed box.", hear:"" },
{ id:"cil2", t:"train", x:3360, y:940, w:310, h:110, sn:"CIL2 · leach (7 tanks)", n:"CIL2 concentrate leach train", tag:"30-TK-32A to 32G", area:"F30", k:7,
  s:"Stage 2: repurposed for leach only. Aggressive leach of UFG concentrate: high pH, high cyanide, lots of oxygen, lead nitrate. Stage 1: an existing CIL treating part of the flotation tails.",
  d:[["Tanks","32A to 32F plus new 32G, 1,685 m³ each"],["pH","11.75 to 12.5"],["Cyanide","Stepped up to thousands of ppm"],["Extraction","90% design"],["Feed","About 104 t/h solids"]],
  c:"Cyanide ratioed to solids mass flow on the CIL2 feed. New VSD oxygen injection pumps on the first two tanks, side lances on all. Milk of lime and lead nitrate at the feed box. New pumps move slurry from 32E/F to 32G.", hear:"" },
{ id:"cil3", t:"train", x:3720, y:940, w:280, h:110, sn:"CIL3 · adsorption (6 tanks)", n:"CIL3 concentrate adsorption train", tag:"F30-TK-62A to 62F", area:"F30", k:6,
  s:"Stage 2: repurposed for adsorption only (no oxygen). Carbon loads to very high grades. Stage 1: an existing CIL treating part of the flotation tails.",
  d:[["Tanks","6 × 1,685 m³"],["Carbon","About 20 g/L, 202 t in circuit"],["Loading","About 4,490 g/t Au"],["Intertank screens","Kemix MPSP 1200, 1.0 mm"]],
  c:"Carbon detection meter on CIL3 tails with a reference probe. CIL3 tails hopper and duty/standby VSD pumps send tails to CIL4, with cyanide water to the hopper.", hear:"" },
{ id:"lcs3", t:"screen", x:3700, y:790, w:120, h:60, sn:"Loaded carbon screen", n:"CIL3 loaded carbon screen", tag:"F65 linear motion screen", area:"F65", st:2,
  s:"New Derrick linear motion screen dewaters loaded carbon, which gravitates to a hopper and is pumped to the existing acid wash columns.",
  d:[["Aperture","0.8 × 12.8 mm"]], c:"Single new loaded carbon pump replaces the old transfer gear.", hear:"" },
{ id:"el3", t:"column", x:3860, y:690, w:100, h:140, sn:"Elution ×2 (existing)", n:"Existing elution circuits ×2", tag:"F65", area:"F65",
  s:"Two existing split AARL circuits with separate acid wash columns strip CIL3 loaded carbon.", d:[["Type","Split AARL"],["Acid","Hydrochloric acid"]], c:"", hear:"" },
{ id:"ew3", t:"ew", x:4010, y:675, w:130, h:60, sn:"Concentrate EW", n:"Concentrate EW", tag:"F66", area:"F66",
  s:"Electrowins gold from the concentrate circuit pregnant eluate.", d:[], c:"", hear:"" },
{ id:"kiln3", t:"kiln", x:4010, y:760, w:160, h:60, sn:"Regen kilns (existing)", n:"Existing regeneration kilns", tag:"F78", area:"F78",
  s:"Reactivate barren carbon from the existing elution circuits.", d:[], c:"Off gas treatment includes a regenerative thermal oxidiser.", hear:"" },
{ id:"sz3", t:"screen", x:4240, y:765, w:120, h:55, sn:"Carbon sizing screen", n:"CIL3 barren carbon sizing screen", tag:"F30-SC-412", area:"F30", st:2,
  s:"New screen sizes regenerated carbon before it goes back to CIL3. Underflow with fines goes to final tails.", d:[], c:"HCN gas monitor in the area.", hear:"" },
{ id:"gold", t:"gold", x:4240, y:1150, w:170, h:95, sn:"Goldroom", n:"Goldroom", tag:"F66", area:"F66",
  s:"Cathode sludge from all EW circuits is dried, fluxed and smelted into doré bars for the refinery.", d:[["Gold","About 1.2 Moz/a nominal design"]], c:"Security CCTV on a separate system.", hear:"" },
// ---------- REAGENTS ----------
{ id:"rg_cu", t:"reag", x:60, y:1390, w:160, h:70, sn:"Copper sulphate", n:"Copper sulphate (activator)", tag:"F72", area:"F72", s:"Activates pyrite so the collector sticks. Dosed at SAG discharge and to the cleaner.", d:[["Delivery","Bulk liquid, compressed air unloading"]], c:"VSD dosing pump on flow control, setpoint as g/t or flow.", hear:"" },
{ id:"rg_pax", t:"reag", x:250, y:1390, w:160, h:70, sn:"PAX", n:"PAX (collector)", tag:"F72", area:"F72", s:"Potassium amyl xanthate makes sulphide surfaces water repellent.", d:[["Dosing","Rougher, scavenger and cleaner feeds"]], c:"VSD dosing pumps on flow control.", hear:"" },
{ id:"rg_fr", t:"reag", x:440, y:1390, w:160, h:70, sn:"Frother", n:"Frother (Luprofroth 168)", tag:"F72", area:"F72", s:"Stabilises bubbles and froth.", d:[["Dosing","Rougher, scavenger, cleaner, cleaner-scavenger feeds"]], c:"", hear:"" },
{ id:"rg_lime", t:"reag", x:630, y:1390, w:160, h:70, sn:"Lime (MoL)", n:"Lime plant (milk of lime)", tag:"F72 / F70", area:"F72", s:"Quicklime slaked in two parallel slaking circuits and pumped round a ringmain for pH control.", d:[["Users","CIL2 feed box, CIL4 feed box"]], c:"Duty/standby DOL ringmain pumps. CIL4 pH controller opens the supply valve.", hear:"" },
{ id:"rg_cn", t:"reag", x:820, y:1390, w:160, h:70, sn:"Cyanide", n:"Sodium cyanide", tag:"F72", area:"F72", s:"Dissolves gold. Two storage tanks, pressurised ringmain.", d:[["Solution","About 29% NaCN"]], c:"DOL ringmain pumps with a mechanical back pressure valve on the return. Flowmeter at each dosing point. HCN monitors in storage and use areas.", hear:"" },
{ id:"rg_pb", t:"reag", x:60, y:1520, w:160, h:70, sn:"Lead nitrate", n:"Lead nitrate", tag:"F72", area:"F72", st:2, s:"Speeds up gold leaching of sulphide concentrate by countering passivation. Dosed at the CIL2 feed box.", d:[], c:"VSD pumps on flow, setpoint as g/t.", hear:"" },
{ id:"rg_fl", t:"reag", x:250, y:1520, w:160, h:70, sn:"Flocculant", n:"Flocculant plant", tag:"F72", area:"F72", s:"Mixes powdered flocculant into solution for all thickeners.", d:[], c:"Automated screw feeder, heated cone, blower, wetting head. Existing thickener floc pumps cascaded from bed level.", hear:"" },
{ id:"rg_hcl", t:"reag", x:440, y:1520, w:160, h:70, sn:"HCl", n:"Hydrochloric acid", tag:"F72", area:"F72", s:"Acid washes carbon to remove scale. Separate dilute acid tank for CIL4.", d:[], c:"DOL pumps started by the elution sequences.", hear:"" },
{ id:"rg_na", t:"reag", x:630, y:1520, w:160, h:70, sn:"Caustic", n:"Caustic (NaOH)", tag:"F72", area:"F72", s:"Elution pre-soak and pH control. Pressurised ringmain.", d:[], c:"Tank heater on below about 20 °C, off above 25 °C to stop freezing.", hear:"" },
{ id:"rg_h2", t:"reag", x:820, y:1520, w:160, h:70, sn:"H₂O₂", n:"Hydrogen peroxide", tag:"F72", area:"F72", s:"Destroys cyanide in decant water.", d:[["Target","Residual WAD CN about 1.5"]], c:"Dosing controlled by an online WAD cyanide analyser and flowmeters on each decant line.", hear:"" },
{ id:"rg_lpg", t:"reag", x:60, y:1650, w:160, h:70, sn:"LPG", n:"LPG", tag:"F72", area:"F72", st:2, s:"Fuel for the CIL4 elution heater.", d:[], c:"", hear:"" },
{ id:"rg_as", t:"reag", x:250, y:1650, w:160, h:70, sn:"Antiscalant", n:"Antiscalant", tag:"F72", area:"F72", s:"Limits scale in water and solution circuits.", d:[], c:"IBC skids with manually set metering pumps. The only reagent not on DCS dosing control.", hear:"" },
// ---------- SERVICES ----------
{ id:"sch", t:"util", x:60, y:1920, w:170, h:75, sn:"Scheme water", n:"Scheme water", tag:"Goldfields pipeline", area:"F24", s:"Fresh water, SG 1.00. Used where salt can't be tolerated: elution, reagent make up, UFG gland seals, safety showers.", d:[], c:"", hear:"" },
{ id:"dams", t:"util", x:280, y:1920, w:190, h:75, sn:"Saline dams", n:"Bore water / saline dams", tag:"Dam 2 (South), Dam 3", area:"F24", s:"Saline bore water (Kaltails borefield and others). Dam 2 tops up process water; Dam 3 feeds the Raw Water Tank.", d:[["Process water SG","About 1.07"]], c:"Three DOL saline pumps trip on Dam 2 low-low level.", hear:"" },
{ id:"rwt", t:"tank", x:520, y:1915, w:120, h:90, sn:"Raw water tank", n:"Raw Water Tank", tag:"F24-TK", area:"F24", s:"Lower portion is reserved for the LP and HP gland water pumps.", d:[], c:"Level held by a dedicated level control valve.", hear:"" },
{ id:"gland", t:"util", x:690, y:1920, w:170, h:75, sn:"Gland water", n:"Gland water pumps (LP / HP)", tag:"F24-PW", area:"F24", s:"Clean seal water to slurry pump glands.", d:[], c:"Each pump: manual isolation, actuated valve opened in the start sequence, Maric constant flow valve, flow switch. Low flow blocks start and trips after a delay.", hear:"" },
{ id:"pwt", t:"tank", x:1000, y:1915, w:130, h:90, sn:"Process water tank", n:"Process Water Tank", tag:"F24-TK", area:"F24", s:"Main plant water, mostly flotation tails thickener overflow, topped up from Bore Water Dam 2.", d:[], c:"Duty/standby pumps; level loop controls top up.", hear:"" },
{ id:"hpw", t:"util", x:1180, y:1920, w:180, h:75, sn:"Mill & HP water", n:"Mill & HP process water", tag:"F24", area:"F24", s:"Distribution to mills, cyclone hopper dilution, sprays, trash screens and launders.", d:[], c:"All water headers have pressure control.", hear:"" },
{ id:"air", t:"util", x:1420, y:1920, w:180, h:75, sn:"Plant & instr. air", n:"Plant & instrument air", tag:"F24 / F81", area:"F24", s:"Compressed air. Instrument air is dried and filtered for valve actuators.", d:[], c:"Compressors controlled from the DCS on pressure.", hear:"" },
{ id:"o2", t:"util", x:1660, y:1920, w:180, h:75, sn:"Oxygen plant", n:"Oxygen plant", tag:"PSA + liquid O₂", area:"F72", s:"Supplies oxygen to CIL2 leach, CIL4 leach and the ILR.", d:[], c:"Free issued package by the principal.", hear:"" },
{ id:"cnw", t:"tank", x:4250, y:1915, w:130, h:90, sn:"Cyanide water tank", n:"Cyanide water tank", tag:"TSF decant return", area:"F75", s:"TSF decant water returns here after peroxide cyanide destruct, for reuse in the plant.", d:[["Flow","About 1,900 to 2,000 m³/h"]], c:"Peroxide dosed through inline mixers on the three decant lines.", hear:"" }
];

// Streams. p = [fromSide, toSide] (r,l,t,b); fo/too = offset along side (-0.5..0.5);
// mx / my = x or y of the middle elbow; via = extra waypoints; lab = short label; i = info rows.
const STREAMS = [
{ id:"s_rom1", f:"rom", to:"pc1", ty:"ore", p:["t","l"], n:"ROM ore to PC1", i:[["Via","Dump pocket, rock breaker for oversize"]] },
{ id:"s_rom2", f:"rom", to:"pc2", ty:"ore", p:["b","l"], n:"ROM ore to PC2", i:[["Size","F80 450 mm"],["Trucks","CAT 793F, 250 t"]] },
{ id:"s_pc1", f:"pc1", to:"cos1", ty:"ore", p:["r","l"], n:"PC1 product to stockpile", i:[["Conveyor","F10-CV-01, tramp magnet"]] },
{ id:"s_pc2", f:"pc2", to:"cos2", ty:"ore", p:["r","l"], n:"PC2 product to stockpile", lab:"2,634 t/h", i:[["Rate","2,634 t/h nominal, 3,135 t/h design"],["Size","P80 about 130 mm"],["Weightometer","Stockpile feed, sets apron feeder speed"]] },
{ id:"s_cos1", f:"cos1", to:"fimsag", ty:"ore", p:["r","l"], n:"Fimiston SAG feed", lab:"1,313 t/h", i:[["Conveyor","F15 coarse ore conveyor to F19 SAG feed conveyor"],["Rate","About 1,313 t/h"]] },
{ id:"s_cos2", f:"cos2", to:"sag", ty:"ore", p:["r","l"], n:"New SAG feed", lab:"1,833 t/h", i:[["Rate","About 1,833 t/h (2,182 t/h high case)"],["Control","Reclaim feeders to SAG feed weightometer or mill weight setpoint, deadband for lag"]] },
{ id:"s_fpeb", f:"fimsag", to:"fimpeb", ty:"ore", p:["r","l"], n:"Fimiston SAG pebbles", i:[] },
{ id:"s_fpebr", f:"fimpeb", to:"fimsag", ty:"ore", p:["t","t"], my:80, n:"Crushed pebbles back to Fimiston SAG", i:[] },
{ id:"s_ftr", f:"fimsag", to:"cfh", ty:"ore", p:["b","t"], fo:0.3, too:-0.3, my:300, via:[[760,300],[1040,300],[1040,500],[1106,500]], n:"Fimiston SAG discharge transfer", lab:"transfer pumps", i:[["Pumps","Duty/duty Fimiston mill transfer pumps"],["Density","About 60% solids"],["Interlock","Stops if primary cyclone feed pump not running"]] },
{ id:"s_sagd", f:"sag", to:"dscr", ty:"ore", p:["r","l"], n:"SAG discharge", i:[["Density","75% solids"],["Trommel","12 × 40 mm"]] },
{ id:"s_dsu", f:"dscr", to:"cfh", ty:"ore", p:["r","l"], fo:0, too:-0.2, mx:1040, n:"Discharge screen undersize", i:[] },
{ id:"s_dso", f:"dscr", to:"peb", ty:"ore", p:["b","t"], n:"Pebbles to pebble crushers", i:[["Rate","About 375 t/h (up to 610 t/h with worn ports)"],["Protection","Magnets and metal detector, automatic bypass"]] },
{ id:"s_pebr", f:"peb", to:"sag", ty:"ore", p:["l","b"], n:"Crushed pebbles to SAG feed", i:[["Size","P80 about 12 mm"]] },
{ id:"s_cf", f:"cfh", to:"cyc", ty:"ore", p:["t","b"], n:"Cyclone feed", lab:"13,233 m³/h", i:[["Flow","13,233 m³/h, 14,400 t/h solids"],["Density","62% solids"],["Pressure","About 82 kPa"]] },
{ id:"s_cuf", f:"cyc", to:"bm", ty:"ore", p:["r","t"], fo:0.3, too:-0.3, n:"Cyclone underflow to ball mill", lab:"UF 77%", i:[["Solids","About 11,275 t/h at 77%"],["Circulating load","About 358%"]] },
{ id:"s_bmd", f:"bm", to:"cfh", ty:"ore", p:["b","b"], my:660, n:"Ball mill discharge", i:[["Trommel","19 × 40 mm, scats to bunker"]] },
{ id:"s_cof", f:"cyc", to:"trash", ty:"ore", p:["r","l"], fo:-0.3, n:"Cyclone overflow", lab:"P80 180 µm", i:[["Solids","3,146 t/h at 36% solids"],["Grind","P80 180 µm target"]] },
{ id:"s_gcf", f:"cyc", to:"gcyc", ty:"ore", p:["t","l"], via:[[1130,160]], n:"Feed to gravity cyclones", i:[] },
{ id:"s_guf", f:"gcyc", to:"gscr", ty:"ore", p:["r","l"], n:"Gravity cyclone underflow", i:[["Rate","About 1,000 t/h each"]] },
{ id:"s_gso", f:"gscr", to:"bm", ty:"ore", p:["b","t"], fo:0, too:0.3, my:250, n:"Scalping screen oversize to ball mill", i:[["Split","About 10% to oversize"]] },
{ id:"s_gsu", f:"gscr", to:"kn", ty:"ore", p:["r","l"], n:"Gravity feed to Knelsons", lab:"1,800 t/h", i:[["Rate","About 900 t/h per Knelson"],["Density","About 54% solids"]] },
{ id:"s_knt", f:"kn", to:"cfh", ty:"ore", p:["b","r"], fo:0, too:0, my:280, via:[[1980,280],[1215,280],[1215,567]], n:"Knelson tails to cyclone feed hopper", i:[] },
{ id:"s_knc", f:"kn", to:"ilr", ty:"gold", p:["r","l"], n:"Knelson concentrate", lab:"14.4 t/d", i:[["Mass","About 150 kg per cycle, 14.4 t/day"]] },
{ id:"s_ilp", f:"ilr", to:"gew", ty:"gold", p:["r","l"], n:"ILR pregnant solution", i:[["Volume","14.5 m³ per batch"],["Grade","About 1,100 to 1,800 ppm Au"]] },
{ id:"s_gg", f:"gew", to:"gold", ty:"gold", p:["r","t"], via:[[4440,160],[4440,1110],[4325,1110]], n:"Gravity gold to goldroom", i:[["Product","Cathode sludge"]] },
{ id:"s_tf", f:"trash", to:"ffb", ty:"flot", p:["b","t"], via:[[1345,760],[1305,760]], n:"Trash screen underflow to flotation", lab:"3,146 t/h", i:[["Flow","6,719 m³/h at 34% solids"]] },
{ id:"s_f1", f:"ffb", to:"r1", ty:"flot", p:["r","l"], n:"Flotation feed", i:[] },
{ id:"s_f2", f:"r1", to:"r2", ty:"flot", p:["r","l"], n:"Rougher 1 tails", i:[] },
{ id:"s_f3", f:"r2", to:"r3", ty:"flot", p:["r","l"], n:"Rougher 2 tails", i:[] },
{ id:"s_f4", f:"r3", to:"s1", ty:"flot", p:["r","l"], n:"Rougher tail to scavengers", lab:"2,946 t/h", i:[["Rate","2,946 t/h, 6,051 m³/h"]] },
{ id:"s_f5", f:"s1", to:"s2", ty:"flot", p:["r","l"], n:"Scavenger 1 tails", i:[] },
{ id:"s_f6", f:"s2", to:"s3", ty:"flot", p:["r","l"], n:"Scavenger 2 tails", i:[] },
{ id:"s_f7", f:"s3", to:"s4", ty:"flot", p:["r","l"], n:"Scavenger 3 tails", i:[] },
{ id:"s_st", f:"s4", to:"ftt", ty:"tails", p:["r","t"], too:0.3, via:[[2560,850]], n:"Scavenger tails to tails thickener", lab:"2,914 t/h", i:[["Rate","2,914 t/h, 5,952 m³/h"]] },
{ id:"s_air", f:"blow", to:"r1", ty:"air", p:["r","b"], via:[[1475,1035]], n:"Blower air to tank cells", hide:true, i:[["Control","Blower VSD on header pressure, cell flow controllers"]] },
{ id:"s_r1c", f:"r1", to:"fch", ty:"conc", p:["b","b"], fo:-0.3, too:-0.2, my:1250, n:"Rougher 1 concentrate to final concentrate", i:[["Mass pull","About 4.4%"],["Grade","About 15% S"]] },
{ id:"s_r23c", f:"r2", to:"jc", ty:"conc", p:["b","t"], too:-0.3, my:960, n:"Rougher 2 & 3 concentrate to cleaner", i:[["Mass pull","About 2.4%"],["Grade","About 7% S"]] },
{ id:"s_sc", f:"s1", to:"jc", ty:"conc", p:["b","t"], too:0.3, my:975, n:"Scavenger concentrate to cleaner", i:[["Mass pull","About 1.1%"],["Grade","About 5% S"]] },
{ id:"s_jcc", f:"jc", to:"fch", ty:"conc", p:["r","l"], fo:-0.35, too:-0.2, mx:1900, via:[[1900,1092],[2150,1092]], n:"Cleaner concentrate", i:[["Stage recovery","About 93% S"]] },
{ id:"s_jct", f:"jc", to:"jcs", ty:"conc", p:["r","l"], fo:0.3, too:0.3, n:"Cleaner tails to cleaner-scavenger", i:[["Split","About half recycled to cleaner feed, rest here"]] },
{ id:"s_jcr", f:"jc", to:"jc", ty:"conc", p:["b","l"], fo:0, too:0.2, via:[[1740,1232],[1655,1232],[1655,1145]], n:"Cleaner tails external recycle", i:[["Purpose","Keeps downcomer (jet) flow constant"]] },
{ id:"s_jsc", f:"jcs", to:"jc", ty:"conc", p:["t","t"], my:1010, n:"Cleaner-scavenger concentrate to cleaner feed", i:[["Grade","About 13% S"]] },
{ id:"s_jst", f:"jcs", to:"ftt", ty:"tails", p:["b","t"], too:-0.3, my:1255, via:[[2020,1255],[2469,1255]], n:"Cleaner-scavenger tails to tails thickener", i:[] },
{ id:"s_fc", f:"fch", to:"ct", ty:"conc", p:["r","l"], n:"Final concentrate to thickener", lab:"~100 t/h", i:[["Rate","About 876 kt/a"],["Thickener","Existing 30-TH-61"]] },
{ id:"s_ctu", f:"ct", to:"fft", ty:"conc", p:["r","l"], n:"Concentrate thickener underflow", i:[["Density","About 60% solids"]] },
{ id:"s_u2", f:"fft", to:"ufg2", ty:"conc", p:["t","l"], fo:-0.2, via:[[2713,935]], n:"UFG 2 feed", i:[["Rate","30 t/h nominal"]] },
{ id:"s_u3", f:"fft", to:"ufg3", ty:"conc", p:["r","l"], fo:-0.3, mx:2830, st:2, n:"UFG 3 feed", i:[["Rate","30 t/h nominal"]] },
{ id:"s_u1", f:"fft", to:"ufg1", ty:"conc", p:["r","l"], fo:0.15, mx:2845, n:"UFG 1 feed", i:[["Stage 2","Only concentrate beyond UFG 2/3 capacity"]] },
{ id:"s_uf", f:"fft", to:"filt", ty:"conc", p:["b","l"], n:"Excess concentrate to filters", i:[["When","Concentrate exceeds UFG capacity; deslimed first"]] },
{ id:"s_gj", f:"filt", to:"gidji", ty:"conc", p:["r","l"], st:1, n:"Filtered concentrate to Gidji", i:[] },
{ id:"s_p2", f:"ufg2", to:"plt", ty:"conc", p:["r","l"], too:-0.2, mx:3090, st:2, n:"UFG 2 product (cyclone overflow)", lab:"P80 9 µm", i:[["Size","P80 9 µm"]] },
{ id:"s_p3", f:"ufg3", to:"plt", ty:"conc", p:["r","l"], too:0.1, mx:3090, st:2, n:"UFG 3 product", i:[] },
{ id:"s_p1", f:"ufg1", to:"plt", ty:"conc", p:["r","l"], too:0.3, mx:3090, st:2, n:"UFG 1 product", i:[] },
{ id:"s_p2a", f:"ufg2", to:"cil1", ty:"conc", p:["r","l"], mx:3100, st:1, n:"UFG product to CIL1 (Stage 1)", i:[] },
{ id:"s_p1a", f:"ufg1", to:"cil1", ty:"conc", p:["r","l"], too:0.3, mx:3110, st:1, n:"UFG 1 product to CIL1 (Stage 1)", i:[] },
{ id:"s_plu", f:"plt", to:"cil2", ty:"leach", p:["r","l"], st:2, n:"Pre-leach thickener underflow to CIL2", lab:"104 t/h", i:[["Rate","About 104 t/h solids"],["Density","52 to 58% solids"],["Control","Cyanide ratioed to solids mass flow"]] },
{ id:"s_c23", f:"cil2", to:"cil3", ty:"leach", p:["r","l"], n:"CIL2 discharge to CIL3", i:[["Stage 2","Via new tank 32G and new transfer pumps"]] },
{ id:"s_c1t", f:"cil1", to:"cil3", ty:"leach", p:["r","t"], too:-0.3, st:1, n:"CIL1 tails to CIL3 (Stage 1)", i:[] },
{ id:"s_c3t", f:"cil3", to:"c4fb", ty:"leach", p:["b","t"], my:1300, st:2, n:"CIL3 tails to CIL4", i:[["Pumps","New CIL3 tails hopper, duty/standby VSD pumps"],["Why","Reuses residual cyanide and catches any dissolved gold"]] },
{ id:"s_c3f", f:"cil3", to:"ftk", ty:"tails", p:["b","t"], fo:0.35, my:1310, st:1, n:"CIL2/3 tails to final tails (Stage 1)", i:[] },
{ id:"s_ttu", f:"ftt", to:"c4fb", ty:"tails", p:["r","l"], st:2, n:"Thickened flotation tails to CIL4", lab:"56% solids", i:[["Rate","About 3,071 t/h, 3,329 m³/h"],["Control","Bed pressure / density → flow → pump VSD"]] },
{ id:"s_ttc", f:"ftt", to:"cil2", ty:"tails", p:["r","b"], fo:-0.3, via:[[2660,1300],[3515,1300]], st:1, n:"Thickened tails to existing CIL2/3 (Stage 1)", i:[["Control","Flow control valves to match existing CIL capacity"]] },
{ id:"s_ttf", f:"ftt", to:"ftk", ty:"tails", p:["b","l"], fo:0.3, via:[[2537,1535],[4040,1535],[4040,1435]], st:1, n:"Balance of thickened tails to final tails (Stage 1)", i:[] },
{ id:"s_c40", f:"c4fb", to:"t411", ty:"leach", p:["r","l"], st:2, n:"CIL4 feed", lab:"3,511 m³/h", i:[["Solids","About 3,164 t/h"],["Adds","Milk of lime, cyanide"]] },
{ id:"s_c41", f:"t411", to:"t412", ty:"leach", p:["r","l"], st:2, n:"Tank 1 to 2", i:[] },
{ id:"s_c42", f:"t412", to:"t413", ty:"leach", p:["r","l"], st:2, n:"Tank 2 to 3", i:[] },
{ id:"s_c43", f:"t413", to:"t414", ty:"leach", p:["r","l"], st:2, n:"Tank 3 to 4", i:[] },
{ id:"s_c44", f:"t414", to:"t415", ty:"leach", p:["r","l"], st:2, n:"Tank 4 to 5", i:[] },
{ id:"s_c45", f:"t415", to:"t416", ty:"leach", p:["r","l"], st:2, n:"Tank 5 to 6", i:[] },
{ id:"s_c46", f:"t416", to:"t417", ty:"leach", p:["r","l"], st:2, n:"Tank 6 to 7", i:[] },
{ id:"s_c47", f:"t417", to:"t418", ty:"leach", p:["r","l"], st:2, n:"Tank 7 to 8", i:[] },
{ id:"s_c4t", f:"t418", to:"ftk", ty:"tails", p:["r","l"], st:2, n:"CIL4 tails to final tails", i:[["Sampling","Three stage shift composite sampler"],["Carbon check","Carbon detection meter"]] },
{ id:"s_tsf", f:"ftk", to:"tsf", ty:"tails", p:["r","l"], n:"Final tails to TSF", lab:"to dam", i:[["Pumps","Duty/duty/duty/standby"],["Leak detection","Flowmeters at both ends of each line"]] },
// carbon CIL4
{ id:"k_48", f:"t418", to:"t417", ty:"carbon", p:["t","t"], fo:-0.25, too:0.25, my:1350, st:2, n:"Carbon advance 8 → 7", i:[["Direction","Counter current to slurry"]] },
{ id:"k_47", f:"t417", to:"t416", ty:"carbon", p:["t","t"], fo:-0.25, too:0.25, my:1350, st:2, n:"Carbon advance 7 → 6", i:[] },
{ id:"k_46", f:"t416", to:"t415", ty:"carbon", p:["t","t"], fo:-0.25, too:0.25, my:1350, st:2, n:"Carbon advance 6 → 5", i:[] },
{ id:"k_45", f:"t415", to:"t414", ty:"carbon", p:["t","t"], fo:-0.25, too:0.25, my:1350, st:2, n:"Carbon advance 5 → 4", i:[] },
{ id:"k_44", f:"t414", to:"t413", ty:"carbon", p:["t","t"], fo:-0.25, too:0.25, my:1350, st:2, n:"Carbon advance 4 → 3", i:[["Method","Recessed impeller pumps; Carbon Scout checks g/L"]] },
{ id:"k_4l", f:"t413", to:"lcs4", ty:"carbon", p:["b","t"], fo:0.3, st:2, n:"Loaded carbon to screen", i:[["Loading","About 330 to 580 g/t"]] },
{ id:"k_4r", f:"lcs4", to:"t413", ty:"leach", p:["l","b"], fo:0, too:-0.3, via:[[2960,1640],[2960,1520],[3160,1520]], st:2, n:"Screen underflow slurry back to CIL4", i:[] },
{ id:"k_4t", f:"lcs4", to:"tv4", ty:"carbon", p:["r","l"], st:2, n:"Loaded carbon to transfer vessel", i:[] },
{ id:"k_4e", f:"tv4", to:"el4", ty:"carbon", p:["r","l"], st:2, n:"Loaded carbon into elution column", i:[] },
{ id:"k_4p", f:"el4", to:"eu4", ty:"gold", p:["r","l"], fo:-0.2, st:2, n:"Pregnant eluate", i:[["Volume","About 5 bed volumes"]] },
{ id:"k_4w", f:"eu4", to:"ew4", ty:"gold", p:["r","l"], st:2, n:"Eluate to EW", i:[] },
{ id:"k_4g", f:"ew4", to:"gold", ty:"gold", p:["t","b"], too:-0.2, via:[[3630,1560],[4274,1560]], st:2, n:"CIL4 gold to goldroom", i:[] },
{ id:"k_4b", f:"el4", to:"kiln4", ty:"carbon", p:["b","b"], my:1775, st:2, n:"Barren carbon to regeneration kiln", i:[["Method","Educted to kiln dewatering screen and feed hopper"]] },
{ id:"k_4k", f:"kiln4", to:"sz4", ty:"carbon", p:["r","l"], st:2, n:"Regenerated carbon via quench tank", i:[] },
{ id:"k_4s", f:"sz4", to:"t418", ty:"carbon", p:["t","b"], fo:-0.2, too:0.2, st:2, n:"Sized carbon back to last CIL4 tank", i:[] },
// carbon CIL3
{ id:"k_3l", f:"cil3", to:"lcs3", ty:"carbon", p:["t","b"], fo:-0.35, st:2, n:"CIL3 loaded carbon to screen", i:[["Loading","About 4,490 g/t"]] },
{ id:"k_3e", f:"lcs3", to:"el3", ty:"carbon", p:["r","l"], too:0.3, st:2, n:"Loaded carbon to existing acid wash / elution", i:[] },
{ id:"k_3p", f:"el3", to:"ew3", ty:"gold", p:["r","l"], fo:-0.3, n:"Concentrate circuit pregnant eluate", i:[] },
{ id:"k_3g", f:"ew3", to:"gold", ty:"gold", p:["r","t"], too:0.2, via:[[4410,705],[4410,1090],[4359,1090]], n:"Concentrate gold to goldroom", i:[] },
{ id:"k_3b", f:"el3", to:"kiln3", ty:"carbon", p:["r","l"], fo:0.3, n:"Barren carbon to existing kilns", i:[] },
{ id:"k_3k", f:"kiln3", to:"sz3", ty:"carbon", p:["r","l"], st:2, n:"Regenerated carbon to sizing screen", i:[] },
{ id:"k_3s", f:"sz3", to:"cil3", ty:"carbon", p:["b","r"], fo:0, too:0.3, via:[[4300,1023]], st:2, n:"Sized carbon back to CIL3", i:[] },
{ id:"k_3f", f:"sz3", to:"ftk", ty:"tails", p:["r","t"], too:0.2, via:[[4380,793],[4380,1300],[4147,1300]], st:2, n:"Fine carbon and acid effluent to final tails", hide:true, i:[] },
// water
{ id:"w_ov", f:"ftt", to:"pwt", ty:"water", p:["b","t"], via:[[2515,1840],[1065,1840]], n:"Thickener overflow to Process Water Tank", i:[["Share","Main source of process water"]] },
{ id:"w_d2", f:"dams", to:"pwt", ty:"water", p:["b","b"], my:2050, n:"Saline top up (Dam 2)", i:[["Pumps","Three DOL saline pumps, trip on dam low-low"]] },
{ id:"w_d3", f:"dams", to:"rwt", ty:"water", p:["r","l"], n:"Dam 3 to Raw Water Tank", i:[["Pumps","Raw water feed booster pumps"]] },
{ id:"w_gl", f:"rwt", to:"gland", ty:"water", p:["r","l"], n:"Raw water to gland pumps", i:[] },
{ id:"w_glp", f:"gland", to:"cfh", ty:"water", p:["t","b"], via:[[775,1850],[1180,1850],[1180,700],[1150,700]], n:"Gland water to slurry pumps", i:[["Users","Every slurry pump gland, e.g. cyclone feed, thickener underflow, final tails"]] },
{ id:"w_pw", f:"pwt", to:"hpw", ty:"water", p:["r","l"], n:"Process water to distribution", i:[] },
{ id:"w_mw", f:"hpw", to:"cfh", ty:"water", p:["t","b"], fo:0.2, too:0.3, via:[[1306,1830],[1200,1830],[1200,690],[1166,690]], n:"Mill water to cyclone feed hopper", i:[["Control","Controls cyclone feed or overflow density"]] },
{ id:"w_kf", f:"hpw", to:"kn", ty:"water", p:["t","b"], fo:-0.2, via:[[1234,1850],[1210,1850],[1210,300],[1965,300]], n:"Fluidising water to Knelsons", i:[["Flow","120 m³/h each"]] },
{ id:"w_sc", f:"sch", to:"el4", ty:"water", p:["b","b"], via:[[145,2085],[3345,2085]], st:2, n:"Scheme water to CIL4 elution", i:[["Use","Elution, cooling, carbon transfer"]] },
{ id:"w_su", f:"sch", to:"ufg2", ty:"water", p:["t","b"], via:[[145,1830],[2890,1830],[2890,1290],[2955,1290]], hide:true, n:"Scheme water to UFG gland seals", i:[] },
{ id:"w_dec", f:"tsf", to:"cnw", ty:"cnw", p:["b","t"], n:"TSF decant return", i:[["Treatment","Hydrogen peroxide via inline mixers on 3 decant lines"],["Control","Online WAD cyanide analyser"]] },
{ id:"w_cnw", f:"cnw", to:"cil3", ty:"cnw", p:["l","b"], fo:0, too:0.45, via:[[4230,1960],[4230,1810],[4020,1810],[4020,1060],[3970,1060]], n:"Cyanide water to plant users", i:[["Users","e.g. CIL3 tails hopper, carbon handling"]] },
{ id:"w_o2a", f:"o2", to:"t411", ty:"air", p:["t","b"], via:[[1750,1845],[2890,1845]], st:2, n:"Oxygen to CIL4 leach", i:[["Method","VSD oxygen injection pumps and side lances"]] },
{ id:"w_o2b", f:"o2", to:"cil2", ty:"air", p:["t","b"], fo:0.3, via:[[1804,1850],[3380,1850],[3380,1060],[3400,1060]], n:"Oxygen to CIL2 leach", i:[["Method","New injection pumps on first two tanks, side lances"]] },
// reagents (shown with Reagents flow)
{ id:"r_cu", f:"rg_cu", to:"sag", ty:"reag", p:["t","b"], fo:0, too:0.3, via:[[140,1310],[776,1310]], rg:1, n:"Copper sulphate to SAG discharge", i:[] },
{ id:"r_pax", f:"rg_pax", to:"ffb", ty:"reag", p:["t","b"], via:[[330,1320],[1305,1320]], rg:1, n:"PAX to flotation feed and cleaners", i:[] },
{ id:"r_fr", f:"rg_fr", to:"ffb", ty:"reag", p:["t","b"], too:0.3, via:[[520,1300],[1338,1300]], rg:1, n:"Frother to flotation", i:[] },
{ id:"r_li", f:"rg_lime", to:"c4fb", ty:"reag", p:["b","b"], via:[[710,1810],[2730,1810]], rg:1, st:2, n:"Milk of lime to CIL4 feed box", i:[["Control","pH controller on tank 1"]] },
{ id:"r_cn", f:"rg_cn", to:"c4fb", ty:"reag", p:["b","b"], fo:0.2, too:0.3, via:[[932,1800],[2760,1800]], rg:1, st:2, n:"Cyanide to CIL4", i:[["Control","Flow controller, g/t ratio, analyser trim"]] },
{ id:"r_cn2", f:"rg_cn", to:"cil2", ty:"reag", p:["r","b"], fo:0, too:-0.3, via:[[1100,1425],[1100,1290],[3422,1290]], rg:1, n:"Cyanide to CIL2", i:[["Control","Ratioed to CIL2 feed solids"]] },
{ id:"r_pb", f:"rg_pb", to:"cil2", ty:"reag", p:["t","b"], fo:0.3, too:-0.4, via:[[188,1480],[1110,1480],[1110,1280],[3391,1280]], rg:1, st:2, n:"Lead nitrate to CIL2 feed box", i:[] },
{ id:"r_fl", f:"rg_fl", to:"ftt", ty:"reag", p:["b","b"], via:[[330,1795],[2450,1795]], rg:1, n:"Flocculant to tails thickener", i:[["Control","Stage 2: ratio to feed solids"]] },
{ id:"r_hcl", f:"rg_hcl", to:"el4", ty:"reag", p:["b","b"], fo:0, too:-0.2, via:[[520,1780],[2920,1780],[2920,1790],[3327,1790]], rg:1, st:2, n:"Dilute HCl to CIL4 column", i:[] },
{ id:"r_na", f:"rg_na", to:"el4", ty:"reag", p:["b","b"], too:0.2, via:[[710,1785],[3363,1785]], rg:1, st:2, n:"Caustic to CIL4 elution pre-soak", i:[] },
{ id:"r_h2", f:"rg_h2", to:"cnw", ty:"reag", p:["b","l"], via:[[900,1830],[4180,1830],[4180,1960]], rg:1, n:"Hydrogen peroxide to decant lines", i:[] },
{ id:"r_lpg", f:"rg_lpg", to:"el4", ty:"reag", p:["b","b"], via:[[140,1800],[140,1820],[3345,1820]], rg:1, st:2, n:"LPG to elution heater", hide:true, i:[] }
];

// Control loops badge layer. n: node it sits on. pv measured, mv moved.
const LOOPS = [
{ n:"pc2", dx:-10, dy:-14, name:"Crusher gap", pv:"Camera particle size on stockpile feed conveyor", mv:"Crusher setting (gap)", txt:"Automatic crusher gap adjustment keeps product size on target as the mantle and concaves wear." },
{ n:"cos2", dx:130, dy:-14, name:"Stockpile feed rate", pv:"Stockpile feed weightometer (t/h)", mv:"Discharge apron feeder speed", txt:"Apron feeder speed is trimmed to an operator tonnage setpoint. Interlocked to the discharge conveyor, chamber low-low and head chute high-high." },
{ n:"sag", dx:-12, dy:-14, name:"SAG feed rate / mill weight", pv:"SAG feed weightometer or mill weight", mv:"Reclaim apron feeder speeds", txt:"Normally set by the mill expert system. A deadband allows for the delay between feeder speed change and the weightometer reading." },
{ n:"cfh", dx:-12, dy:-14, name:"Cyclone feed hopper", pv:"Hopper level, cyclone feed density", mv:"Pump flow setpoint (VSD) and dilution water", txt:"Water addition holds cyclone feed or overflow density. Pump flow is cascaded from cyclone pressure and hopper level. Slow tuning keeps flotation feed steady, Fast tuning recovers upsets." },
{ n:"cyc", dx:105, dy:-14, name:"Cyclone pressure", pv:"Distributor pressure", mv:"Number of cyclones open (knife gates)", txt:"One cyclone opens if pressure stays high, one closes if low. In cascade, hopper level sets the pressure setpoint. Minimum cyclones open before pump start." },
{ n:"peb", dx:115, dy:-14, name:"Pebble bin", pv:"Bin level, metal detector", mv:"Crusher feeders, bypass gate", txt:"Feeders start on high level, stop on low. Bypass opens on metal detected, bin High with both feeders stopped, or High-High." },
{ n:"r1", dx:95, dy:-14, name:"Cell level & air", pv:"Cell level; air mass flow", mv:"Two dart valves (split range); air control valve", txt:"Each tank cell holds a level (froth depth) setpoint with split range dart valves, and an air flow setpoint. Expert control uses froth and launder velocity cameras and the OSA. Air valve closes on agitator trip." },
{ n:"jc", dx:105, dy:-14, name:"Jameson flow", pv:"Feed pump discharge flow", mv:"Feed pump VSD, recycle", txt:"Constant volumetric flow through the downcomers sets the jet and therefore the air. External tails recycle makes up for changes in new feed." },
{ n:"ftt", dx:-12, dy:-14, name:"Thickener underflow & floc", pv:"Bed pressure or underflow density; bed level / feed solids", mv:"Underflow pump VSD (via flow loop); floc pump speed", txt:"Cascade: bed pressure or density sets the underflow flow controller, which drives the pump VSD. Flocculant from bed level (Stage 1) or a ratio to feed solids (Stage 2). Recycle to feed at low flow." },
{ n:"ufg2", dx:155, dy:-14, name:"IsaMill power & temperature", pv:"Mill power draw; discharge temperature", mv:"Media knife gate; feed hopper water", txt:"Media is metered in to hold a power setpoint. Feed water holds density, or cools the mill above 60 °C." },
{ n:"t411", dx:-12, dy:-14, name:"CIL4 pH, cyanide, DO", pv:"Tank 1 pH; cyanide analyser; DO analyser", mv:"Milk of lime valve; cyanide flow valve; oxygen flow valves", txt:"pH controller opens the lime valve at the feed box. Cyanide by flow controller, set by operator or g/t on thickener tonnes, trimmed by analyser. Oxygen by flow controller to the injection pump injectors." },
{ n:"cil2", dx:-12, dy:-14, name:"CIL2 cyanide ratio", pv:"CIL2 feed flow × density = solids t/h", mv:"Cyanide flow control valve", txt:"Cyanide delivery is ratioed to the mass of solids in the pre-leach thickener underflow; downstream tanks have their own flow controllers." },
{ n:"el4", dx:75, dy:-14, name:"Elution sequence & heater", pv:"Eluate temperature, column level and pressure", mv:"LPG burner, valves, elution pumps", txt:"Timed sequence steps through every stage. Temperature controller feeds the LPG burner management system. Elution pumps on flow control." },
{ n:"ftk", dx:95, dy:-14, name:"Final tails pumping", pv:"Final tails tank level", mv:"Each pump's flow setpoint (VSD)", txt:"Level sets the flow. Flowmeters at both ends of each line give leak detection." },
{ n:"cnw", dx:-12, dy:-14, name:"Cyanide destruct", pv:"Online WAD cyanide analyser, decant flow", mv:"Hydrogen peroxide dosing", txt:"Peroxide is dosed through inline mixers on the three decant lines to a residual WAD target." },
{ n:"gland", dx:155, dy:-14, name:"Gland water permissive", pv:"Gland water flow switch / mag meter", mv:"Pump start permissive and trip", txt:"Actuated valve opens as part of the pump start sequence; Maric valve gives constant flow. Low flow blocks the start and trips a running pump after a delay." }
];

// Flow walkthroughs. ids = streams/nodes to highlight for each step.
const FLOWS = [
{ id:"main", name:"Ore & slurry main line", color:"#c9a06a", desc:"The bulk tonnage path from haul truck to tailings dam.",
  steps:[
   { t:"ROM ore is tipped into Primary Crusher 2 (and PC1 for the Fimiston SAG). The gyratory breaks it to about 130 mm.", ids:["rom","s_rom1","s_rom2","pc1","pc2"] },
   { t:"Crushed ore builds the coarse ore stockpiles, the surge buffer between 65% crusher availability and 93% mill availability.", ids:["s_pc1","s_pc2","cos1","cos2"] },
   { t:"Apron feeders reclaim to the new SAG and belt feeders to the Fimiston SAG.", ids:["s_cos1","s_cos2","sag","fimsag"] },
   { t:"Both SAGs discharge to the primary cyclone feed hopper (the old SAG via its transfer pumps).", ids:["s_sagd","dscr","s_dsu","s_ftr","cfh"] },
   { t:"Cyclones split the slurry. Underflow goes to the ball mill and back; overflow at P80 180 µm is the flotation feed.", ids:["s_cf","cyc","s_cuf","bm","s_bmd","s_cof"] },
   { t:"Trash screens remove wood and plastic, then slurry feeds the rougher and scavenger cells.", ids:["trash","s_tf","ffb","s_f1","r1","s_f2","r2","s_f3","r3","s_f4","s1","s_f5","s2","s_f6","s3","s_f7","s4"] },
   { t:"Scavenger and cleaner-scavenger tails are thickened from about 33% to 56% solids.", ids:["s_st","s_jst","ftt"] },
   { t:"Stage 2: thickened tails are leached in CIL4 (2 leach + 6 adsorption tanks). Stage 1: part went to the old CIL2/3, the rest straight to final tails.", ids:["s_ttu","c4fb","s_c40","t411","s_c41","t412","s_c42","t413","s_c43","t414","s_c44","t415","s_c45","t416","s_c46","t417","s_c47","t418","s_ttc","s_ttf"] },
   { t:"CIL4 tails go to the final tails tank and are pumped to the Fim III TSF.", ids:["s_c4t","ftk","s_tsf","tsf"] }
  ] },
{ id:"grind", name:"Grinding recycle loops", color:"#e08a4a", desc:"The loops that make an SABC circuit work, and why they matter.",
  steps:[
   { t:"Pebble loop: SAG discharge screen oversize (critical size rock) goes to the cone crushers and returns to SAG feed. Pebble crushers down = SAG load builds.", ids:["sag","s_sagd","dscr","s_dso","peb","s_pebr"] },
   { t:"Cyclone loop: coarse underflow goes to the ball mill and its discharge comes back to the hopper. Circulating load is about 358%, like a pump recirculation loop that keeps the mill full of near sized material.", ids:["cfh","s_cf","cyc","s_cuf","bm","s_bmd"] },
   { t:"Gravity loop: two cyclones feed the scalping screens and Knelsons; Knelson tails return to the hopper, so coarse gold gets many chances to be caught.", ids:["s_gcf","gcyc","s_guf","gscr","s_gso","s_gsu","kn","s_knt"] },
   { t:"Fimiston loop: the old SAG has its own pebble crushers, then sends its discharge to the shared hopper.", ids:["fimsag","s_fpeb","fimpeb","s_fpebr","s_ftr"] }
  ] },
{ id:"flot", name:"Flotation circuit", color:"#b9b08f", desc:"How concentrate is pulled from the slurry and upgraded, including the Jameson recycles.",
  steps:[
   { t:"Rougher 1 floats the fastest, richest sulphides (about 15% S). That concentrate can go straight to the final concentrate hopper.", ids:["r1","s_r1c","fch"] },
   { t:"Roughers 2 and 3 and the scavengers float slower, lower grade material. It goes to the Jameson cleaner for upgrading.", ids:["r2","r3","s1","s2","s3","s4","s_r23c","s_sc","jc"] },
   { t:"The cleaner rejects gangue. Half its tails recycle to keep the jet flow constant; the rest go to the cleaner-scavenger.", ids:["jc","s_jcr","s_jct","jcs"] },
   { t:"Cleaner-scavenger concentrate returns to cleaner feed. Its tails join the scavenger tails at the thickener.", ids:["s_jsc","s_jst","ftt"] },
   { t:"Cleaner concentrate joins Rougher 1 concentrate in the final concentrate hopper. That's about 72% of the gold in about 4% of the mass.", ids:["s_jcc","fch"] }
  ] },
{ id:"conc", name:"Concentrate & gold path", color:"#e8a93a", desc:"Where the small, rich stream goes, and every route gold takes to the goldroom.",
  steps:[
   { t:"Final concentrate is thickened in the old 30-TH-61 and stored in filter feed tanks A and B.", ids:["fch","s_fc","ct","s_ctu","fft"] },
   { t:"IsaMills grind it to P80 9 µm. Stage 2 runs UFG 2 and 3, with UFG 1 taking any excess. Beyond that, concentrate is filtered and stockpiled (Stage 1: to Gidji).", ids:["s_u2","s_u3","s_u1","ufg2","ufg3","ufg1","s_uf","filt","s_gj","gidji"] },
   { t:"Stage 2: UFG product is thickened in 30-TH-31, then leached hard in CIL2 (high pH, high cyanide, oxygen, lead nitrate). Stage 1: UFG product went to CIL1.", ids:["s_p2","s_p3","s_p1","plt","s_plu","cil2","s_p2a","s_p1a","cil1"] },
   { t:"CIL3 carbon adsorbs the dissolved gold (loading about 4,500 g/t). CIL3 tails go on to CIL4 to catch what's left.", ids:["s_c23","cil3","s_c3t","s_c1t"] },
   { t:"Gravity gold: Knelson concentrate is leached in the ILR and electrowon directly.", ids:["kn","s_knc","ilr","s_ilp","gew","s_gg"] },
   { t:"All EW circuits (gravity, concentrate, CIL4) send cathode product to the goldroom for smelting into doré.", ids:["k_3p","ew3","k_3g","k_4p","eu4","k_4w","ew4","k_4g","gold"] }
  ] },
{ id:"carbon", name:"Carbon loop", color:"#9fb0c2", desc:"Carbon moves against the slurry, is stripped, regenerated and returned.",
  steps:[
   { t:"Regenerated carbon enters the LAST CIL4 tank, where solution gold is lowest.", ids:["sz4","k_4s","t418"] },
   { t:"Carbon is pumped upstream tank by tank, counter current to the slurry, loading more gold each step. Like a counterflow heat exchanger. The Carbon Scout checks g/L in every tank.", ids:["k_48","k_47","k_46","k_45","k_44","t417","t416","t415","t414","t413"] },
   { t:"Loaded carbon is pumped from the first adsorption tank to the loaded carbon screen; slurry goes back to CIL4.", ids:["k_4l","lcs4","k_4r","k_4t","tv4"] },
   { t:"The CIL4 column acid washes and elutes (split AARL); pregnant eluate goes to EW.", ids:["k_4e","el4","k_4p","eu4"] },
   { t:"Barren carbon is regenerated in the kiln (with mercury abatement), quenched and sized, then goes back to the last tank.", ids:["k_4b","kiln4","k_4k","sz4"] },
   { t:"CIL3 has the same idea: loaded carbon to the new linear screen and the existing elution circuits, barren carbon through the existing kilns and new sizing screen back to CIL3.", ids:["k_3l","lcs3","k_3e","el3","k_3b","kiln3","k_3k","sz3","k_3s","cil3"] }
  ] },
{ id:"water", name:"Water circuits", color:"#4aa3df", desc:"Saline process water, fresh scheme water, gland water and cyanide water.",
  steps:[
   { t:"Thickener overflow is the main process water source, topped up with saline bore water from Dam 2. Process water SG is about 1.07.", ids:["ftt","w_ov","pwt","dams","w_d2"] },
   { t:"Process water is distributed as mill water and HP water: cyclone hopper dilution (density control), sprays and Knelson fluidising water.", ids:["w_pw","hpw","w_mw","w_kf","cfh","kn"] },
   { t:"Dam 3 feeds the Raw Water Tank, whose lower part is reserved for gland water to every slurry pump.", ids:["w_d3","rwt","w_gl","gland","w_glp"] },
   { t:"Scheme (fresh) water is used only where salt can't be tolerated, such as elution.", ids:["sch","w_sc","el4"] },
   { t:"TSF decant returns as cyanide water after hydrogen peroxide treatment and is reused in the plant.", ids:["tsf","w_dec","cnw","w_cnw"] }
  ] },
{ id:"reag", name:"Reagents & oxygen", color:"#b07cd8", desc:"What gets dosed where, and how it's controlled.",
  steps:[
   { t:"Flotation reagents: copper sulphate at SAG discharge (conditioning time), PAX and frother at flotation feed. VSD pumps on g/t setpoints.", ids:["rg_cu","r_cu","rg_pax","r_pax","rg_fr","r_fr","ffb","sag"] },
   { t:"Leach reagents: milk of lime and cyanide at the CIL4 feed box, cyanide ratioed to solids at CIL2, lead nitrate at the CIL2 feed box.", ids:["rg_lime","r_li","rg_cn","r_cn","r_cn2","rg_pb","r_pb","c4fb","cil2"] },
   { t:"Oxygen from the oxygen plant to CIL2 and CIL4 leach tanks through injection pumps and side lances.", ids:["o2","w_o2a","w_o2b","t411","cil2"] },
   { t:"Elution reagents: dilute HCl for acid wash, caustic for the pre-soak, LPG for the heater.", ids:["rg_hcl","r_hcl","rg_na","r_na","rg_lpg","r_lpg","el4"] },
   { t:"Flocculant to the thickeners, and hydrogen peroxide for cyanide destruct on decant water.", ids:["rg_fl","r_fl","ftt","rg_h2","r_h2","cnw"] }
  ] }
];

// Operating scenarios from the control philosophy (mill relines).
const SCENARIOS = [
  { id:"normal", name:"Normal operation", off:[], txt:"Both SAG mills and the ball mill running, sharing the primary cyclone cluster." },
  { id:"bm", name:"Ball mill reline", off:["bm"], txt:"New SAG runs single stage while the ball mill is relined. Reduced throughput." },
  { id:"fsag", name:"Fimiston SAG reline", off:["fimsag","fimpeb","cos1","pc1"], txt:"The new SABC circuit (new SAG, pebble crushers, ball mill) runs on its own. Reduced throughput." },
  { id:"nsag", name:"New SAG reline", off:["sag","dscr","peb","cos2","pc2"], txt:"The Fimiston SAG and new ball mill run together. Reduced throughput." }
];
